### ISSUE TITLE
pvacseq example code from "Getting Started" page

### ISSUE THREAD

**Issue by nitishnih** [griffithlab/pVACtools#1008]
Hi, 

I was running the example code for pvacseq shown here:
https://pvactools.readthedocs.io/en/latest/pvacseq/getting_started.html#getting-started

I ran:
```
pvacseq download_example_data .
pvacseq run \
 pvacseq_example_data/input.vcf \
 HCC1395_TUMOR_DNA \
 HLA-A*29:02,HLA-B*45:01,DRB1*04:05 \
 all \
 pvacseq_example_output \
 -e1 8,9,10 \
 -e2 15 \
 --normal-sample-name HCC1395_NORMAL_DNA
```
The first command finished successfully. The second gave the following error:
```
Executing MHC Class I predictions
Converting .vcf to TSV
/usr/local/lib/python3.7/site-packages/vcfpy/header.py:288: DuplicateHeaderLineWarning: Seen FILTER header more than once: PASS, using firstoccurence
  DuplicateHeaderLineWarning,
normal_sample_name HCC1395_NORMAL_DNA provided but the input file is a single-sample (tumor only) VCF
```

If I deleted the `pvacseq_example_output` directory and restarted pvacseq without the `--normal-sample-name` option, then it worked. Am I doing something wrong or does the documentation need to be updated?

**Comment by susannasiebert** [comment]
This totally is a mistake on our part. The VCF should be `pvacseq_example_data/annotated.expression.vcf.gz`. However, I'm confused that your example worked with the VCF input.vcf because that file is no longer part of the newest example data in version 4.0. You should've received an error that a file with such name was not found. Are you using an older version of pVACtools?

**Comment by nitishnih** [comment]
Thanks for the response and pointing out the problem. I pull the docker container `griffithlab/pvactools:latest-slim` using singularity. This was done on July 21st but I didn't know that was still pvactools version 3.1.3. I mistakenly assumed it was the newer 4.0.1 version. I'll correct this and pull 4.0.1 explicitly. Thanks again!

**Comment by susannasiebert** [comment]
Thank you for pointing that out. 4.0 no longer has xs and slim versions so the latest-xs and latest-slim are outdated. I will remove them.

**Comment by susannasiebert** [comment]
The documentation has been updated and the latest-xs and latest-slim images have been removed. Closing this issue.
