### ISSUE TITLE
mismatch between the actual wildtype amino acid and the expected amino acid

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVACtools#101]
Original report by @huangxiaogua

hello,when I run pvacseq the results indicated an ERROR: There was a mismatch between the actual wildtype amino acid and the expected amino acid. Did you use the same reference build version for VEP that you used for creating the VCF? Following are the details:

Generating Variant Peptide FASTA and Key Files - Entries 801-1000
Generating Variant Peptide FASTA and Key Files - Entries 1001-1200
ERROR: There was a mismatch between the actual wildtype amino acid and the expected amino acid. Did you use the same reference build version for VEP that you used for creating the VCF?
{'reference': 'A', 'stop': '145365433', 'start': '145365432', 'index': 'NBPF10.NM_001039703.5.missense.3426H/R', 'transcript_expression': 'NA', 'trna_depth': 'NA', 'tdna_vaf': 'NA', 'tdna_depth': 'NA', 'normal_depth': 'NA', 'transcript_name': 'NM_001039703.5', 'gene_expression': 'NA', 'wildtype_amino_acid_sequence': 'MVVSAGPWSSEKAEMNILEINETLRPQLAEKKQQFRSLKEKCFLTQLAGFLANRQKKYKYEECKDLIKFMLRNERQFKEEKLAEQLKQAEELRQYKVLVHSQERELTQLREKLREGRDASRSLYEHLQALLTPDEPDKSQGQDLQEQLAEGCRLAQHLVQK

I had got vcf file from sentieon TNseq by online app, the Reference genome was ucsc_hg19.fa.gz and GATK resource bundle was hg19.gatk.resource.bundle.tar.gz.
The vep command was ./vep --cache --port 3337 -i /home/jm/DATA/output_p0001.vcf --format vcf -o /home/jm/DATA/p0001vepout3.vcf --vcf --offline --use_given_ref --no_stats --symbol --terms SO --dir_plugins /home/jm/vep/dir/Plugins --plugin Downstream --plugin Wildtype.
I used the vep_GRCh37 references.

Then I run the pvacseq with the command pvacseq run p0001vepout3.vcf Test HLA-A*11:01 NetMHC resultc05 -e 9 --tdna-vaf 20 --net-chop-method cterm --netmhc-stab --top-score-metric=lowest -d full --keep-tmp-files
Whether my references has some errors? Thank you

**Comment by susannasiebert** [comment]
@huangxiaogua. Can you please post the rest of the error message, if it is available. The wildtype_amino_acid_sequence seems to be cut off and there are other fields I'm expecting to see. Also,  are you using the pvactools package or the pvacseq package? Which version do you have installed?

**Comment by huangxiaogua** [comment]
Thank you for your consideration, I used pvactools 1.0.2. I have found the  mistake that when we installed the vep, we uesd a mismatch references  version between the files name and the real references data.

**Comment by HugoMananet** [comment]
Hi, I'm currently getting the same error : 


Converting .vcf to TSV
frameshift_variant transcript does not contain a DownstreamProtein sequence. Skipping.
chr5 96077274 AGGTGGAGAAG A NM_001750.6
frameshift_variant transcript does not contain a DownstreamProtein sequence. Skipping.
chr7 151945071 G GT NM_170606.2
Completed
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-36
Completed
Generating Variant Peptide FASTA and Key Files
Generating Variant Peptide FASTA and Key Files - Entries 1-72
ERROR: There was a mismatch between the actual wildtype amino acid sequence (T) and the expected amino acid sequence (P). Did you use the same reference build version for VEP that you used for creating the VCF?
OrderedDict([('chromosome_name', 'chr7'), ('start', '100550427'), ('stop', '100550428'), ('reference', 'C'), ('variant', 'T'), ('gene_name', 'MUC3A'), ('transcript_name', 'NM_005960.1'), ('transcript_support_level', 'NA'), ('amino_acid_change', 'P/S'), ('codon_change', 'Cct/Tct'), ('ensembl_gene_id', '4584'), ('hgvsc', 'NM_005960.1:c.1009C>T'), ('hgvsp', 'NP_005951.1:p.Pro337Ser'), ('wildtype_amino_acid_sequence', 'MQLLGLLGLLWMLKASPWATGTLSTATSISQVPFPRAEAASAVLSNSPHSRDLAGWPLGVPQLASPAPGHRENAPMTLTTSPHDTLISETLLNSPVSSNTSTTPTSKFAFKVETTPPTVLVYSATTECVYPTSFIITISHPTSICVTTTQVAFTSSYTSTPVTQKPVTTVTSTYSMTTTEKGTSAMTSSPSTTTARETPIVTVTPSSVSATDTTFHTTISSTTRTTERTPLPTGSIHTTTSPTPVFTTLKTAVTSTSPITSSITSTNTVTSMTTTASQPTATNTLSSPTRTILSSTPVLSTETITSGITNTTPLSTLVTTLPTTISRSTPTSETTYTTSPTSTVTDSTTKIAYSTSMTGTLSTETSLPPTSSSLPTTETATTPMTNLVTTTTEISSHSTPSFSSSTIYSTVSTSTTAISSLPPTSGTMVTSTTMTPSSLSTDIPFTTPTTITHHSVGSTGFLTTATDLTSTFTVSSSSAMSTSVIPSSPSIQNTETSSLVSMTSATTPNVRPTFVSTLSTPTSSLLTTFPATYSFSSSMSASSAGTTHTESISSPPASTSTLHTTAESTLAPTTTTSFTTSTTMEPPSTTAATTGTGQTTFTSSTATFPETTTPTPTTDMSTESLTTAMTSPPITSSVTSTNTVTSMTTTTSPPTTTNSFTSLTSMPLSSTPVPSTEVVTSGTINTIPPSILVTTLPTPNASSMTTSETTYPNSPTGPGTNSTTEITYPTTMTETSSTATSLPPTSPLVSTAKTAKTPTTNLVTTTTKTTSHSTTSFTSSTVYSTASTYTTAITSVPTTLGTMVTSTSMISSTVSTGIPTSQPTTITPSSVGISGSLPMMTDLTSVYTVSNMSARPTTVIPSSPTVQNTEISISVSMTSATTPSGGPTFTSTENTPTRSLLTSFPMTHSFSSSMSESSAGTTHTESISSPRGTTSTLHTTVESTPSPTTTTSFTTSTMMEPPSSTVSTTGRGQTTFPSSTATFPETTTLTPTTDISTVSLTTAMTSPPPVSSSITPTNTMTSMRTTTYWPTATNTLSPLTSSILSSTPVPSTEMITSHTTNTTPLSTLVTTLLTTITRSTPTSETTYPTSPTSIVSDSTTEITYSTSITGTLSTATTLPPTSSSLPTTETATMTPTTTLITTTPNTTSLSTPSFTSSTIYSTVSTSTTAISSASPTSGTMVTSTTMTPSSLSTDTPSTTPTTITYPSVGSTGFLTTATDLTSTFTVSSSSAMSTSVIPSSPSIQNTETSSLVSMTSATTPSLRPTITSTDSTLTSSLLTTFPSTYSFSSSMSASSAGTTHTETISSLPASTNTIHTTAESALAPTTTTSFTTSPTMEPPSTTVATTGTGQTTFPSSTATFLETTTLTPTTDFSTESLTTAMTSTPPITSSITPTDTMTSMRTTTSWPTATNTLSPLTSSILSSTPVPSTEVTTSHTTNTNPVSTLVTTLPITITRSTLTSETAYPSSPTSTVTESTTEITYPTTMTETSSTATSLPPTSSLVSTAETAKTPTTNLVTTTTKTTSHSTTSFTSSTIYSTASTPTTAITSVPTTLGTMVTSTSMIPSTVSTGIPTSQPTTITPSSVGISGSLPMMTDLTSVYTVSSMSARPTSVIPSSPTVQNTETSIFVSMMSATTPSGGPTFTSTENTPTRSLLTSFPVTHSFSSSMSASSVGTTHTQSISSPPAITSTLHTTAESTPSPTTTMSFTTFTKMETPSSTVATTGTGQTTFTSSTATSPKTTTLTPTSDISTGSFKTAVSSTPPITSSITSTYTVTSMTTTTPLGPTATNTLPSFTSSVSSSTPVPSTEAITSGTTNTTPLSTLVTTFSNSDTSSTPTSETTYPTSLTSALTDSTTRTTYSTNMTGTLSTVTSLRPTSSSLLTTVTATVPTTNLVTTTTKITSHSTPSFTSSIATTETPSHSTPRFTSSITTTETPSHSTPRFTSSITNTKTTSHSSPSFTSSITTTETTSHNTPSLTSSITTTKTTSHSTPSYTSLITTTTTTSHSTPSFTSSITTTETTSHNTPSLTSSITTTETTSHSTPSFTSSITTETTSHSTPSFTSLITITEITSHSTLSYTTSITTTETPSHSTLSFTSSITTTETTSHSTPSFTSSITTSEMPSHSTPSFTSSITTTENATHSTPNFTSSITTTETTSHSTPSFTSLITTTETTSHRWGTTETTSYSTPSFTSSNTITETTSHSTPSYITSITTTETPSSSTPSFSSSITTTETTSHSTPGFTSSITTTETTSHSTPSFTSSITTTETTSHDTPSFTSSITTSETPSHSTPSSTSLITTTKTTSHSTPSFTSSITTTETTSHSAHSFTSSITTTETTSHNTRSFTSSITTTETNSHSTTSFTSSITTTETTSHSTPSFSSSITTTETPLHSTPGLTSWVTTTKTTSHITPGLTSSITTTETTSHSTPGFTSSITTTETTSESTPSLSSSTIYSTVSTSTTAITSHFTTSETAVTPTPVTPSSLSTDIPTTSLRTLTPSSVGTSTSLTTTTDFPSIPTDISTLPTRTHIISSSPSIQSTETSSLVGTTSPTMSTVRMTLRITENTPISSFSTSIVVIPETPTQTPPVLTSATGTQTSPAPTTVTFGSTDSSTSTLHTLTPSTALSTIVSTSQVPIPSTHSSTLQTTPSTPSLQTSLTSTSEFTTESFTRGSTSTNAILTSFSTIIWSSTPTIIMSSSPSSASITPVFSTTIHSVPSSPYIFSTENVGSASITGFPSLSSSATTSTSSTSSSLTTALTEITPFSYISLPSTTPCPGTITITIVPASPTDPCVEMDPSTEATSPPTTPLTVFPFTTEMVTCPTSISIQTTLTTYMDTSSMMPESESSISPNASSSTGTGTVPTNTVFTSTRLPTSETWLSNSSVIPLPLPGVSTIPLTMKPSSSLPTILRTSSKSTHPSPPTTRTSETPVATTQTPTTLTSRRTTRITSQMTTQSTLTTTAGTCDNGGTWEQGQCACLPGFSGDRCQLQTRCQNGGQWDGLKCQCPSTFYGSSCEFAVEQVDLDVVETEVGMEVSVDQQFSPDLNDNTSQAYRDFNKTFWNQMQKIFADMQGFTFKGVEILSLRNGSIVVDYLVLLEMPFSPQLESEYEQVKTTLKEGLQNASQDVNSCQDSQTLCFKPDSIKVNNNSKTELTPAAICRRAAPTGYEEFYFPLVEATRLRCVTKCTSGVDNAIDCHQGQCVLETSGPTCRCYSTDTHWFSGPRCEVAVHWRALVGGLTAGAALLVLLLLALGVRAVRSGWWGGQRRGRSWDQDRKWFETWDEEVVGTFSNWGFEDDGTDKDTNFYVALENVDTTMKVHIKRPEMTSSSV'), ('downstream_amino_acid_sequence', ''), ('fusion_amino_acid_sequence', ''), ('variant_type', 'missense'), ('protein_position', '337'), ('transcript_expression', 'NA'), ('gene_expression', 'NA'), ('normal_depth', 'NA'), ('normal_vaf', 'NA'), ('tdna_depth', 'NA'), ('tdna_vaf', 'NA'), ('trna_depth', 'NA'), ('trna_vaf', 'NA'), ('index', '12.MUC3A.NM_005960.1.missense.337P/S'), ('protein_length_change', '')])

I'm using the same reference file (hg19) for all steps : 
alignment, variant calling, and annotations with VEP (--fasta)

I tried upgrading pvactools (from 1.1.5 to 1.5.4) in a container (singularity) but this type of error still occur in some cases (most analyses work well)

I tried to change VEP versions, but the same errors occur for the same samples.


my command line is : 

pvacseq run -e 8,9,10  --iedb-install-directory /opt/iedb N16-10_final.vcf N16-10 HLA-A*24:02,HLA-A*24:20,HLA-A*26:08,HLA-A*26:01,HLA-B*40:01,HLA-B*07:02,HLA-B*14:01,HLA-B*14:56,HLA-C*08:02,HLA-C*14:02 NetMHC results_pvactools/

Do you have any advice on how to solve this ?

**Comment by susannasiebert** [comment]
This error occurs when the reference bases of a VCF entry are different than the Ensembl transcript nucleotides at that position. This results in the mutant amino acid in the Amino_acids VEP annotation being different from the amino acid of the transcript protein sequence as predicted by the Wildtype plugin. The Amino_acids VEP annotation is based on the reference and alternate nucleotides of the variant while the WildtypeProtein prediction is based on the Ensembl transcript nucleotide sequence.

This points to a fundamental disagreement between the reference that was used during alignment and variant calling and the Ensembl reference. This mismatch cannot be resolved by pVACseq, which is why this error is fatal.

To resolve this you would need to either "fix" the reference bases of your variant and reannotating your VCF or use a Ensembl version that uses the same reference for the transcript sequence while running VEP. I'm not sure why the ---fasta option in VEP doesn't achieve the latter. We recommend that you file a ticket with VEP/Ensembl for help in resolving this issue.

**Comment by HugoMananet** [comment]
Thanks a lot for your quick and concise answer , i will try to resolve this working on the annotation side of things.
