### ISSUE TITLE
pvactools reports different EL rank from  NetMHCpan 4.1

### ISSUE THREAD

**Issue by ysbioinfo** [griffithlab/pVACtools#1018]
### Installation Type

Standalone

### pVACtools Version / Docker Image

4.0.1

### Python Version

3.8.3

### Operating System

Centos7

### Describe the bug

Hi,
I want to use the new feature implemented in pvactools -- NetMHCpanEL. However, it seems that the EL Rank given by pvactools is different from that by NetMHCpan4.1 (official website). For example,

The binding of AAYDYCENY with HLA-A*01:02

- pvactools results: NetMHCpanEL.MT.Percentile: 0.37, NetMHCpanEL.MT.Score: 0.363
- NetMHCpan4.1 results: %Rank_EL: 0.575 Score_EL: 0.363.

I also check some other peptides, all of the EL_scores are same, while the EL_rank are usually different. Do you know where the cause is? 

Thanks!
Yang

### How to reproduce this bug

```Shell
See above
```

### Log output

See above

**Comment by susannasiebert** [comment]
Hi @ysbioinfo,
I apologize for the late reply to your question. pVACtools uses the IEDB API to make binding predictions. The results you are getting are consistent with the API results:

**Comment by ysbioinfo** [comment]
Hi @susannasiebert ,
Thanks for your kind reply. Look forward to your updates after the communication with IEDB.

Yang

**Comment by susannasiebert** [comment]
I received the following response from IEDB:
> It is expected to see different percentile rank values as we recalculate percentile ranks based on our own datasets so that all of our MHCI methods can be based on the same data, which is why you are seeing the difference.

**Comment by ysbioinfo** [comment]
Thanks for your clarification!
