### ISSUE TITLE
Where there are multiple transcript sets in pVACview, select the one containing the top peptide

### ISSUE THREAD

**Issue by malachig** [griffithlab/pVACtools#1034]
Currently, in pVACview if one hits the "Investigate" button for a row, in the "Variant Information" section below, "Transcript Sets of Selected Variant", the first transcript set is always selected.  Even if that is not the one that corresponds to the best peptide.  The right transcript set is highlighted in green, but its not the one that is active.  

This can lead to confusion.  If possible it would be great to have the same logic used to highlight the correct row, also be used to make sure that is the selected row.  

If its not active, when you scroll down further to look at individual peptides you are looking at the wrong ones.

**Comment by susannasiebert** [comment]
An alternate solution would be to output the transcript set containing the best transcript first in the metrics file which would put it first in the display.

**Comment by malachig** [comment]
Yeah, I don't see any obvious scheme being used to set the order of transcript sets right now.  So if ordering them like this cause the top one to be selected initially, that would make sense.  

This behavior continues to cause a lot of confusion.
