### ISSUE TITLE
SUGGESTION Add specific anchoring residues for alleles H2-Db, Kb, Dd, Hd and Kd from https://doi.org/10.1084/jem.20190179

### ISSUE THREAD

**Issue by PierreLaplante** [griffithlab/pVACtools#1047]
This [paper ](https://doi.org/10.1084/jem.20190179)defined anchoring residues for 6 of the MHC-I mice alleles, for 8, 9, 10 and 11-mer peptides, and found increased discrimination of immunogenic neoepitopes.

Would you consider adding the option to define them as anchoring residues in the pipeline?

**Comment by susannasiebert** [comment]
This is a great suggestion. I will discuss this with the team.

**Comment by susannasiebert** [comment]
This feature is now available in version 4.3.0.
