### ISSUE TITLE
pVACview demo: some candidates dont show anchor heatmap

### ISSUE THREAD

**Issue by mhoang22** [griffithlab/pVACtools#1059]
### Installation Type

Standalone

### pVACtools Version / Docker Image

NA

### Describe the bug

When I use the demo data for pvacview, 2 candidates: ARID1B (5th candidate) and HSPA4 (6th candidate) dont show anchor heatmap. Other candidates show normal anchor heatmap. 

### How to reproduce this bug

```Shell
I Loaded demo data on pvacview (https://griffithlab.shinyapps.io/pvacview/)
```

### Input files

The demo data for pvacview 

### Log output

NA

### Output files

![Screen Shot 2024-02-06 at 2 14 01 PM](https://github.com/griffithlab/pVACtools/assets/98837430/c540958e-e418-4e6b-a1d0-8147ee6f0216)

**Comment by susannasiebert** [comment]
Anchor weights for the specific allele in question (HLA-B*82:02) were not been calculated in our anchor weight table so this is expected and not a bug. Once #1030 is implemented, maybe this becomes more apparent?
