### ISSUE TITLE
Minor fix in readme

### ISSUE THREAD

**Issue by serge2016** [griffithlab/pVACtools#1066]
Hello!

If I understand correctly, here it is about specifically somatic VCFs from `strelka2`, but not about germline:
https://github.com/griffithlab/pVACtools/blob/9642052ba082641ed2d2fd43bbcbdbe12110d4ed/docs/pvacseq/input_file_prep/gt.rst?plain=1#L12
I suppose to add word `somatic` in this sentence.

**Comment by serge2016** [comment]
I am not sure that `--fasta` is necessary, if it is already installed: https://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html#fasta

https://github.com/griffithlab/pVACtools/blob/9642052ba082641ed2d2fd43bbcbdbe12110d4ed/docs/pvacseq/input_file_prep/vep.rst?plain=1#L47

I suppose it should also be mentioned

**Comment by susannasiebert** [comment]
> Hello!
> 
> If I understand correctly, here it is about specifically somatic VCFs from `strelka2`, but not about germline:
> 
> https://github.com/griffithlab/pVACtools/blob/9642052ba082641ed2d2fd43bbcbdbe12110d4ed/docs/pvacseq/input_file_prep/gt.rst?plain=1#L12
> 
> 
> I suppose to add word `somatic` in this sentence.

This has been updated. Closing this issue.
