### ISSUE TITLE
Outputting accounted-for germline variants

### ISSUE THREAD

**Issue by evelyn-schmidt** [griffithlab/pVACtools#1088]
https://github.com/griffithlab/pVACtools/blob/7c4b383c554a62352c74a92884bc5214267810b1/pvactools/tools/pvacseq/generate_protein_fasta.py#L45C1-L48C6

The `generate_protein_fasta.py` script uses the `phased-proximal-variants-vcf` to create correct predicted sequences within the fasta file. It would be helpful if the list of variants that affect the final sequences were output to a file that could be easily viewed and eventually incorporated into the final neoantigen review files. 

As of now, during the manual review process of the neoantigen candidates, reviewers have to check to make sure that germline variants are correctly accounted for in the sequences (and a majority of the time they are). For clarity that these germline variants are being reviewed, a list of the accounted-for germline variants would be helpful.

**Comment by susannasiebert** [comment]
This should be pretty straightforward. Such a file already gets created by the VCF conversion step so it just needs to be copied over from its temporary location.
