### ISSUE TITLE
Zero or few results after filtering

### ISSUE THREAD

**Issue by SirKuikka** [griffithlab/pVACtools#1104]
Hi,

I have been testing pVAC-seq with a few samples. For each sample, I have typically 150-400 somatic PASS mutations, of which ~40-75 are missense variants. I am using quite a new version of pVACtools (4.1.1).

I don't use MHC Class II for prediction, i have peptide lengths 8,9,10. These are basically the default settings. I am using the proximal variant approach.

In the filtered neoantigen file (<sample_name>.filtered.tsv), I have typically zero or only a few neoantigens. Is this an expected number given the specifications I have?

**Comment by susannasiebert** [comment]
In our experience, this is not unusual. The hard filters are pretty strict. We recommend that users use the aggregated report instead of the hard filtered one. This will report the best epitope for each variant with a Tier to reflect the main cause of why a candidate might be less suitable for inclusion in a potential vaccine. If you load this report into pVACview (together with the metrics.json file) you will able to investigate each variant more thoroughly and also easily manipulate thresholds to re-tier variants if you would like to test out less stringent criteria. We have put together a [tutorial](https://pvactools.readthedocs.io/en/latest/pvacview/pvacseq_module/pvacseq_vignette.html) on how to interpret your candidates in pVACview that might be useful.

**Comment by SirKuikka** [comment]
> In our experience, this is not unusual. The hard filters are pretty strict. We recommend that users use the aggregated report instead of the hard filtered one. This will report the best epitope for each variant with a Tier to reflect the main cause of why a candidate might be less suitable for inclusion in a potential vaccine. If you load this report into pVACview (together with the metrics.json file) you will able to investigate each variant more thoroughly and also easily manipulate thresholds to re-tier variants if you would like to test out less stringent criteria. We have put together a [tutorial](https://pvactools.readthedocs.io/en/latest/pvacview/pvacseq_module/pvacseq_vignette.html) on how to interpret your candidates in pVACview that might be useful.

Hi, 

Thanks. I have a small problem though because I need to use pvacview in a closed environment with limited access to internet. What are the internet addresses that pvacview needs to download the required files?

**Comment by SirKuikka** [comment]
> You can fully run pVACview locally without any internet access as long as you have access to a browser and are able to install R and all of the required dependencies. pVACview can be run in a way that serves the app to a local IP (`http://127.0.0.1:3333`). The demo data won't work but you will still be able to visualize your own pVACseq data. All of the files required for pVACview get generated during your pVACseq run, including the R files for pVACview itself. To start pVACview follow the [instructions](https://pvactools.readthedocs.io/en/latest/pvacview/prerequisites.html#installing-r-r-studio) to download R and install of the required R packages. To start pVACview from your pVACseq results simply follow the instructions for [Option 1 here](https://pvactools.readthedocs.io/en/latest/pvacview/prerequisites.html#launching-pvacview-r-shiny-app).

Hi,

Ok, I think I misundertood this part in the documentation. "Please note that you will need internet connection for pVACview, as it needs to download necessary datasets including both the demo data and anchor calculations." https://pvactools.readthedocs.io/en/latest/pvacview/prerequisites.html

**Comment by susannasiebert** [comment]
You are correct, my apologies. All of the files that pVACview needs to load from the internet are fetched from GitHub.

**Comment by susannasiebert** [comment]
I'm resolving this issue due to inactivity but please feel free to reopen if there are any additional questions.
