### ISSUE TITLE
Frameshift VEP plugin 

### ISSUE THREAD

**Issue by SirKuikka** [griffithlab/pVACtools#1107]
### Installation Type

Docker

### pVACtools Version / Docker Image

4.1.1

### Describe the bug

**Annotate VCF with VEP** (https://pvactools.readthedocs.io/en/latest/pvacseq/input_file_prep/proximal_vcf.html)

While annotating the variants, these errors occur 9 times. First, there's the " lt (<) " error two times then the "addition (+)" error once. Therefore, this happened at three genomic positions.

Use of uninitialized value in numeric lt (<) at /path/plugin_dir/vep_plugins/Frameshift.pm /line 129, <$fh> line 29779.
Use of uninitialized value in addition (+) at /path/plugin_dir/vep_plugins/Frameshift.pm line 129, <$fh> line 29779

### How to reproduce this bug

```Shell
${path_veo105}/vep --input_file $somatic_phased_vcf --output_file
Sannotated_somatic_phased_vcf --format vcf --vcf --symbol --terms SO --tsl --biotype --hgvs --fasta Sref_path --offline --dir_cache $cache_dir --dir_plugins $plugin_dir --plugin
Frameshift --plugin Wildtype --pick --compress_output bgzip
```

### Log output

Use of uninitialized value in numeric lt (<) at /path/plugin_dir/vep_plugins/Frameshift.pm /line 129, <$fh> line 29779.
Use of uninitialized value in addition (+) at /path/plugin_dir/vep_plugins/Frameshift.pm line 129, <$fh> line 29779

**Comment by susannasiebert** [comment]
Hm, that is odd. Are you seeing the same problem when annotating your main input VCF with the same plugin? Can you please post the Frameshift.pm file you are using?

**Comment by SirKuikka** [comment]
Hi,

No, I didn't encounter the same problem when I annotated the main input VCF.

This is the plugin https://raw.githubusercontent.com/griffithlab/pVACtools/v2.0.0/tools/pvacseq/VEP_plugins/Frameshift.pm

**Comment by susannasiebert** [comment]
Can you please attach your phased VCF to this issue so I can try and replicate this error on my end?

**Comment by SirKuikka** [comment]
Hi,

Unfortunately I can't give the whole file. If 29779 would correspond to line 29779 in the VCF file, I could test if the error happens with those few variants. I can perhaps give those.

**Comment by susannasiebert** [comment]
That's ok. Can you try commenting out line 129 in Frameshift.pm? The value of that variable is no longer used anyway so we should be ok to remove/comment out the code that is causing the error.

**Comment by susannasiebert** [comment]
The Frameshift.pm file has been updated in version 4.3.0. Please give it a try with that version and reopen this issue if you're still encountering this error.
