### ISSUE TITLE
NetChop SSLError

### ISSUE THREAD

**Issue by Tseng722** [griffithlab/pVACtools#1111]
### Installation Type

Standalone

### pVACtools Version / Docker Image

4.0.2

### Describe the bug

pvacbind run myfile.fasta tttt HLA-A*01:01 NetMHCpan NetMHC  myfile
-e1 9 
-k  
-t 48 
-b 100000 
--aggregate-inclusion-binding-threshold 100000  
--net-chop-method cterm  
--netmhc-stab   
--iedb-install-directory my_path

When I use the command above, I came up with error below:

Submitting remaining epitopes to NetChop
requests.exceptions.SSLError: HTTPSConnectionPool(host='services.healthtech.dtu.dk', port=443): Max retries exceeded with url: /cgi-bin/webface2.cgi (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))

How can I solve this problem, thanks

### How to reproduce this bug

```Shell
pvacbind run myfile.fasta tttt HLA-A*01:01 NetMHCpan NetMHC  myfile
-e1 9 
-k  
-t 48 
-b 100000 
--aggregate-inclusion-binding-threshold 100000  
--net-chop-method cterm  
--netmhc-stab   
--iedb-install-directory my_path
```

### Log output

Submitting remaining epitopes to NetChop
requests.exceptions.SSLError: HTTPSConnectionPool(host='services.healthtech.dtu.dk', port=443): Max retries exceeded with url: /cgi-bin/webface2.cgi (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)')))

**Comment by susannasiebert** [comment]
It looks like their website is was temporarily down due to their SSL certificate expiring. As far as I can tell, that has been resolved and you should be able to restart your run.
