### ISSUE TITLE
BigMHC prediction not working

### ISSUE THREAD

**Issue by giacuong171** [griffithlab/pVACtools#1119]
### Installation Type

Standalone

### pVACtools Version / Docker Image

4.2.1

### Python Version

3.10.8

### Operating System

Linux

### Describe the bug

The error occurs when pvactools run BigMHC prediction. It seems that there is no tool named bigmhc_predict, that is installed with pvactools. Should I install it separately from this [repo](https://github.com/KarchinLab/BigMHC) ? 

### How to reproduce this bug

```Shell
pvacseq run \
input.vcf.gz \
sample_name \
HLA-A*01:01,HLA-A*68:02,HLA-B*08:01,HLA-B*37:01,HLA-C*06:03,HLA-C*07:01 \
all \
output \
--normal-sample-name normal_sample_name \
-e1 8,9,10 \
-e2 15 \
```

### Log output

The full log file is : 
[pvactools.log](https://github.com/user-attachments/files/15984965/pvactools.log)

**Comment by susannasiebert** [comment]
BigMHC, as well as DeepImmuno, need to be installed separately. Please follow the instructions [in our documentation](https://pvactools.readthedocs.io/en/latest/install.html#installing-bigmhc) to install these predictors. Please note, that these instructions are different from the installation instructions provided by the BigMHC directly. pVACtools will only be able to use BigMHC if it is installed as instructed in our documentation.

**Comment by giacuong171** [comment]
Thank you for your quick response. I installed pvactools using pip and wonder if the Docker image of pvactools already includes BigMHC or DeepImmuno, or if I need to install them separately ?

**Comment by susannasiebert** [comment]
Our Docker image comes with both BigMHC and DeepImmuno pre-installed.
