### ISSUE TITLE
Output HGVS field in the final report

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVACtools#112]
The current annotation doesn’t adhere to HGVS guidelines. For clinicians it might be useful to have something they recognize.

**Comment by susannasiebert** [comment]
I have to check whether this is a default field in the VEP annotation. If it's not a default output, the code can look for that field and if it doesn't find it, use the ensembl api to convert it. I suppose we would then need to know the reference sequence so we need to decide whether we'd try to determine that from the VCF headers or require it as an input.

**Comment by susannasiebert** [comment]
`--hgvs` is an additional option for VEP. It's not a default. We should add it to our instructions on how to run VEP. This option adds fields for HGVSc and HGVSp. Which one is preferred? HGVSc?

**Comment by malachig** [comment]
It would be nice to have both. But if we have to pick one, then HGVSc

**Comment by susannasiebert** [comment]
This has been implemented in PR #116 (merged). It will become available in version 1.1.
