### ISSUE TITLE
KeyError: 'mhcflurry_processing_score'

### ISSUE THREAD

**Issue by hangfafa** [griffithlab/pVACtools#1123]
### Installation Type

Standalone

### pVACtools Version / Docker Image

4.2.1

### Python Version

3.8

### Describe the bug

Making binding predictions on Allele HLA-B*45:01 and Epitope Length 10 with Method MHCflurry - File /t9k/mnt/zxm/MHC_Class_I/tmp/HCC1395_TUMOR_DNA.MHCflurry.HLA-B*45:01.10.tsv_2401-2426
Making binding predictions on Allele HLA-B*45:01 and Epitope Length 10 with Method MHCflurry - File /t9k/mnt/zxm/MHC_Class_I/tmp/HCC1395_TUMOR_DNA.MHCflurry.HLA-B*45:01.10.tsv_2401-2426 - Completed
Parsing prediction file for Allele HLA-A*29:02 and Epitope Length 8 - Entries 1-200
Traceback (most recent call last):
  File "/t9k/mnt/.conda/envs/python38/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/t9k/mnt/.conda/envs/python38/lib/python3.8/site-packages/pvactools/tools/pvacseq/main.py", line 123, in main
    args[0].func.main(args[1])
  File "/t9k/mnt/.conda/envs/python38/lib/python3.8/site-packages/pvactools/tools/pvacseq/run.py", line 142, in main
    pipeline.execute()
  File "/t9k/mnt/.conda/envs/python38/lib/python3.8/site-packages/pvactools/lib/pipeline.py", line 452, in execute
    split_parsed_output_files = self.parse_outputs(chunks)
  File "/t9k/mnt/.conda/envs/python38/lib/python3.8/site-packages/pvactools/lib/pipeline.py", line 413, in parse_outputs
    parser.execute()
  File "/t9k/mnt/.conda/envs/python38/lib/python3.8/site-packages/pvactools/lib/output_parser.py", line 649, in execute
    iedb_results = self.process_input_iedb_file(tsv_entries)
  File "/t9k/mnt/.conda/envs/python38/lib/python3.8/site-packages/pvactools/lib/output_parser.py", line 529, in process_input_iedb_file
    iedb_results = self.parse_iedb_file(tsv_entries)
  File "/t9k/mnt/.conda/envs/python38/lib/python3.8/site-packages/pvactools/lib/output_parser.py", line 784, in parse_iedb_file
    scores         = self.get_scores(line, method)
  File "/t9k/mnt/.conda/envs/python38/lib/python3.8/site-packages/pvactools/lib/output_parser.py", line 156, in get_scores
    'mhcflurry_processing_score': float(line['mhcflurry_processing_score']),
KeyError: 'mhcflurry_processing_score'

### How to reproduce this bug

```Shell
pvacseq run /t9k/mnt/zxm/pvacseq_example_data/annotated.expression.vcf.gz HCC1395_TUMOR_DNA HLA-A*29:02,HLA-B*45:01,DRB1*04:05 all /t9k/mnt/zxm -e1 8,9,10 -e2 15 --normal-sample-name HCC1395_NORMAL_DNA
```

### Input files

example data

### Log output

IEDB API Output doesn't match input. Retrying.
2024-07-11 12:08:50.572683
Inputs:
{'sequence_text': '>1\nSLHEPLYLSSEYEAAPGSF\n>2\nSLHEPLYLSFEYEAAPGSF\n>3\nSGNETGILSEDALLRISIP\n>4\nSGNETGILSKDALLRISIP\n>5\nMKYSIVSRNCEHFVTQLR\n>6\nMKYSIVSRNCEIWQVPL\n>7\nRLLADPTGAFGKETDLLLD\n>8\nRLLADPTGALGKETDLLLD\n>9\nWTAARARPLVMTLNSLGFS\n>10\nWTAARARPLLMTLNSLGFS\n>11\nVLLNSLSVDPDAECKYGLY\n>12\nVLLNSLSVDLDAECKYGLY\n>13\nTLLNSLSVDPDAECKYGLY\n>14\nTLLNSLSVDLDAECKYGLY\n>15\nVVFVIFAICWAPLNCIGLA\n>16\nVVFVIFAICCAPLNCIGLA\n>17\nSWIDQRLHIQMYFFLRNFS\n>18\nSWIDQRLHIEMYFFLRNFS\n>19\nLSFIDLCYSSVITPKMLVN\n>20\nLSFIDLCYSFVITPKMLVN\n>21\nQQPLEDLDAQLRRTLSPEM\n>22\nQQPLEDLDAELRRTLSPEM\n>23\nLFRVRGAVSQTYPSGTCAY\n>24\nLFRVRGAVSETYPSGTCAY\n>25\nAVASSCSYLHEASLKRCCN\n>26\nAVASSCSYLNEASLKRCCN\n>27\nDYLNPRSGGISSRSGNTDK\n>28\nDYLNPRSGGMSSRSGNTDK\n>29\nPSFKKGLPQRKPRTSQTEA\n>30\nPSFKKGLPQHKPRTSQTEA\n>31\nVNDIYELDTSGLEDTMEIQ\n>32\nVNDIYELDTRGLEDTMEIQ\n>33\nSSSSSLPPPASSKHKTAER\n>34\nSSSSSLPPPGSSKHKTAER\n>35\nSAGPSSSSSLPPPASSKHK\n>36\nSAGPSSSSSLPPPGSSKHK\n>37\nIRQGLSHTADMQTREVLMK\n>38\nIRQGLSHTAHMQTREVLMK\n>39\nIRQGLSHTALMQTREVLMK\n>40\nIRQGLSHTAVMQTREVLMK\n>41\nPILLDKQFSEFTPDITPII\n>42\nPILLDKQFSKFTPDITPII\n>43\nNPVDVVRTRMMNQRVLRDG\n>44\nNPVDVVRTRIMNQRVLRDG\n>45\nPSHADFRDCRAALAEITEM\n>46\nPSHADFRDCLAALAEITEM\n>47\nIRHTAEYQEHWFYFEAKWQ\n>48\nIRHTAEYQENWFYFEAKWQ\n>49\nDRFSKPDSDRFVFLLCTRA\n>50\nDRFSKPDSDLFVFLLCTRA\n>51\nFKAGLLGLLEEMRDERLSR\n>52\nFKAGLLGLLAEMRDERLSR\n>53\nSPSPASQDGEEEKEGTLFP\n>54\nSPSPASQDGKEEKEGTLFP\n>55\nQVKIIVPNSTAGLIIGKGG\n>56\nQVKIIVPNSRAGLIIGKGG\n>57\nEDEEGTGSPKAEVQLCYLE\n>58\nEDEEGTGSPMAEVQLCYLE\n>59\nQWQTRLQKKMGKESETLNV\n>60\nQWQTRLQKKIGKESETLNV\n', 'method': 'pickpocket', 'allele': 'HLA-A*29:02', 'length': 10, 'user_tool': 'pVac-seq'}
Output:
allele	seq_num	start	end	length	peptide	ic50	percentile_rank

**Comment by susannasiebert** [comment]
@hangfafa thank you for reporting this error. I'm unable to reproduce this on my end. Which version of MHCflurry do you have installed? Did you run the `mhcflurry-downloads fetch` command before running pVACseq? Would you be able to share your output folder with us to further investigate this issue?

**Comment by hangfafa** [comment]
Hi, my version of mhcflurry is 2.0.6 and I have downloaded the relevant model files before running, the download link is https://github.com/openvax/mhcflurry/releases/download/pre-2.0/models_class1_ presentation.20200611.tar.bz2. I've put the tmp file generated during the run in the attachment
[tmp.zip](https://github.com/user-attachments/files/16190531/tmp.zip)

**Comment by susannasiebert** [comment]
Hm, that is strange. The tmp files do not contain prediction values for presentation and processing.

What does an example command from MHCflurry return (e.g. `mhcflurry-predict --alleles HLA-B4501 --peptides SIINFEKL SIINFEKD SIINFEKQ`).

Could you please also post the output from `mhcflurry-downloads info`?

**Comment by hangfafa** [comment]
Hi, thanks for your reply. mhcflurry works without any problem, the result is as shown in the picture, and I zip all the process files to you
![1721092978034](https://github.com/user-attachments/assets/0fa99433-57dc-40f9-8efe-af003d3fa7dd)
[test.zip](https://github.com/user-attachments/files/16242028/test.zip)

**Comment by hangfafa** [comment]
Hi, I solved the problem after reinstalling mhcflurry, thanks for the answer!
