### ISSUE TITLE
Adding Gene and Transcript Expression to VCF for pVACseq

### ISSUE THREAD

**Issue by biounix** [griffithlab/pVACtools#1159]
Hi,

If it’s possible to add both gene and transcript expression annotations to the input VCF file for `pVACseq` (`GX` and `TX` fields with `vcf-expression-annotator`), is it advisable to include both? Or is it better to include just one of them? If the latter, which one would you recommend prioritizing? My guess would be transcript expression since it seems more specific.

Additionally, if both gene and transcript expressions are included, how does `pVACseq` handle or prioritize this information during processing?

I couldn’t find documentation on this, so apologies if this has been answered elsewhere.

Thank you for your time and for developing such an invaluable toolset!

**Comment by chrisamiller** [comment]
pVACtools doesn't use the GX/TX information for anything in the binding predictions, etc. It is passed through to the aggregate report table, and is one of the factors used in determining the neoantigen's "Tier". It is also exposed in the pVACview interface, so that you can use that information when prioritizing peptides.

**Comment by biounix** [comment]
Great! Thanks for the answer.

**Comment by susannasiebert** [comment]
To add to @chrisamiller we do use both the TX and GX information in the coverage filter (both use the same `--expn-val` cutoff). This will impact the neoantigen candidates in the .filtered.tsv. For the aggregated report, gene expression is used for the tiering as part of the Allele Expr value, which is gene expression * tumor RNA VAF. You can find more information about the tiers in the aggregate report on [this page](https://pvactools.readthedocs.io/en/latest/pvacseq/output_files.html#the-pvacseq-aggregate-report-tiers) of our docs.

**Comment by biounix** [comment]
Thanks for your explanation, @susannasiebert!

Then, if expression values are present but not the tumor RNA VAF information (NA), I understand that the expression cireteria for tiering are not applied. Is that right?

**Comment by susannasiebert** [comment]
Correct, it would "auto-pass" that specific criteria and only consider the other criteria for each tier.

**Comment by biounix** [comment]
Thank you for clearing that up, much appreciated.
