### ISSUE TITLE
expression is NA. 

### ISSUE THREAD

**Issue by Leehyeonjin93** [griffithlab/pVACtools#137]
I used pvacseq run.
Input files are correct. 
fpkm(cufflinks result) is ok.
bam-readcount input is ok.
![image](https://user-images.githubusercontent.com/40356335/41532007-553641dc-7330-11e8-8ea2-2e07d9baec60.png)
but, result
gene_expression and transcript_expression are NA, all colums.
![image](https://user-images.githubusercontent.com/40356335/41532099-985b27a2-7330-11e8-9966-9ceb2402305a.png)
I don't know why this happen.

**Comment by susannasiebert** [comment]
Without seeing the actual content of the input files it is impossible for me to say what might be going wrong here. Can you attach the expression and readcount files as well as the VCF? If you do not want to distribute these input files publicly on GitHub you can also send them to us by emailing our help alias help@pvactools.org.

For what it's worth there might be some entries that do not have entries while others do, so just using head is not sufficient to assess whether the file contains parsed expression and readcount data. Try something like this to ensure that all entries are `NA`: `cut -f 16 E0771.tsv | sort | uniq -c`

**Comment by Leehyeonjin93** [comment]
![image](https://user-images.githubusercontent.com/40356335/41568354-2acc263a-73a0-11e8-8651-f1311736eca6.png)
I sent e-mail to help@pvactools.org. 
thanks

**Comment by susannasiebert** [comment]
The zip file you emails us did not contain any of the tracking files. Can you please send them as well? Thank you.

**Comment by Leehyeonjin93** [comment]
oh sorry, I sent tracking files to help@pvactools.org,  please check e-mail.

**Comment by susannasiebert** [comment]
The reason the files aren't being parsed in your case is because the `tracking_id` columns don't contain the expected type of identifier. pVACseq expects the tracking_id in the gene file to be an ensembl gene ID (not gene name) and for the isoforms file to be an ensembl transcript ID.

**Comment by Leehyeonjin93** [comment]
I will try to change tracking format.
thank you.
