### ISSUE TITLE
Advice on filtering

### ISSUE THREAD

**Issue by pjleo** [griffithlab/pVACtools#170]
Dear ALL,
I was looking for advice or  general recommendation on using the  
Cleavage, Stability and Mutation Position / Sub-peptide position columns in the pVacSeq output.

I'm not really sure how (or if) the  Mutation Position / Sub-peptide position should be used for filtering  There was a comment in the pVacSeq paper which I was not sure if it was referring to these columns?

> Second, epitope binding calls are evaluated
> only for those peptides that contain the mutant amino
> acid (localized peptides). This filter eliminates any WT
> peptides that may overlap between the two FASTA se-
> quences.

Can anyone clarify?
Also the Cleavage and Stability I understand their utility but is there recommended on ranges that are good/bad/ugly? 

Thanks in advance 
Paul

**Comment by susannasiebert** [comment]
The Mutant Position and Sub-peptide position are not used for any of the filter steps in pVACseq. The sentence you are quoting from the original paper reflects how pVACseq filters all MT epitopes that are identical to their corresponding WT epitope which means that they don't overlap the somatic mutation of interest.

In terms of how to interpret the additional columns maybe @chrisamiller @malachig and/or @jhundal  can give more information.

**Comment by pjleo** [comment]
Great thanks for the clarification and advice
