### ISSUE TITLE
Are IEDB binding prediction tools instalation available on mgibio/pvactools docker image?

### ISSUE THREAD

**Issue by vladimirkovacevic** [griffithlab/pVACtools#171]
If yes, on which location?
If no, what would be the best way to add it?

Thanks!

**Comment by pjleo** [comment]
It would be handy if the base included :

apt-get update
apt-get install tcsh
apt-get install python
apt-get install gawk

and having the python 2.7 modules to run  IEDB

Then the IEDB can just be installed outside the image could still use it my mounting that location. 
It was a bit confusing getting  the two version of python initially -the tests for mhc_ii tests would all fail etc unless I edited the phyon script...

**Comment by susannasiebert** [comment]
We added IEDB to our Docker image starting with version 1.1.0. Please note that the location moved from the `mgibio` to the `griffithlab` organization. You can pull that docker image using `griffithlab/pvactools:1.1.0`.
