### ISSUE TITLE
Document use of --transcript_version 

### ISSUE THREAD

**Issue by malachig** [griffithlab/pVACtools#173]
For compatibility with kallisto output and because it is a good best practice we should document some best practices for annotation of variants:
- Use the `--transcript_version` when running VEP
- Make sure your RNA-seq transcript expression values use the same Ensembl build and that transcript Ids have version numbers there as well.

**Comment by susannasiebert** [comment]
@malachig can you please have a look at the updated documentation here (https://pvactools.readthedocs.io/en/docs/pvacseq/input_file_prep/vep.html).

**Comment by susannasiebert** [comment]
@malachig and I chatted of-ticket about this and the documentation has been updated with his suggestions.
