### ISSUE TITLE
Update the filter sliders in the pVACviz visualization interface

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVACtools#180]
- Add a slider for `Gene Expression`
- Remove the existing slider for `Binding Threshold (WT)`
- Add slider for `Tumor RNA Depth` and `Tumor RNA VAF`

**Comment by jmcmichael** [comment]
Gene Expression and Tumor RNA Depth/VAF sliders are only shown when those columns contain values. We just haven't visualized data with those values present. I've just [created a PR](https://github.com/griffithlab/pVACtools/pull/200) that removes the Binding Threshold (WT) slider.

**Comment by jmcmichael** [comment]
Closing.
