### ISSUE TITLE
pvacseq suddenly stoped.

### ISSUE THREAD

**Issue by Leehyeonjin93** [griffithlab/pVACtools#186]
Hi,
I used mouse samples. but pvacseq stoped working.
I have two samples. two samples had a same problem. like that,
![pvacseq](https://user-images.githubusercontent.com/40356335/44779489-9365f700-abba-11e8-8783-cb60697e5105.png)
no more, working. I didn't see any error message.
so I checked memories and running programs.
![image](https://user-images.githubusercontent.com/40356335/44779704-24d56900-abbb-11e8-9742-576d1bcfa74a.png)
you can see.

this is my input log.
![image](https://user-images.githubusercontent.com/40356335/44779842-84cc0f80-abbb-11e8-8d5d-8a938849e631.png)

if you know what are problems, plz tell me. 
thank you

**Comment by susannasiebert** [comment]
This is the step where a subprocess to IEDB gets called. Can you try using the `ps` command to see if it's doing anything? E.g., something like `ps aux | grep predict_binding.py` and `ps aux | grep pvacseq`.

**Comment by Leehyeonjin93** [comment]
![image](https://user-images.githubusercontent.com/40356335/44822765-d619e480-ac37-11e8-9e75-dd74e0d04d13.png)
stoped again at same position..

**Comment by susannasiebert** [comment]
It's using CPU (25.9%) so it's still processing. NetMHCcons makes calls to a few different prediction algorithms and calculates a consensus binding affinity. This can be compute intensive so I'm not surprised that it's taking a while. If this particular chunk of data contains a lot of frameshift mutations the resulting downstream sequences will lead to a lot epitopes getting generated which will take a longer time to process. You can check the fasta file in that line (`MHC_Class_I/tmp/E0771_21.fa.split_601-8001`) to see what the data looks like.

**Comment by Leehyeonjin93** [comment]
Yes.  It looks like working.
but I didn't touch anything for 2days, but screen was same, no result.
when pvacseq run, top in terminal show python2.7 and MHCcons working.
but I can't see python2.7 and MHCcons in terminal.
Do you have any solutions?

**Comment by susannasiebert** [comment]
OK, well if you truly believe that it stopped working you can try one of two things:
- Kill the pvacseq process and restart it. If you use the same inputs and don't delete the output files, it should pick up from where it left off. Maybe it will succeed the second time.
- You can also try to start a new pvacseq run and change the `--fasta-size` to a smaller number. By default this is 200. You could try 100. This regulates how many fasta sequences get submitted to NetMHCcons at the same time. Maybe with a smaller set this process will succeed.

**Comment by Leehyeonjin93** [comment]
I changed --fasta-size option. and I checked frameshift regions that regions was very long.
I removed that region and pvacseq is working on.
thanks.

**Comment by susannasiebert** [comment]
Glad it's working now. I'll close this issue but feel free to reopen or to make a new issue should you run into anymore problems.
