### ISSUE TITLE
release pvactools docker image with iedb integrated

### ISSUE THREAD

**Issue by malachig** [griffithlab/pVACtools#192]
After discussions with IEDB it appears possible to release a docker image with IEDB included as long as we appropriately inform the downloader of IEDB license details.  I have provided text to be used below.  We should also link to the pvactools license in a preamble to this text that explains the software bundling that is being done here.

Places we should do this:
1.) In the dockerfile itself, as comments at the top.
2.) Place a simple text file in the docker image itself.
3.) On the DockerHub documentation page: https://hub.docker.com/r/griffithlab/pvactools/
4.) In the pvactools documentation section where we describe installation via the docker image.

IEDB statement and links to accompany the docker image:

------

License Agreements
By using the IEDB software, you are consenting to be bound by and become a "Licensee" for the use of IEDB tools and are consenting to the terms and conditions of the Non-Profit Open Software License ("Non-Profit OSL") version 3.0

Please read these two license agreements ([here:](http://tools.iedb.org/mhci/download/)) before proceeding. If you do not agree to all of the terms of these two agreements, you must not install or use the product. Companies (for-profit entities) interested in downloading the command-line versions of the IEDB tools or running the entire analysis resource locally, should contact us (license@iedb.org) for details on licensing options.

Citing the IEDB
All publications or presentations of data generated by use of the IEDB Resource Analysis tools should include citations to the relevant reference(s), found [here](http://tools.iedb.org/mhci/reference/).

**Comment by susannasiebert** [comment]
This has been completed.
