### ISSUE TITLE
Missing MHCflurry downloadable file

### ISSUE THREAD

**Issue by zhangbaifeng** [griffithlab/pVACtools#218]
* pvactools version:1.1.0
* Python version:2.7
* Operating System:linux

**Describe the bug**
Traceback (most recent call last):
  File "/opt/conda/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/tools/pvacseq/main.py", line 99, in main
    args[0].func.main(args[1])
  File "/opt/conda/lib/python3.6/site-packages/tools/pvacseq/run.py", line 107, in main
    if allele in MHCI.all_valid_allele_names():
  File "/opt/conda/lib/python3.6/site-packages/lib/prediction_class.py", line 136, in all_valid_allele_names
    valid_alleles.update(prediction_class().valid_allele_names())
  File "/opt/conda/lib/python3.6/site-packages/lib/prediction_class.py", line 192, in valid_allele_names
    predictor = Class1AffinityPredictor.load()
  File "/opt/conda/lib/python3.6/site-packages/mhcflurry/class1_affinity_predictor.py", line 393, in load
    models_dir = get_default_class1_models_dir()
  File "/opt/conda/lib/python3.6/site-packages/mhcflurry/downloads.py", line 85, in get_default_class1_models_dir
    return get_path("models_class1", "models", test_exists=test_exists)
  File "/opt/conda/lib/python3.6/site-packages/mhcflurry/downloads.py", line 140, in get_path
    % (quote(path), download_name))
RuntimeError: Missing MHCflurry downloadable file: /tmp/1.2.0/models_class1/models. To download this data, run:
	mhcflurry-downloads fetch models_class1
in a shell.
[job pvacseq.cwl] completed permanentFail
{
    "mhc_i_filtered_neoepitopes": null, 
    "mhc_ii_unfiltered_neoepitopes": null, 
    "mhc_ii_filtered_neoepitopes": null, 
    "mhc_i_unfiltered_neoepitopes": null
}
Final process status is permanentFail
**To Reproduce**
I start virtual environment, and then run:
cwltool pvacseq.cwl --alleles HLA-A*02:01 --prediction_algorithms NetMHCpan --sample_name B10 --input_file vep.annotated.vcf

pvacseq.cwl script is:
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: CommandLineTool
label: "run pVACseq"

baseCommand: [
    "pvacseq",
    "run"
]
requirements:
    - class: DockerRequirement
      dockerPull: griffithlab/pvactools:1.1.0
arguments:
    - position: 5
      valueFrom: $(runtime.outdir)
inputs:
    input_file:
        type: File
        inputBinding:
            position: 1
    sample_name:
        type: string
        inputBinding:
            position: 2
    alleles:
        type: string[]
        inputBinding:
            position: 3
            itemSeparator: ','
            separate: false
            prefix: ""
    prediction_algorithms:
        type: string[]
        inputBinding:
            position: 4
    epitope_lengths:
        type: int[]?
        inputBinding:
            prefix: "-e"
            itemSeparator: ','
            separate: false
    binding_threshold:
        type: int?
        inputBinding:
            prefix: "-b"
    iedb_retries:
        type: int?
        inputBinding:
            prefix: "-r"
    keep_tmp_files:
        type: boolean?
        inputBinding:
            prefix: "-k"
    peptide_sequence_length:
        type: int?
        inputBinding:
            prefix: "-l"
        default: 21
    net_chop_method:
        type:
            - "null"
            - type: enum
              symbols: ["cterm", "20s"]
        inputBinding:
            prefix: "--net-chop-method"
    netmhc_stab:
        type: boolean?
        inputBinding:
            prefix: "--netmhc-stab"
    top_result_per_mutation:
        type: boolean?
        inputBinding:
            prefix: "-t"
    top_score_metric:
        type:
            - "null"
            - type: enum
              symbols: ["lowest", "median"]
        inputBinding:
            prefix: "-m"
    net_chop_threshold:
        type: float?
        inputBinding:
            prefix: "--net-chop-threshold"
    additional_report_columns:
        type:
            - "null"
            - type: enum
              symbols: ["sample_name"]
        inputBinding:
            prefix: "-a"
    fasta_size:
        type: int?
        inputBinding:
            prefix: "-s"
    downstream_sequence_length:
        type: string?
        inputBinding:
            prefix: "-d"
    exclude_nas:
        type: boolean?
        inputBinding:
            prefix: "--exclude-NAs"
    minimum_fold_change:
        type: int?
        inputBinding:
            prefix: "-c"
    normal_cov:
        type: int?
        inputBinding:
            prefix: "--normal-cov"
    tdna_cov:
        type: int?
        inputBinding:
            prefix: "--tdna-cov"
    trna_cov:
        type: int?
        inputBinding:
            prefix: "--trna-cov"
    normal_vaf:
        type: int?
        inputBinding:
            prefix: "--normal-vaf"
    tdna_vaf:
        type: int?
        inputBinding:
            prefix: "--tdna-vaf"
    trna_vaf:
        type: int?
        inputBinding:
            prefix: "--trna-vaf"
    expn_val:
        type: int?
        inputBinding:
            prefix: "--expn-val"
outputs:
    mhc_i_unfiltered_neoepitopes:
        type: File?
        outputBinding:
            glob: "MHC_Class_I/*.combined.parsed.tsv"
    mhc_i_filtered_neoepitopes:
        type: File?
        outputBinding:
            glob: "MHC_Class_I/*.final.tsv"
    mhc_ii_unfiltered_neoepitopes:
        type: File?
        outputBinding:
            glob: "MHC_Class_II/*.combined.parsed.tsv"
    mhc_ii_filtered_neoepitopes:
        type: File?
        outputBinding:
            glob: "MHC_Class_II/*.final.tsv"

**Log Output**
```
NO
```

**Output File**
NO

**Expected behavior**
MHC_Class_I/*.final.tsv

**Comment by susannasiebert** [comment]
The MHCflurry files get downloaded by this line of the Dockerfile: https://github.com/griffithlab/docker-pvactools/blob/1.1.0/Dockerfile#L50. They are installed to `/tmp/1.2.0/models_class1/` inside of the Docker container. My best guess is that something about the way things are set up on your machine changes things so that this directory is no longer in your path.

We also recently released a new pVACtools version (1.1.1) so you'll want to make sure to download the latest CWL.

**Comment by susannasiebert** [comment]
Digging into this some more, I believe the problem is that cwtools mounts a temporary directory into /tmp, basically overwriting what is already there. We can probably get around this by downloading the MHCflurry files into a different directory.

**Comment by zhangbaifeng** [comment]
Thanks, Susanna.

Susanna Kiwala <notifications@github.com> 于2018年10月29日周一 下午9:28写道：

**Comment by susannasiebert** [comment]
The 1.1.1 version of the pvactools docker container has been rebuilt with the change to the MHCflurry data directory. Please download the latest version of the CWL to use this update.

As a side note, during testing I discovered that integer inputs to the CWL are not compatible with  cwltool's command line passing of parameters. This is a known bug with cwltool (see https://github.com/common-workflow-language/cwltool/issues/342). For your run, you will need to specify an epitope length (because you're using a class I algorithm), which is an integer input to the CWL. To get around this issue, you will need to use a yml file for your arguments, instead of the command line passing you're currently using.

**Comment by susannasiebert** [comment]
This worked for me:
```
    epitope_lengths:
        type: int[]?
        inputBinding:
            prefix: "-e"
            itemSeparator: ','
            separate: false
        default:
          - 9
          - 10
          - 11
```

**Comment by zhangbaifeng** [comment]
I deleted "separate: false", because it will cause "-e9,10,11". But I also
get same error as above.


[job pvacseq.cwl] /tmp/tmpk3v9cckz$ docker \

    run \

    -i \

    --volume=/tmp/tmpk3v9cckz:/dkVQyw:rw \

    --volume=/tmp/tmpalm8qo54:/tmp:rw \


--volume=/share/Data01/zhangbaifeng/BLC/Neoantigen/pvac/test:/var/lib/cwl/stg8ee6fffd-c25c-47b3-ac9b-ebe53ea4648f/test:ro
\

    --workdir=/dkVQyw \

    --read-only=true \

    --user=1015:1016 \

    --rm \

    --env=TMPDIR=/tmp \

    --env=HOME=/dkVQyw \

    griffithlab/pvactools:1.1.1 \

    pvacseq \

    run \

    -e \

    9,10,11 \

    -l \

    21 \

    /var/lib/cwl/stg8ee6fffd-c25c-47b3-ac9b-ebe53ea4648f/test \

    B10 \

    HLA-A*02:01 \

    NetMHCpan \

    /dkVQyw \

    --iedb-install-directory \

    /opt/iedb \

    --pass-only

[job pvacseq.cwl] completed permanentFail

{

    "combined_all_epitopes": null,

    "combined_filtered_epitopes": null,

    "combined_ranked_epitopes": null,

    "mhc_i_all_epitopes": null,

    "mhc_i_filtered_epitopes": null,

    "mhc_i_ranked_epitopes": null,

    "mhc_ii_all_epitopes": null,

    "mhc_ii_filtered_epitopes": null,

    "mhc_ii_ranked_epitopes": null

}

Final process status is permanentFail

Susanna Kiwala <notifications@github.com> 于2018年10月30日周二 下午10:31写道：

**Comment by susannasiebert** [comment]
I attached the cwl file that worked on my machine. With this cwl I was able to get a succeeded run. Unfortunately, I'm unable to provide additional assistance beyond that since I can't reproduce your problem.

[pvacseq.cwl.zip](https://github.com/griffithlab/pVACtools/files/2530187/pvacseq.cwl.zip)

**Comment by zhangbaifeng** [comment]
OK，thanks very much，susanna.

Best,
Baifeng
