### ISSUE TITLE
Rounding issues with pvacseq output

### ISSUE THREAD

**Issue by huimingx** [griffithlab/pVACtools#230]
* pvactools version: 1.1.4
* Python version: -
* Operating System: Ubuntu 

**Describe the bug**
I've been analyzing output files produced by running different filter commands on the same set of TCGA samples. When trying to calculate the overlapping entries from files produced by different filters, I notice that there are entries that are nearly identical with the exception of certain numerical entries that are off by 1 decimal (e.g. ‘0.4271844660194174’ vs ‘0.4271844660194175’) or the significant numbers that are being reported are different (e.g.  ‘28.226825861673237’ vs ‘28.22682586167324’ ). Perhaps for consistency, we should consider rounding the numbers to a specific number of significant figures in a consistent way. 

**To Reproduce**
filter1a: pvacseq binding_filter -b 500 ".$out_files_dir."/".$pid.".all_epitopes.tsv ".$out_files_dir."/".$pid.".filter1a_binding500nm.tsv
filter1b: pvacseq binding_filter -a ".$out_files_dir."/".$pid.".all_epitopes.tsv ".$out_files_dir."/".$pid.".filter1b_allelespecificbinding.tsv

**Log Output**

**Output File**
Path to output files: /gscmnt/gc2596/griffith/h.xia/pvactools_manuscript/pvacseq_demonstration/TCGA_300_filter1a_epitopes_combined.txt
/gscmnt/gc2596/griffith/h.xia/pvactools_manuscript/pvacseq_demonstration/TCGA_300_filter1b_epitopes_combined.txt

**Expected behavior**
Reduced number of significant figures and consistent method of rounding.

**Comment by susannasiebert** [comment]
@jhundal how many digits of precision do we want to round to? 3?
