### ISSUE TITLE
How is Genotype information used

### ISSUE THREAD

**Issue by Rashesh7** [griffithlab/pVACtools#231]
Hi, 

So it seems that pVACseq needs the GT field in the FORMAT and for each sample in the VCF. But I was wondering how that genotype value is being used

So in case if my VCF does not have the GT tag and I manually add it, can I just add 0/1 for all variants for the tumor and 0/0 for the normal sample?

Your input is highly appreciated. 
Thank you.

**Comment by susannasiebert** [comment]
We use the GT field to identified the variants that are actually called in your sample as well as the alternate alleles that are actually involved in the mutation of the specific sample. So in your case you can add the GT tag as you suggested as long as there aren't any variants with multiple alts that you would also want to process.

**Comment by Rashesh7** [comment]
Hello @susannasiebert ,
Thank you so much for the quick reply. 
So then it does not matter if the somatic mutation is a Het or a homozygous mutation. It's just to check the presence of the variant in the sample and which allele?

**Comment by susannasiebert** [comment]
Correct.

**Comment by Rashesh7** [comment]
Great! thank you
