### ISSUE TITLE
Update citation

### ISSUE THREAD

**Issue by jhundal** [griffithlab/pVACtools#232]
1) Update citation section of pVACtools. Add: https://doi.org/10.1038/s41588-018-0283-9
2) Include hyperlink of citation to the "Table of Contents" panel on the main page

**Comment by susannasiebert** [comment]
Do we want both papers to appear in the citation section? If so, which one should be first?

(I can add that tomorrow after I land and get to my hotel)

**Comment by jhundal** [comment]
Yes. Proximal paper (2018) first followed by the pVAC-seq paper (2016) unless @malachig prefers it the other way around.

**Comment by malachig** [comment]
This sounds good

**Comment by susannasiebert** [comment]
I added the citation in various place. I also tried to add the requested link into the table of contents but it doesn't seem to work. I added a "label" on line 139 of https://github.com/griffithlab/pVACtools/edit/master/docs/index.rst and added a reference to it on line 40 of the same file which according to the docs (https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html) should create a link in the table of contents but no such luck. @ahwagner, you've some experience with restructered text. Any idea what I might be doing wrong? I also tried adding the reference to the toctree as 
```
:ref:`citation`
```
and
```
Citation <citation>
```
 and that didn't work either. Worst case scenario we'd need to make the citation section it's own page.

**Comment by jhundal** [comment]
Also, add this pre-print in the citation section:

_pVACtools: a computational toolkit to select and visualize cancer neoantigens
Jasreet Hundal, Susanna Kiwala, Joshua McMichael, Christopher A Miller, Alexander T Wollam, Huiming Xia, Connor J Liu, Sidi Zhao, Yang-Yang Feng, Aaron P Graubert, Amber Z Wollam, Jonas Neichin, Megan Neveau, Jason Walker, William E Gillanders, Elaine R Mardis, Obi L Griffith, Malachi Griffith
bioRxiv 501817; doi: https://doi.org/10.1101/501817_

**Comment by susannasiebert** [comment]
I added the preprint to the various citation sections. I also added a standalone citation page so that the automated creation of the sidebar tree of contents will include a citation link. It will take a user to that standalone page instead of the citation section on the main page but this is the only way I was able to get it to work.
