### ISSUE TITLE
Better support for peptide lengths for class II prediction

### ISSUE THREAD

**Issue by malachig** [griffithlab/pVACtools#235]
Currently class II prediction appears limited to peptides of length 15 only.  This does not reflect the biology of MHC class II binding or even the capabilities of the class II predictors.  It appears that IEDB simply made the choice to only support length of 15?

https://help.iedb.org/hc/en-us/articles/114094152411-Why-does-the-MHC-class-II-binding-prediction-operate-only-on-15-mers-

We should confirm that the IEDB interface really does still have this limitation.  

If it does, and given that is has already been two years since they stated it would be fixed, we may want to consider a work around?

**Comment by susannasiebert** [comment]
MHCnuggets support class II so we could at a minimum implement it for that algorithm.

**Comment by susannasiebert** [comment]
Some observations as I start digging into this:
- We currently hard-code the peptide-sequence-length to 31 for class II algorithms. Class I gets set to what the user specifies in `--peptide-sequence-length`. With this change we'll probably want the user to be able to set the peptide sequence length to something that makes sense with is class ii epitope lengths. The same value won't be appropriate for both class I and class II. Do we need to implement a `--class-i-peptide-sequence-length` and `--class-ii-peptide-sequence-length`?
- A user would probably want to be able to set the epitope lengths for class I and class II independently so we'd need some way to differentiate between the class I and class II epitope lengths. This could be two parameters `--class-i-eptiope-length` and `--class-ii-epitope-length`.

These two proposed changes would break backwards compatibility which would necessitate a new major version release (2.0.0).

**Comment by susannasiebert** [comment]
Now that IEDB supports class II prediction lengths, we can easily incorporate this feature.

**Comment by malachig** [comment]
IEDB now supports lengths 11-30 for class II. 

Right now we can't support choice of these lengths using just the `-e` option we have now for class I.

Options for supporting this:
a) change pvactools so that you can only run class I OR class II at any one time and then the `-e` option is used to specify appropriate lengths

b) use two options. e.g. `-class_i_length` and `-class_ii_length`. We might also then need to change the `peptide-sequence-length`, possibly by also having two options for this as we do for epitope length . 

Leaning towards going with (b).  We would have two optional parameters for class I and II lengths.  Default for class I: `8,9,10,11` and default class II: `15`.

**Comment by MatDal** [comment]
Have you planned when this feature will be added?
Thanks

**Comment by susannasiebert** [comment]
It will be part of the next major feature release (2.0), same as the percentile feature.

**Comment by MatDal** [comment]
Thanks!
