### ISSUE TITLE
pVACseq fails: Error posting request to IEDB

### ISSUE THREAD

**Issue by genomicsresearcher** [griffithlab/pVACtools#238]
* pvactools version: 1.1.5
* Python version: 3.5
* Operating System: Linux

**Describe the bug**
pVACtools fails with error: Error posting request to IEDB. I am running pVACtools for a set of 500 VCF files, each from a single data source. Some of my runs are failing with this error. An example is shown below. Thanks in advance for your help!

**To Reproduce**
```
pvacseq run \
path/to/TCGA-G9-6362-11A-01D-1786-08.vcf \
TCGA-G9-6362-11A-01D-1786-08 \
HLA-A*01:01,HLA-A*11:01,HLA-B*15:01,HLA-B*37:01,HLA-C*01:02,HLA-C*06:02 \
MHCflurry MHCnuggetsI MHCnuggetsII NNalign NetMHC PickPocket SMM SMMPMBEC SMMalign \
out/path/to/TCGA-G9-6362-11A-01D-1786-08 \
-e 8,9,10,11
```

Note, the input file used is of identical format to the one attached in the same section as this in https://github.com/griffithlab/pVACtools/issues/237

**Log Output**
[slurm-30822449.out.txt](https://github.com/griffithlab/pVACtools/files/2717439/slurm-30822449.out.txt)

**Output File**
N/A

**Expected behavior**
To produce output as stipulated by program.

**Comment by malachig** [comment]
I you use the pvactools docker image, you will have everything you need including a local copy of IEDB installed.  

https://hub.docker.com/r/griffithlab/pvactools/

**Comment by genomicsresearcher** [comment]
Thanks a lot @susannasiebert and @malachig! I have filed a ticket with IEDB and am working with them to sort this out. As for a docket image, I agree this is the best way to go, but unfortunately my computing platform does not support it.

**Comment by genomicsresearcher** [comment]
After several back and forths with IEDB, here is the conclusion of Jyan, from the IEDB support team:

```
None of these IPs are blocked. And most importantly, you got the prediction results from our API server. So this shouldn't be an IP issue.

I'm not familiar with pVACseq. But I think it's not likely because of the DDOS Prevention (sending too many requests in a very short period of time). So one possible reason is the size of the datasets you used. For those jobs which the web server need to take a long time to finish, the web server will ask user a email address, and send the result to it after the predictions finishing instead of returning the result directly. Maybe pVACseq couldn't deal with this.

So if you were using large datasets, I would like to suggest that you split the prediction into small ones and give it a try.
```

Has use of large datasets been an issue in the past? Do you think this may remedy the problem or do you think there is a different issue at play here?

Thanks a lot.

**Comment by susannasiebert** [comment]
Yes, this is a known issue which is why we recommend to use the standalone IEDB installation if you are running large files or a large number of files at the same time. At a minimum, you'll want to avoid submitting all of your 500 pVACseq jobs at the same time.

**Comment by alongalor** [comment]
A quick follow-up question: are there specific epitope prediction algorithms that do not send requests to IEDB? I would assume using those algorithms shouldn't cause any issues.

**Comment by susannasiebert** [comment]
Yes, MHCnuggets (I and II) and MHCflurry are run outside of IEDB.

**Comment by alongalor** [comment]
Amazing. Thank you, Susanna!
