### ISSUE TITLE
Docs pages contain errors/warnings

### ISSUE THREAD

**Issue by malachig** [griffithlab/pVACtools#239]
I am seeing the following in the docs page that make the documentation a bit harder to read:

https://pvactools.readthedocs.io/en/latest/pvacseq/additional_commands.html

```
Using TensorFlow backend.
/home/docs/checkouts/readthedocs.org/user_builds/pvactools/conda/latest/lib/python3.5/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (3.0.4) doesn't match a supported version!
```

**Comment by susannasiebert** [comment]
This has been fixed in the latest update to the documentation.

**Comment by susannasiebert** [comment]
This has been fixed (again).
