### ISSUE TITLE
Add coverage filter for pVACfuse

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVACtools#25]
1. Integrate-NEO is outputting a coverage already; this needs to be parsed into the tsv
2. The pvacfuse coverage_filter needs to filter on the above, new column. We need to decide what the default threshold should be.

**Comment by susannasiebert** [comment]
Based on information from @gschang STARfusion outputs this information. We need to determine how it can be provided to pVACfuse and processed.

@gschang can you please attach an example output file from STARfusion to this ticket to show what that readcount output looks like?

**Comment by gschang** [comment]
As Susanna requested above, the following final STAR-Fusion output file has two columns for the read count number associated with each transcript fusion--(1) **JunctionReadCount** and (2) **SpanningFragCount**.

```
./output_dir/**star-fusion.fusion_predictions.abridged.tsv**
```

The JunctionReadCount has all sequencing reads that are aligned to the site of the fusion junction (predicted), resulting in split alignments. This count number may more precisely support the fusion event. However, some sequencing platforms may not always have such supporting reads--for example targeted cDNA exome sequencing. The SpanningFrags count looks like available only if in the paired-end sequencing mode.

More information is at https://github.com/STAR-Fusion/STAR-Fusion/wiki#Outputs.


Below is an example format of star-fusion.fusion_predictions.abridged.tsv. These two columns are also found in ./output_dir/star-fusion.fusion_predictions.tsv and ./output_dir/star-fusion.fusion_predictions.abridged.coding_effect.tsv (available if with --examine_coding_effect).

```
#FusionName	JunctionReadCount	SpanningFragCount	SpliceType	LeftGene	LeftBreakpoint	RightGene	RightBreakpoint	LargeAnchorSupport	FFPM	LeftBreakDinuc	LeftBreakEntropy	RightBreakDinuc	RightBreakEntropy	annots
PSMG2--SPIRE1	133	3	ONLY_REF_SPLICE	PSMG2^ENSG00000128789	chr18:12706721:+	SPIRE1^ENSG00000134278	chr18:12546904:-	YES_LDAS	0.6096	GT	1.8892	AG	1.8295	["INTRACHROMOSOMAL[chr18:0.00Mb]","NEIGHBORS_OVERLAP:+:-:[91]"]
SAA4--SAA1	90	0	ONLY_REF_SPLICE	SAA4^ENSG00000148965	chr11:18232395:-	SAA1^ENSG00000173432	chr11:18269717:+	YES_LDAS	0.4034	GT	1.9329	AG	1.7819	["INTRACHROMOSOMAL[chr11:0.03Mb]","LOCAL_INVERSION:-:+:[29281]"]
AC108010.1--PDE1C	83	6	ONLY_REF_SPLICE	AC108010.1^ENSG00000242588	chr7:128592017:+	PDE1C^ENSG00000154678	chr7:32209539:-	YES_LDAS	0.399	GT	1.5546	AG	1.9329	["INTRACHROMOSOMAL[chr7:96.28Mb]"]
CREB3L2--DGKI	66	1	ONLY_REF_SPLICE	CREB3L2^ENSG00000182158	chr7:137928150:-	DGKI^ENSG00000157680	chr7:137690002:-	NO_LDAS	0.3004	GT	1.9656	AG	1.9086	["INTRACHROMOSOMAL[chr7:0.03Mb]","NEIGHBORS[27887]"]
PDE1C--CCDC136	27	0	INCL_NON_REF_SPLICE	PDE1C^ENSG00000154678	chr7:31789845:-	CCDC136^ENSG00000128596	chr7:128805761:+	YES_LDAS	0.121	GT	1.2729	AG	1.7819	["INTRACHROMOSOMAL[chr7:96.49Mb]"]
PDCD10--SLITRK3	23	1	ONLY_REF_SPLICE	PDCD10^ENSG00000114209	chr3:167695596:-	SLITRK3^ENSG00000121871	chr3:165190851:-	YES_LDAS	0.1076	GT	1.8892	AG	1.7819	["INTRACHROMOSOMAL[chr3:2.49Mb]"]
```

**Comment by susannasiebert** [comment]
If we switch to Arriba the following metrics are available:
> `split_reads1` and `split_reads2` : The number of supporting split fragments with an anchor in gene1 or gene2, respectively, is given in these columns. The gene to which the longer segment of the split read aligns is defined as the anchor.
>
> `discordant_mates` : This column contains the number of pairs (fragments) of discordant mates (a.k.a. spanning reads or bridge reads) supporting the fusion.
>
> `coverage1` and `coverage2` : These two columns show the coverage near breakpoint1 and breakpoint2, respectively. The coverage is calculated as the number of fragments near the breakpoint on the side of the breakpoint that is retained in the fusion transcript. Note that the coverage calculation counts all fragments (even duplicates), whereas the columns split_reads1, split_reads2, and discordant_mates only count non-discarded reads. Fragments discarded due to being duplicates or other types of artifacts can be found in the column filters.

**Comment by susannasiebert** [comment]
A couple of issues/questions that need answering before we can move forward with this issue:
- STAR-Fusion outputs one JunctionReadCount while Arriba outputs separate split read counts for each gene. How should this data be normalized in the pVACfuse output files
- How do we want to handle thresholds for filtering? Should there be two separate thresholds for encompassing and spanning reads? What do we want the threshold default(s) to be?

**Comment by malachig** [comment]
My initial instinct is that we use the following approach for counts to simplify things:
StarFusion: `ReadSupport` = `JunctionReadCount` + `SpanningFragCount`
Arriba: `ReadSuport` = `split_reads1` + `split_reads2` + `discordant_mates`

Based on my reading of the documentation above, I think this puts the two tools on an even footing.

I would then just have the threshold operate on this `ReadSupport` value.
