### ISSUE TITLE
pvacViz: input folders not installed correctly (pip and github installation)

### ISSUE THREAD

**Issue by EdGreen21** [griffithlab/pVACtools#250]
* pvactools version: 1.2.0
* Python version: 3.5.6 (inside conda environment)
* Operating System: Ubuntu 18.04 (inside Virtualbox container)

FAO: @jmcmichael  

**Describe the bug**
Installed pVACtools 1.2.0 into conda environments using both the pip install and (separately) setup.py, adding the missing dependencies by hand (see issue #249 ). On running pvacapi and then pvacviz was able to access localhost:4200, but navigating to the 'Start' page selecting 'Input vcf' throws and error (see log output below). 

On inspection no` pVAC-Seq/input `etc folders have been created during the installation, and manual addition of `~/pVAC-Seq/input/example.vcf ` does not solve the problem. Potentially this is related to recent changes in folder structures (dropbox renaming etc)

**To Reproduce**
(terminal1) `pvacapi`
(terminal2) `pvacviz`

**Log Output**

```
pvacviz
Fri Jan 18 21:06:35 2019 Starting pVACviz client webserver
Fri Jan 18 21:06:35 2019 pVACviz server started at http://localhost:4200
Fri Jan 18 21:06:35 2019 Opening pVACviz client at http://localhost:4200 in default browser.
127.0.0.1 - - [18/Jan/2019 21:06:36] "GET /assets/pvacviz-favicon.png HTTP/1.1" 200 -

Exception happened during processing of request from ('127.0.0.1', 36142)
Traceback (most recent call last):
  File "/home/ed/anaconda3/envs/python3.5/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/ed/anaconda3/envs/python3.5/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/home/ed/anaconda3/envs/python3.5/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/ed/anaconda3/envs/python3.5/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/ed/anaconda3/envs/python3.5/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/home/ed/anaconda3/envs/python3.5/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/home/ed/anaconda3/envs/python3.5/lib/python3.5/site-packages/pvactools-1.2.0-py3.5.egg/utils/pvacviz/app.py", line 31, in do_GET
    with open(INDEXFILE, 'rb') as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'index.html'
```

**Expected behavior**
On installation: creation of `~/pVAC-Seq `as described in readme
On run: suggest: 'navigate to folder' option

**Comment by susannasiebert** [comment]
@EdGreen21 Would you mind attaching a screenshot of your pVACviz form on the Start page? I want to make sure you have the latest version of the pVACviz code.

**Comment by EdGreen21** [comment]
Afraid this'll have to wait till Monday as I've left the lab, but will start afresh using the hotfix updates you've just pushed in #251.

**Comment by EdGreen21** [comment]
Hi @susannasiebert, I think this might be because the pip version (Jan 17) and the hotfix (Jan 18) aren't running off quite the same code. To recreate the pip error I ran the following:


Spin up Ubuntu 18.04 LTS fresh virtual machine
__________
**Terminal 1**
sudo apt-get update
sudo apt install git
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh  #python 3.7
bash Miniconda3-latest-Linux-x86_64.sh
source ~/.bashrc
conda create -n pVACtools python=3.5
conda activate pVACtools
pip install pvactools
pvactools –v #confirm version 1.2.0
pvacapi
ImportError: No module named 'flask_cors'  

*#dependencies not resolved correctly – the github fix was commited Jan18, but the pip version updaded Jan17. Add manually:*

pip install flask-cors watchdog swagger-spec-validator tornado bokeh py-postgresql

pvacapi
Initializing app configuration
Visualization server started on PID 4081
Unable to connect to your Postgres server.                         The pVAC-Seq API requires a running local Postgres server
Cleaning up visualization server
2019-01-21 10:49:02,208 Starting Bokeh server version 1.0.4 (running on Tornado 5.1.1)
2019-01-21 10:49:02,211 Bokeh app running at: http://localhost:5006/visualizations
2019-01-21 10:49:02,211 Starting Bokeh server with process id: 4082
*running correctly*
__________
**Terminal 2**
conda activate pVACtools
pvacviz
Mon Jan 21 10:50:50 2019 Starting pVACviz client webserver
Mon Jan 21 10:50:50 2019 pVACviz server started at http://localhost:4200
Mon Jan 21 10:50:50 2019 Opening pVACviz client at http://localhost:4200 in default browser.
*running correctly*
__________
**Terminal 3**
cd ~
ls     
Desktop    examples.desktop                   Music     shared-drives
Documents  miniconda3                         Pictures  Templates
Downloads  Miniconda3-latest-Linux-x86_64.sh  Public    Videos

*#no ~/pVAC-Seq folder, try adding dummy files manually:*
mkdir pVAC-Seq
mkdir pVAC-Seq/input
pVAC-Seq/input/dummy.VCF


__________
**Firefox**
Input page > reload inputs
No dummy.VCF in drop down
![pvacviz input](https://user-images.githubusercontent.com/18687751/51467412-c9c03080-1d6c-11e9-8086-707132ada2ee.png)

I tried to find the input folder using whereis as I thought it might end up inside the miniconda env folder, but no luck.

Attached is the in pVACviz input form.

Will try again using direct installation using setup.py from the hotfix_setup branch

**Comment by EdGreen21** [comment]
Now from the github repository with setup.py it seems that index.html is not installed:

**terminal 1**
git clone https://github.com/griffithlab/pVACtools.git
conda create -n py3.5 python=3.5
source activate py3.5
python –V 
*3.5.1*

cd pVACtools/	
git checkout remotes/origin/hotfix_setup 
*HEAD is now at ada3840 Add documentation for installing Postgres*

python setup.py build
python setup.py install
pvacapi
*2019-01-21 11:24:23,842 Starting Bokeh server version 0.13.0 (running on Tornado 5.0.2)
2019-01-21 11:24:23,846 Bokeh app running at: http://localhost:5006/visualizations
2019-01-21 11:24:23,846 Starting Bokeh server with process id: 1774*

*code running correctly*

**2nd terminal window**
source activate py3.5
pvacviz

<pre>Mon Jan 21 11:24:44 2019 Starting pVACviz client webserver
Mon Jan 21 11:24:44 2019 pVACviz server started at http://localhost:4200
Mon Jan 21 11:24:44 2019 Opening pVACviz client at http://localhost:4200 in default browser.
127.0.0.1 - - [21/Jan/2019 11:24:46] &quot;GET / HTTP/1.1&quot; 200 -
127.0.0.1 - - [21/Jan/2019 11:24:46] &quot;GET /favicon.ico HTTP/1.1&quot; 200 -
----------------------------------------
Exception happened during processing of request from (&apos;127.0.0.1&apos;, 60924)
Traceback (most recent call last):
  File &quot;/home/ed/miniconda3/envs/py3.5/lib/python3.5/socketserver.py&quot;, line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File &quot;/home/ed/miniconda3/envs/py3.5/lib/python3.5/socketserver.py&quot;, line 341, in process_request
    self.finish_request(request, client_address)
  File &quot;/home/ed/miniconda3/envs/py3.5/lib/python3.5/socketserver.py&quot;, line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File &quot;/home/ed/miniconda3/envs/py3.5/lib/python3.5/socketserver.py&quot;, line 681, in __init__
    self.handle()
  File &quot;/home/ed/miniconda3/envs/py3.5/lib/python3.5/http/server.py&quot;, line 422, in handle
    self.handle_one_request()
  File &quot;/home/ed/miniconda3/envs/py3.5/lib/python3.5/http/server.py&quot;, line 410, in handle_one_request
    method()
  File &quot;/home/ed/miniconda3/envs/py3.5/lib/python3.5/site-packages/pvactools-1.2.0-py3.5.egg/utils/pvacviz/app.py&quot;, line 31, in do_GET
    with open(INDEXFILE, &apos;rb&apos;) as fin:
FileNotFoundError: [Errno 2] No such file or directory: &apos;index.html&apos;
</pre>

**Comment by susannasiebert** [comment]
When you manually created the `dummy.VCF` file, did that file have any content? It won't be displayed in the dropdown unless it has a size.

Regarding the `index.html` issues, what are the contents of the `/home/ed/miniconda3/envs/py3.5/lib/python3.5/site-packages/pvactools-1.2.0-py3.5.egg/utils/pvacviz/client` directory?

**Comment by EdGreen21** [comment]
On my VM created using `pip install git+https://github.com/griffithlab/pVACtools.git@hotfix_setup` I can confirm `/home/ed/miniconda3/envs/py3.5/lib/python3.5/site-packages/pvactools-1.2.0-py3.5.egg/utils/pvacviz/client` is empty.

On the other VM that can run pvacviz with index.html, the `dummy.vcf` I created was indeed empty, but I re-ran the rest copying `pVACtools/tests/test_data/pvacseq/input.vcf` to the `~/pVAC-Seq/input/ folder`, clicking `reload inputs` on the pvacviz browser and again nothing was displayed, suggesting there's still a bug somewhere regarding file directories (after all I had to manually make these folders).

**Comment by susannasiebert** [comment]
There are multiple issues going on here and I'm trying to focus at one at a time. Is there any output in the `pvacapi` window?

**Comment by susannasiebert** [comment]
Can you also post the contents of the `~/.pvacseq` folder? Does it contain a `input.json` file? If so, what are its contents?

**Comment by EdGreen21** [comment]
In the pvacapi window there is the following output:

```
ed@ed-VirtualBox:~$ source activate pvactools
(pvactools) ed@ed-VirtualBox:~$ pvacapi
Initializing app configuration
Visualization server started on PID 1594
Unable to connect to your Postgres server.                         The pVAC-Seq API requires a running local Postgres server
Cleaning up visualization server
2019-01-23 03:53:51,356 Starting Bokeh server version 1.0.2 (running on Tornado 5.1.1)
2019-01-23 03:53:51,381 Bokeh app running at: http://localhost:5006/visualizations
2019-01-23 03:53:51,381 Starting Bokeh server with process id: 1595
```

As mentioned above, it's not clear from the output whether the Postgres server is then started, or whether this might be causing the later error.  What I can say is that `pip list `shows that `py-postgresql 1.2.1` is installed.

**Comment by EdGreen21** [comment]
> There are multiple issues going on here and I'm trying to focus at one at a time. Is there any output in the `pvacapi` window?



> Can you also post the contents of the `~/.pvacseq` folder? Does it contain a `input.json` file? If so, what are its contents?

`~/.pvacseq` wasn't created automatically, and is empty.  When I put the example `input.vcf` into `~/.pvacseq/input/input.vcf` it also doesn't appear in the drop down box after refresh.

Apologies for conflating two issues, was trying to establish if the error could be traced to a difference between the github `setup.py` installation and the `pip` installation.

**Comment by susannasiebert** [comment]
So I think pVACapi is trying to start up postgres but in the process doesn't do the other things it's supposed to do on startup. Can you try starting postgres manually before starting the pvacapi. It's probably best if you delete the `~/pVAC-Seq` and `~/.pvacseq` folders so that if that is the issues, pvacapi can create all the required files on startup.

**Comment by EdGreen21** [comment]
```
ed@ed-VirtualBox:~$ source activate pvactools
(pvactools) ed@ed-VirtualBox:~$ service postgresql start
(pvactools) ed@ed-VirtualBox:~$ pvacapi
Initializing app configuration
Visualization server started on PID 1617
Unable to connect to your Postgres server.                         The pVAC-Seq API requires a running local Postgres server
Cleaning up visualization server
2019-01-23 04:30:02,497 Starting Bokeh server version 1.0.2 (running on Tornado 5.1.1)
2019-01-23 04:30:02,500 Bokeh app running at: http://localhost:5006/visualizations
2019-01-23 04:30:02,500 Starting Bokeh server with process id: 1618
(pvactools) ed@ed-VirtualBox:~$ sudo apt-get install postgresql
[sudo] password for ed: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
postgresql is already the newest version (10+190).
0 upgraded, 0 newly installed, 0 to remove and 219 not upgraded.
```
postgresql is definitely installed (see validation in code above), but running `service postgresql start` alone doesn't seem to be enough -the files aren't created.  Trying to access  `http://localhost:5006/visualizations` leads to a blank page, but it does display the header 'Bokeh Application'.

Running pvacviz in another terminal brings up the index.html page fine

**Comment by susannasiebert** [comment]
Ok, so it _is_ shutting down pVACapi when the postgres server isn't running correctly. So that's good. But without pVACapi running, pVACviz won't work, which is what you're seeing.

One thing we ran into is that we needed postgresql 9.6, instead of 10 (`sudo apt-get install postgresql-9.6`). I'm trying to get more information from a colleague that has been able to set up pVACviz successfully on Ubuntu on AWS. @huimingx can you please add your installation notes here as well.

**Comment by susannasiebert** [comment]
Here is the link to the installation instructions that my colleague but together: https://docs.google.com/document/d/1n5pxyTNBLxGvc1exbSYD5QAiM20zFwgbF5Ridzo0KkE/edit?usp=sharing. The key for your problem seems to be to get postgres up and running correctly so that pvacapi is able to connect to the database and run successfully.

**Comment by susannasiebert** [comment]
This issue is older and has had no further activity. Since we are removing pVACviz in version 3.0.0 I'm closing this issue.
