### ISSUE TITLE
pvacviz app webbrowser.open() function causes launch to fail if no default browser exists

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/pVACtools#257]
**Describe the bug**
pVACviz's app.py [attempts to open the viz app in a default browser](https://github.com/griffithlab/pVACtools/blob/master/utils/pvacviz/app.py#L59-L60). However, if no default browser exists, the script throws an error and exits. The script should test to see if a default browser was found before attempting to use the open() function.

**To Reproduce**
Attempt to launch `pvacviz` on an operating system with no installed browser.

**Log Output**
```
(python3.5) ubuntu@ip-172-31-27-163:~$ pvacviz
Tue Jan 22 14:48:53 2019 Starting pVACviz client webserver
Tue Jan 22 14:48:53 2019 pVACviz server started at http://localhost:4200
Tue Jan 22 14:48:53 2019 Opening pVACviz client at http://localhost:4200 in default browser.
Traceback (most recent call last):
  File "/usr/local/bin/miniconda/envs/python3.5/bin/pvacviz", line 11, in <module>
    sys.exit(main())
  File "/usr/local/bin/miniconda/envs/python3.5/lib/python3.5/site-packages/utils/pvacviz/app.py", line 60, in main
    webbrowser.get().open("http://%s:%s" % (HOSTNAME, PORT), new=1, autoraise=True)
  File "/usr/local/bin/miniconda/envs/python3.5/lib/python3.5/webbrowser.py", line 51, in get
    raise Error("could not locate runnable browser")
webbrowser.Error: could not locate runnable browser
```

**Expected behavior**
App script should print 'No default browser found.' and complete execution.

**Comment by EdGreen21** [comment]
I'd suggest this would be a useful edit, users could then run the pvactools Docker image, mapping a drive from the host to the pvactools container and forwarding port 4200 so that pvacviz was available on localhost:4200 on the host machine
