### ISSUE TITLE
Error running pvactools on VEP-annotated COSMIC VCF: VCF doesn't contain any sample genotype information.

### ISSUE THREAD

**Issue by alongalor** [griffithlab/pVACtools#279]
* pvactools version: 1.3.0
* Python version: 3.5.5 
* Operating System: Linux

**Describe the bug**
Error running pvacseq on VEP-annotated COSMIC VCF: VCF doesn't contain any sample genotype information. I am confused by this error message as your documentation reads: T

>The main input file to the pVACseq pipeline is a VCF file. At a minimum, the VCF needs to be annotated with VEP to add transcript information.

I have supplied a VCF annotated with VEP but am still getting this error. I realize the VCF does not contain a 'GT' flag as do other VCF files I have successfully run through the tool - is this a requirement? If so, perhaps this should be clarified in your docs. 

**To Reproduce**
What is the pVACtools command you ran? Please also attach any input files that can be used to reproduce this problem.

```
pvacseq run \
xaa.vcf \
xaa \
HLA-A*03:02 \
MHCflurry MHCnuggetsI MHCnuggetsII \
COSMIC/HLA-A*03:02/xaa \
-e 8,9,10,11
```
I am attaching my input below. For reference, this file was produced by downloading the COSMIC Coding mutations file (from https://cancer.sanger.ac.uk/cosmic/download by clicking the button "Download Whole File" under the header "VCF Files (coding and non-coding mutations)", after registering), pasting the header + the next 5000 line of the file and annotating it with VEP as suggested in your documentation (as shown below):

```
/n/data1/hms/dbmi/park/alon/software/VEP_most_recent/ensembl-vep/vep \
--database \
--input_file xaa.vcf  \
--output_file xaa.vcf  \
--format vcf \
--vcf \
--symbol \
--terms SO \
--tsl \
--hgvs \
--fasta human_g1k_v37.fasta \
--offline \
--cache \
--plugin Downstream \
--plugin Wildtype \
--dir_plugins /VEP_plugins \
--pick \
--dir_cache /VEP_Cache \
--assembly GRCh37
```

**Log Output**
```
Using TensorFlow backend.
Executing MHC Class I predictions
Converting .vcf to TSV
VCF doesn't contain any sample genotype information.
```

**Output File**
N/A

**Expected behavior**
To produce output as stipulated by program.

I should note I have successfully run both VEP and pvacseq using exactly the same commands, with different input files (TCGA data).

Thanks in advance for your help,

Alon

[xaa.vcf.gz](https://github.com/griffithlab/pVACtools/files/2842524/xaa.vcf.gz)

**Comment by susannasiebert** [comment]
Yes, the GT field is required. I will update the documentation accordingly.

**Comment by alongalor** [comment]
Are there any other required fields I should know about beyond the ones contained in my VCF? Thank you!

**Comment by susannasiebert** [comment]
I apologize for not getting back to you sooner on this question. From your more recent GitHub issue I infer that you were able to get it to work after adding the GT field. GT should be the only format/sample field needed. I believe this issue can be resolved but feel free to reopen if you have any other questions about your input VCF.

**Comment by alongalor** [comment]
Thanks a lot for your help Susanna!
