### ISSUE TITLE
sample_name not in VCF

### ISSUE THREAD

**Issue by tdw1221** [griffithlab/pVACtools#288]
I encountered the following error when trying to run pvaseq with a VEP-annotated vcf file. The vcf file was annotated with varscan2 and was from TCGA, I followed the instruction using VEP to annotate it, however, when I ran the following code
#######################
pvacseq run \
/ysm-gpfs/pi/zhao/dt485/immumutation/vcf/test_vcf/test_out_vep_annotate.vcf \
TCGA-WE-A8ZY-06A-11D-A372-08 \
HLA-A*01:01,HLA-A*02:01,HLA-B*07:02,HLA-B*08:01,HLA-C*07:01,HLA-C*07:02 \
NetMHC \
/ysm-gpfs/pi/zhao/dt485/immumutation/vcf/test_vcf/ \
-e 8,9,10 \
--iedb-install-directory /ysm-gpfs/pi/zhao/dt485/immumutation/IEDB \
-t 3
#######################

It produces the following error message:

#######################
Executing MHC Class I predictions
Converting .vcf to TSV
sample_name TCGA-WE-A8ZY-06A-11D-A372-08 not in VCF /ysm-gpfs/pi/zhao/dt485/immumutation/vcf/test_vcf/test_out_vep_annotate.vcf
#######################

It seems that it was caused by missing sample name in my single-sample vcf file, however, the meta data section of my vcf does include sample name as follow:
#######################
##SAMPLE=<ID=TUMOR,NAME=TCGA-WE-A8ZY-06A-11D-A372-08,ALIQUOT_ID=88a53c33-9d70-46cb-b62e-5afefcf3d580,BAM_ID=b0c0859e-9850-44cd-ad0b-89eaec6ae27d>
#######################

On top of that, I didn't see any part of the exmaple vcf contains the string "Test" (which was the sample name given in the tutorial), actually I was able to run the example code with different sample name and the code still worked, for example:
###################
pvacseq run \
/ysm-gpfs/pi/zhao/dt485/immumutation/pVAC/pvacseq_example_data/input.vcf \
TCGA-QW \
HLA-A*02:01,HLA-B*35:01,DRB1*11:01 \
NetMHC \
/ysm-gpfs/pi/zhao/dt485/immumutation/pVAC/pvacseq_example_data/ \
-e 8,9,10 \
--iedb-install-directory /ysm-gpfs/pi/zhao/dt485/immumutation/IEDB \
-t 3
###################

so I was wondering what's going on here and how can I fix it, thank you so much!

**Comment by susannasiebert** [comment]
The sample name is checked against the sample IDs in the #CHROM header, not from the ##SAMPLE headers.

**Comment by tdw1221** [comment]
@susannasiebert Thanks for the help, it does help! But I'm still curious why the example vcf file will still work under different sample names specification, shouldn't its sample name be "H_NJ-HCC1395-HCC1395"? thanks

**Comment by susannasiebert** [comment]
Looks like I forgot to hit send on a comment I meant to post yesterday that was meant to answer that question. We currently only execute this check if the input VCF contains more than one sample to identify which variants to process (the ones that have calls for that sample). If it's a single-sample VCF we will process that sample. I will update the attached PR to add that information to the help text.

**Comment by tdw1221** [comment]
Thank you so much!

**Comment by susannasiebert** [comment]
The usage information has been updated for version 1.3.1. to make this clearer. I'm resolving this issue but feel free to reopen or make a new one if you have additional questions.
