### ISSUE TITLE
add command-line option to supply IP address to api and viz

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/pVACtools#291]
Amazon and maybe other cloud providers have a public/private IP system, and only the private IP is discovered by the startup scripts. Since the public IP will need to be used for public access, we'll need to provide a method for users to manually provide this IP. I'm thinking --ip-address [address] would work.

**Comment by malachig** [comment]
This would be a new option that you would specify when you start the `pvacviz` process?

**Comment by susannasiebert** [comment]
@malachig that's my understanding.
