### ISSUE TITLE
Create helper tool to generate DNA sequences for the pvacvector peptide list

### ISSUE THREAD

**Issue by malachig** [griffithlab/pVACtools#294]
Currently pvactools outputs a list of peptides and their optimal order.  The trial workflow deals with creating the DNA construct as a separate exercise.  In some cases a DNA manufacturer may have their own process for determining the optimal DNA sequence for encoding a series of peptides.

Some groups may wish to take greater control over this aspect of the process.  Particularly for experimental (non-clinical) use of these DNA constructs.  

Maybe we could consider having an additional step that proposes the DNA sequence for the string of peptides that comes out of pvacvector?

**Comment by susannasiebert** [comment]
Would the DNA sequence be reverse engineered from the peptide sequence? What is the heuristic for determining which DNA codon to use for each amino acid?

**Comment by malachig** [comment]
Yes, we would need to discuss.  For each species the codon tables are known and probably available from existing python packages.  In cases where multiple codons are available a choice would need to be made.  Here there may be some preferences to improve DNA synthesis efficiency.  Would require a bit of research to see what is desired there.

**Comment by susannasiebert** [comment]
This tool might be useful to accomplish this task: https://www.ebi.ac.uk/Tools/st/emboss_backtranseq/
> EMBOSS Backtranseq reads a protein sequence and writes the nucleic acid sequence it is most likely to have come from.

They have an API so it would be easy to use for us. I wasn't able to find a license for the tool itself.

**Comment by susannasiebert** [comment]
There is also EMBOSS Backtranambig, which "back-translates protein sequences to ambiguous nucleotide sequences."

**Comment by malachig** [comment]
Just adding a note based on offline discussion.  In addition to synthesis efficiency (and potentially more important to efficacy) we would ideally optimize these sequences for *translation* efficiency.
