### ISSUE TITLE
germline variant

### ISSUE THREAD

**Issue by 41526** [griffithlab/pVACtools#308]
I wonder whether the germline variant can be downloaded from website or calculated by some tools with patient data?

**Comment by 41526** [comment]
I used the GATK toolkit to obtain somatic mutation data from patient data and known germline mutation data. Do I need to recalculate the patient's germline mutation data through the GATK toolkit? This is a waste of time.

**Comment by jhundal** [comment]
Germline variant calling can be done by any variant caller of your choice. However, to account for proximal variants in your final peptide sequence, you will need to do phasing of variants to determine if they are in phase or not. We recommend using GATK's ReadBackedPhasing for phasing of somatic and germline variants. You can follow the instructions on this page to generate this phased VCF from your somatic and germline VCFs : https://pvactools.readthedocs.io/en/latest/pvacseq/input_file_prep/proximal_vcf.html

**Comment by 41526** [comment]
Thank you.

**Comment by susannasiebert** [comment]
@41526 let us know if you run into any problems with this process. Since your question has been answered I will resolve this ticket but feel free to make a new one for any problems you might run into.
