### ISSUE TITLE
Pvacseq v4.0.10 (install from bioconda by conda) looks a bit weird

### ISSUE THREAD

**Issue by 41526** [griffithlab/pVACtools#311]
I installed pvacseq v4.0.10 from Bioconda using conda v4.5.12.
I find the usage is a little different from here.

usage: pvacseq run [-h] [-e EPITOPE_LENGTH] [-l PEPTIDE_SEQUENCE_LENGTH]
[--iedb-install-directory IEDB_INSTALL_DIRECTORY]
[-i ADDITIONAL_INPUT_FILE_LIST]
[--net-chop-method {cterm,20s}] [--netmhc-stab] [-t]
[-m {lowest,median}] [-b BINDING_THRESHOLD]
[-c MINIMUM_FOLD_CHANGE] [--normal-cov NORMAL_COV]
[--tdna-cov TDNA_COV] [--trna-cov TRNA_COV]
[--normal-vaf NORMAL_VAF] [--tdna-vaf TDNA_VAF]
[--trna-vaf TRNA_VAF] [--expn-val EXPN_VAL]
[--net-chop-threshold NET_CHOP_THRESHOLD]
[-a {sample_name}] [-s FASTA_SIZE] [-r IEDB_RETRIES]
[-d DOWNSTREAM_SEQUENCE_LENGTH] [-k]
input_file sample_name allele
{NNalign,NetMHC,NetMHCIIpan,NetMHCcons,NetMHCpan,PickPocket,SMM,SMMPMBEC,SMMalign}
[{NNalign,NetMHC,NetMHCIIpan,NetMHCcons,NetMHCpan,PickPocket,SMM,SMMPMBEC,SMMalign} ...]
output_dir

I tried to run pvacseq with the following command : 

pvacseq run -e 8,9,10,11 
--iedb-install-directory /pub6/temp/pb/Software/IEDB 
--normal-sample-name SRR5357710 
--pass-only /IJob/J33/Data/SRP102119_BC_12P22M34NSamples_WES/WESSRA/WESFastq/_AfterFASTQC_/_AfterAlign_/BAMFile/VEPtest/VEPoutput/SMC_OS_42VEPed.vcf 
SRR5357744 
HLA-A*02:01,HLA-B*35:01,DRB1*11:01 
NNalign NetMHC NetMHCIIpan NetMHCcons NetMHCpan PickPocket SMM SMMPMBEC SMMalign /IJob/J33/Data/SRP102119_BC_12P22M34NSamples_WES/WESSRA/WESFastq/_AfterFASTQC_/_AfterAlign_/BAMFile/pvacseq_output

An error comes to me : 

pvacseq run: error: argument prediction_algorithms: invalid choice: 'HLA-A*02:01,HLA-B*35:01,DRB1*11:01' (choose from 'NNalign', 'NetMHC', 'NetMHCIIpan', 'NetMHCcons', 'NetMHCpan', 'PickPocket', 'SMM', 'SMMPMBEC', 'SMMalign')

I tried another command again :

pvacseq run -e 8,9,10,11 
--iedb-install-directory /pub6/temp/pb/Software/IEDB
/IJob/J33/Data/SRP102119_BC_12P22M34NSamples_WES/WESSRA/WESFastq/_AfterFASTQC_/_AfterAlign_/BAMFile/VEPtest/VEPoutput/SMC_OS_42VEPed.vcf 
SRR5357744 
HLA-A*02:01,HLA-B*35:01,DRB1*11:01 
NNalign NetMHC NetMHCIIpan NetMHCcons NetMHCpan PickPocket SMM SMMPMBEC SMMalign /IJob/J33/Data/SRP102119_BC_12P22M34NSamples_WES/WESSRA/WESFastq/_AfterFASTQC_/_AfterAlign_/BAMFile/pvacseq_output

An error comes to me again :-( : 

Executing MHC Class I predictions
Converting VCF to TSV
ERROR: VCF file contains more than one sample

I understand the error message that i should specify a sample name, however, i don't know how to edit the command.

Thanks in advance.

**Comment by susannasiebert** [comment]
The `pvacseq` package is not longer supported. The pVACseq tool has been moved to the pVACtools suite and is available as part of the `pvactools` package instead. You can find installation instructions here: https://pvactools.readthedocs.io/en/latest/install.html

**Comment by 41526** [comment]
Thanks.

**Comment by 41526** [comment]
I used conda to simulate the python 3.5.6 environment and installed pvactools. The installation was successful without any errors or warnings. But when I executed pvacseq, nothing happened.

`pvacseq run -h`

!!!Nothing happened!!!

`pvacseq run --version`

!!!Nothing happened!!!

`pvactools -h`

usage: pvactools [-h] [-v] {download_cwls} ...

positional arguments:
  {download_cwls}
    download_cwls  Run pVACtools CWLs

optional arguments:
  -h, --help       show this help message and exit
  -v, --version    Display the currently installed pvactools version (default:
                   False)

`pvactools -v`

1.3.1

I am trying to upgrade pvactools using the command:

`pip install pvactools --upgrade`

It shows 
.
.
.
Requirement already satisfied, skipping upgrade: Werkzeug>=0.14 in /pub5/xiaoyun/BioSoftware/Conda/envs/pVACseq/lib/python3.5/site-packages (from flask>=0.10.1->connexion==1.4.2->pvactools) (0.14.1)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in /pub5/xiaoyun/BioSoftware/Conda/envs/pVACseq/lib/python3.5/site-packages (from packaging>=16.8->bokeh==0.13.0->pvactools) (2.3.1)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /pub5/xiaoyun/BioSoftware/Conda/envs/pVACseq/lib/python3.5/site-packages (from Jinja2>=2.7->bokeh==0.13.0->pvactools) (1.1.1)
Requirement already satisfied, skipping upgrade: html5lib==0.9999999 in /pub5/xiaoyun/BioSoftware/Conda/envs/pVACseq/lib/python3.5/site-packages (from tensorboard<1.9.0,>=1.8.0->tensorflow==1.8.0->pvactools) (0.9999999)
Requirement already satisfied, skipping upgrade: markdown>=2.6.8 in /pub5/xiaoyun/BioSoftware/Conda/envs/pVACseq/lib/python3.5/site-packages (from tensorboard<1.9.0,>=1.8.0->tensorflow==1.8.0->pvactools) (3.0.1)
Requirement already satisfied, skipping upgrade: bleach==1.5.0 in /pub5/xiaoyun/BioSoftware/Conda/envs/pVACseq/lib/python3.5/site-packages (from tensorboard<1.9.0,>=1.8.0->tensorflow==1.8.0->pvactools) (1.5.0)
 
It looks like every package is satisfied.

What should i do?

**Comment by d-henness** [comment]
I've had the same problem as you Ivan. I found it that it was caused by having tensorflow already installed in the conda environment before trying to install pVACtools. You can solve it by creating a fresh conda environment with only python 3.5 installed, and then running `pip install pvactools` as normal.

**Comment by 41526** [comment]
I use the following command:

conda create -n pVACseq python=3.5.6
source activate pVACseq
pip install pvactools

the problem still exists

**Comment by 41526** [comment]
It seems that pip installs pvactools automatically installed tensorflow

**Comment by d-henness** [comment]
Odd. Here is the exact commands I use. 
```
conda create -n testing_pvec ensembl-vep=95.2 python=3.5   vt=2015.11.10 tensorflow=1.8.0
conda activate testing_pvec
pip install pvactools
```

**Comment by 41526** [comment]
I use your command to install pvactools, however, this problem still exists

**Comment by 41526** [comment]
I guess it may be the reason for the software version.
How do I install the previous version?
Do you know this?

**Comment by susannasiebert** [comment]
Could it be that you still have the `pvacseq` package installed? What does `pip show pvacseq` return? If it looks like it's still installed, uninstall if by running `pip uninstall pvacseq`.

Regarding your question about installing a different version, you can do so by running `pip install pvactools==<version>`.

**Comment by susannasiebert** [comment]
Can you try installing an old version of pVACtools (like 1.2.0) and see if `pvacseq run -h` causes an error? You might be running into the same issue as https://github.com/griffithlab/pVACtools/issues/312
