### ISSUE TITLE
pvacseq stopped with no message

### ISSUE THREAD

**Issue by oldteng** [griffithlab/pVACtools#322]
* pvactools version: 1.3.2
* Python version: 3.6.4
* Operating System: CentOS 6

**Describe the bug**
I installed the pvactools using pip3 without any error logs. However, I can't get any help messages or logs when I run
"pvacseq"
"pvacseq -h"
"pvacseq valid_alleles"
or any other basic commands even without any input file.
![image](https://user-images.githubusercontent.com/18716279/54263582-23deb480-45ac-11e9-92da-677c803c6acd.png)

I also tried it with python 3.5.1 and it still doesn't work.
By the way, when I run the command "pvactools", it can successfully return the help message of pvactools.

**Comment by susannasiebert** [comment]
There is a bug in this release that results in error messages getting suppressed. Please upgrade to version 1.3.3 (pip install pvactools --upgrade), which shouldn't have this problem. You should then see what exactly the error is. Most likely it is related to your installation of Tensorflow. Please post you're error and I will be happy to help you debug the problem.

**Comment by oldteng** [comment]
Thanks a lot!
I updated pvactools and  got the error message that my tensorflow is not configured correctly because of the glibc is not up to date.
Because it is hard to update the glibc, I create a conda environment with python=3.5 and tensorflow=1.8 and it works!
