### ISSUE TITLE
Is there a way to filter by binding % rank from netMHC

### ISSUE THREAD

**Issue by tdw1221** [griffithlab/pVACtools#329]
I was wondering is there a way to filter results from epitopes' binding ranks instead of IC50, it seems that there's a growing emphasis on this criterion because each allele has a distinct spectrum of strong/weak binders in terms of IC50. netMHC 4.0 also provides rank based filtering itself, thanks!

**Comment by susannasiebert** [comment]
We don't currently support rank-based filtering but you might be interested in trying out the `--allele-specific-binding-thresholds` option. With this option, pVACseq will use allele-specific binding cutoffs as recommended by IEDB (https://help.iedb.org/hc/en-us/articles/114094151811-Selecting-thresholds-cut-offs-for-MHC-class-I-and-II-binding-predictions).

**Comment by tdw1221** [comment]
I see, thanks for letting me know!
