### ISSUE TITLE
lib/output_parser.py:485: yaml.load() without Loader=... is deprecated

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVACtools#330]
We need to update any call to `yaml.load` to specify a `Loader` like so: `yaml.load(input, Loader=yaml.FullLoader)`

**Comment by serge2016** [comment]
Hello.
When running pvacseq from pvactools 1.3.5 on Ubuntu14.04 I have this warning every time:
```
/usr/local/lib/python3.6/dist-packages/lib/output_parser.py:485: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  protein_identifiers_from_label = yaml.load(key_file_reader)
```

Is this warning already fixed with this PR?

**Comment by susannasiebert** [comment]
#344  fixes the warning. However, it hasn't been incorporated into a release yet. It will be part of the next feature release (1.4.0), which is denoted by the Milestone tag on the right.

**Comment by serge2016** [comment]
@susannasiebert Thank you!
