### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by jackyenbioinfo** [griffithlab/pVACtools#331]
* pvactools version: 1.3.3
* Python version: 3.5
* Operating System: linux

**Describe the bug**
tried to run pvacseq command but returns 
"Illegal instruction (core dumped)" other command like pvacfuse seems find

**To Reproduce**
What is the pVACtools command you ran? Please also attach any input files that can be used to reproduce this problem.

**Log Output**
```
The log that gets written to standard out
```

**Output File**
If your bug is related to the contents of an output file, please paste the output file here.

**Expected behavior**

**Comment by susannasiebert** [comment]
Without an input file and the exact command you ran, I won't be able to reproduce this problem. Please add this information to this issue.

**Comment by jackyenbioinfo** [comment]
Hello,
thanks for getting back to me. 
Here are the commands:

source activate py35  
pip install pvactools
pip list (just to check pvactools is install)

and I type 
"pvacseq" error message is the following 

"Illegal instruction (core dumped)"
It's hard to figure out what cause the error. could you help? thanks

**Comment by susannasiebert** [comment]
It is probably related to your conda environment. Which steps did you run to create `py35`?

**Comment by jackyenbioinfo** [comment]
hello thanks for getting back to me.
Here's the steps I took

conda create -n py35 python=3.5

and then I activate the enviroment
source activate py35

not sure what went wrong...could you help? thanks

**Comment by susannasiebert** [comment]
Unfortunately, I'm unable to reproduce this error locally. What does `pip freeze` return?
Also, do you get a core dump when you run `pvacseq -h` and `pvacseq run -h`?

**Comment by jackyenbioinfo** [comment]
hello,
pip freeze return
"pvactools==1.3.3" and other tools version

yes, same core dump error from  pvacseq -h and pvacseq run -h

**Comment by susannasiebert** [comment]
I know it's a lot of information but can you please post the full return of `pip freeze`. I would like to compare all of the installed packaged between your environment and mine.

**Comment by jackyenbioinfo** [comment]
[pip_freeze.txt](https://github.com/griffithlab/pVACtools/files/2989932/pip_freeze.txt)
thanks for your help!

**Comment by susannasiebert** [comment]
Your environment shows a lot of additional packages that mine doesn't. Did you install other packages aside from pvactools? Do you have the same problem when you do just the following:
```
conda create -n py35_new python=3.5
source activate py35_new
pip install pvactools
pvacseq -h
```

**Comment by jackyenbioinfo** [comment]
Hi, I tried the steps but still the same. So it's probably not the enviroment issue. I'm not sure what's wrong...if you have anything else I could try please let me know. Thanks!

**Comment by susannasiebert** [comment]
At this point I would suggest switching to our Docker image which is available at `griffithlab/pvactools`.

**Comment by jackyenbioinfo** [comment]
hello I'm thinking about building the pvactools from source. I googled on the error message and it seems might be related with architecture. Some people was able to solve it when re-build. Could you walk me through how to build pvactools from source? thanks

**Comment by susannasiebert** [comment]
You could `git clone` the repository and then regenerate the .whl file on your system following the instructions here: https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives. Once you have the .whl file you can run `pip install <.whl file>` to install.

**Comment by jackyenbioinfo** [comment]
Thanks! Downgraded to Tensorflow 1.50 and it fix my issue
