### ISSUE TITLE
update viz filter value increments

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/pVACtools#337]
Currently the VAF increment is set at .5, should be smaller.

**Comment by malachig** [comment]
I would adjust several of these to match our common use cases:

* Binding Threshold (best): 0 .. Max observed (increments of 10)
* Binding Threshold (median):0 .. Max observed (increments of 10)
* Fold Change -> Good as it is now
* Tumor DNA Depth -> Good as it is now
* Tumor DNA VAF -> 0 .. 1.0 (increments at 0.01)
* Tumor RNA Depth -> 0 .. Max observed (increments of 10)
* Tumor RNA VAF -> 0 .. 1.0 (increments at 0.01)
* Gene Expression: 0 .. Max observed (increments of 1)

**Comment by jmcmichael** [comment]
Note - Gene Expression increment [currently set to 1](https://github.com/griffithlab/pVACtools/blob/cae05029a204d7f66782ba603a2f421b7ef72dc7/utils/pvacapi/visualizations.py#L315), so I left it as-is. Reopening in case this needs to be adjusted.

**Comment by susannasiebert** [comment]
@malachig what's the final decision on the gene expression increment? If we change it to something different than 1, do we also adjust the transcript expression increment to the same value?

**Comment by malachig** [comment]
I think this is fine for now. Difficult to really handle this well with a slider like this.  You may want 0.01, 0.1, 1, 5, 5, 500, ...

Ultimately this maybe would be more flexible with an entry box where you could just enter what ever float value you want.  But it sounded like that would be difficult from what I remember?

**Comment by susannasiebert** [comment]
Yes, from what I remember it's difficult to have a slider that also has min max entry boxes.

**Comment by susannasiebert** [comment]
A PR for the entry box suggestion already exists (#161). I'll close this issue since the PR for changing the slider increments has been merged.
