### ISSUE TITLE
Add standalone command to create the pVACvector visualization from pVACvector output fasta

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVACtools#363]
When we run pVACvector on the cluster, we can't create the visualization file because the blades don't have DISPLAY set. We need a standalone command that the analysts can run on their Macs.

**Comment by malachig** [comment]
+1 to this idea.  a great candidate for a stand alone helper tool. in addition to this DISPLAY issue we may want to add customizations to the visualization over time.
