### ISSUE TITLE
Creating a phased VCF of proximal variants

### ISSUE THREAD

**Issue by ShahiRB** [griffithlab/pVACtools#371]
Dear developers,

GATK4 Mutect2 already has physical phasing information for some somatic variants (e.g given below). Thus can the same vcf file( or selecting 'tumour only' sample, if tumor-normal pair vcf) be used as an option for --phased-proximal-variants-vcf in pVACseq ?

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	normal_dna	**tumor_dna**
chr5	172373627	.	C	T	.	PASS	CONTQ=93;DP=26;ECNT=2;GERMQ=32;MBQ=42,39;MFRL=231,341;MMQ=60,40;MPOS=1;NALOD=1.11;NLOD=3.61;POPAF=5.60;SAAF=0.253,0.333,0.333;SAPP=0.030,0.021,0.949;TLOD=10.36	GT:AD:AF:DP:F1R2:F2R1:OBAM:OBAMRC:OBF:OBP:OBQ:OBQRC:PGT:PID:PS	0|0:12,0:0.071:12:8,0:4,0:false:false:.:.:.:.:0|1:172373622_C_A:172373622	**0|1:8,4:0.325:12:3,4:5,0:true:false:1.00:1.00:56.59:100.00:0|1:172373622_C_A:172373622**

Regards,
Rajendra

**Comment by susannasiebert** [comment]
Hi Rajendra,
Unfortunately, we currently don't support this phasing format. The current implementation uses phasing information provided via GATK's ReadBackedPhasing. Our current SOP for producing a phased VCF is outline [in our documentation](https://pvactools.readthedocs.io/en/latest/pvacseq/input_file_prep/proximal_vcf.html).

**Comment by rabiafidan** [comment]
Hi! 

Thank you for this amazing program! I was just wondering if you intend to update this step? It would be great to be able to use up-to-date tools in the market in my workflow.
Thank you!

Rabia
