### ISSUE TITLE
Some questions about Gene Expression and Transcript Expression values

### ISSUE THREAD

**Issue by ShahiRB** [griffithlab/pVACtools#373]
Hi @susannasiebert ,
 
1.  Is Gene Expression(ENSG) value [but not Transcript Expression(ENST) value) only considered for priority score calculation?

2. If Gene Expression value, can you please suggest me a tool to convert Kallisto output, that gives Transcript Expression value (TPM), to Gene Expression value(?).

3. And finally, in the foo.condensed.ranked.tsv file do you only output values for Gene Expression but not Transcript Expression?

Your help is appreciated!

KR
Raj

**Comment by susannasiebert** [comment]
1) Yes, only gene expression is considered for the ranking score (see [our documentation](https://pvactools.readthedocs.io/en/latest/pvacseq/output_files.html#the-pvacseq-neoeptiope-priority-score) for the exact calculation
2) You should be able to convert transcript-level metrics into gene-level metrics using [tximport](https://bioconductor.org/packages/release/bioc/vignettes/tximport/inst/doc/tximport.html)
3. Yes, the condensed file only outputs gene expression values (see [our documentation](https://pvactools.readthedocs.io/en/latest/pvacseq/output_files.html#filtered-condensed-ranked-tsv-report-columns) for a list of the columns and their contents)

**Comment by ShahiRB** [comment]
@susannasiebert , Thanx!
