### ISSUE TITLE
Make GitHub releases / version tags to track historical releases

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVACtools#377]

**Comment by Stikus** [comment]
Hello, any updates about release implementation?

**Comment by susannasiebert** [comment]
I should have some time next week to tackle this.

**Comment by serge2016** [comment]
@susannasiebert Thank you! It would be great!

**Comment by susannasiebert** [comment]
This has been completed. GitHub releases and tags are now available for all pVACtools versions.

**Comment by malachig** [comment]
Awesome!

**Comment by serge2016** [comment]
Thank you very much!
