### ISSUE TITLE
a lot of noisy messeges from MHCflurry in stdout 

### ISSUE THREAD

**Issue by NVSmirnova** [griffithlab/pVACtools#384]
* pvactools version:1.3.7
* Python version: from yours docker image griffithlab/pvactools:1.3.7 
* Operating System: from yours docker image griffithlab/pvactools:1.3.7 
Host OS ubuntu:18.04

**Describe the bug**
there are a lot of messeges in stdout like :

> Forcing tensorflow backend.
> Wrote: /tmp/tmp81r3i0pr
> Forcing tensorflow backend.
> Using TensorFlow backend.
> 2019-04-30 18:48:06.655778: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA

**To Reproduce** 
`docker run --rm --entrypoint /bin/bash -it -v /mnt/data/NSmirnova/pvacseq:/our_tool:ro -v /mnt/data/NSmirnova/pvactools_output:/output griffithlab/pvactools:1.3.7

pvacseq download_example_data /output/
pvacseq run -t 4 -e 9 -l 21 /output/pvacseq_example_data/input.vcf test01 "HLA-A*02:01,HLA-A*03:01,HLA-B*07:02,HLA-C*07:01,HLA-C*07:02" MHCflurry /output/test02`

**The log that gets written to standard out**
[pvactools_log_02.txt](https://github.com/griffithlab/pVACtools/files/3132956/pvactools_log_02.txt)

**Expected behavior**

1) We ask you if it possible to remove these messages from stdout. (We have found out that these messeges 

> Forcing tensorflow backend.
> Wrote: /tmp/tmp81r3i0pr
> Using TensorFlow backend

came from prediction_class.py (line 239 -256) more preciesly line 249. We tried to run just command from line 249 and got these 3 lines in stdout

`mhcflurry-predict --alleles H-2-Kb --out /tmp/nadya001 --peptides LPLPPPPLLP PLPPPPLLPL LPPPPLLPLL PPPPLLPLLL PPPLLPLLLL PPLLPLLLLL PLLPLLLLLL LLPLLLLLLG LPLLLLLLGA PLLLLLLGAS LLLLLLGASG LLLLLGASGG`

Also we remove the messege 

 

> tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA

from stdout by changing TF_CPP_MIN_LOG_LEVEL from 0 to 1

`export TF_CPP_MIN_LOG_LEVEL=0`

2) As we understood, TensorFlow doesn't use all possibilites of our mashine. Is it possible to make Tensorflow use all the benefits of our computers? (we tried to update Tensorflow to latest version and it didn't help, these messages stayed.)

**Comment by tufanchina** [comment]
same here

**Comment by susannasiebert** [comment]
1) I will look into it.
2) This page has  a pretty good writeup: https://stackoverflow.com/a/47227886. The short answer is that you would need to build tensorflow from the source optimized for your CPU, which, unfortunately, is non-trivial.
