### ISSUE TITLE
About Parsing the pvacseq results

### ISSUE THREAD

**Issue by xizhihui** [griffithlab/pVACtools#389]
Hi, thanks for your nice tools. 
I have used pvacseq with my data. But I got nothing in the `*.filtered.tsv`. Here are my questions:
* Does the empty filtered.tsv indicate that our data is bad ? Or how can I get the non-empty result ?
* * change the binding threshold ?
* If I can't get the non-empty result, I want to filter the all_epiptope.tsv to get some epiptopes, could you give me some advices? Just use the lower Best MT score is ok? I was confused by so many data to chose from.

Thank you for your help.

**Comment by susannasiebert** [comment]
Without seeing your results it's impossible to say why your epitopes didn't pass the filters. We recommend that you manually run the individual filters on the all_epitopes file using the standalone filtering commands to examine why your epitopes didn't pass the filters. See (https://pvactools.readthedocs.io/en/latest/pvacseq/filter_commands.html) for instructions. Running just the binding filter on the default 500 binding threshold for the median MT score is a good first start. This will eliminate a large portion of epitopes and you can then inspect the remaining ones to see why they failed the remaining filters and maybe adjust the filtering thresholds for the remaining filters accordingly.

**Comment by xizhihui** [comment]
Thanks for replying.  
I have found the reason why the filtered.tsv was empty. First, I ran the binding_score_filter and got 60 results.  But after the coverage_filter, all the 60 results were filtered. Besides, I found the input.yaml in logs, the values in it will be the parameters for filtering. Now I can check the filters  by myself.
Thanks again.
