### ISSUE TITLE
Support alternative known transcripts in Top Score Filter

### ISSUE THREAD

**Issue by malachig** [griffithlab/pVACtools#390]
Currently a variant leads to multiple peptides unique peptides due to nearby differential splice site usage, during the Top Score Filter step, the one with better binding is chosen.

These could be considered as district candidates. Its possible that both are expressed at the same time.  One might want to include both.

This is different from multiple peptides corresponding to different registers or lengths.  In those cases simply including flanking amino acid sequence in a synthetic long peptide or DNA vector design means that get all the slightly different candidates.  In the case of alternative transcripts, including flanking sequence doesn't help because it can only be based on a single transcript sequence.

Proposed ideas for handling this:
- include the transcript in what we consider the “variant”
- have an option for users as to how the define a ‘variant’ for the purpose of the top score filter
(i.e. whether or not to include the transcript).

**Comment by malachig** [comment]
For now, I have created some discussion in the docs to warn about this nuance.
https://github.com/griffithlab/pVACtools/pull/391

**Comment by susannasiebert** [comment]
Take into account the transcript, pick the best epitope per variant+transcript.
1.1. If the epitopes are different keep all of the different ones.
1.2. If the epitopes are the same, keep the one with the better transcript expression.
1.3. There might be some combination of the above cases that need to be handled.
1.4. We need to decide how to handle cases without transcript expression values available. Do we want to then output all, or just the first one?

**Comment by susannasiebert** [comment]
For 1.4 pick the lowest ensembl transcript ID

**Comment by susannasiebert** [comment]
This was closed prematurely.
