### ISSUE TITLE
python 3.7.3 switches to python 3.6.8

### ISSUE THREAD

**Issue by ShixiangWang** [griffithlab/pVACtools#395]
I see you write ` we recommend using Conda to emulate a Python 3.7 environment` at https://pvactools.readthedocs.io/en/latest/install.html . However in the `setup.py` you set `tensorflow==1.5.0`, it will make python 3.7 switches to python 3.6.8.

I just want to report this.

Thanks for your tool.

Best,
Shixiang

**Comment by susannasiebert** [comment]
Thank you for notifying us of this. We downgraded tensorflow to a lower version to support users with older CPUs. If your hardware supports a higher version of tensorflow you can manually upgrade it.
