### ISSUE TITLE
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.

### ISSUE THREAD

**Issue by ShixiangWang** [griffithlab/pVACtools#396]
* pvactools version: 1.4.0
* Operating System: CentOS

**Describe the bug**
`conda activate` cannot run within script, `conda activate` should switch to `source activate`.

`conda activate` in two scripts `prediction_class.py` and `call_iedb.py` cannot be used.

An error like the following will be returned.

```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Traceback (most recent call last):
  File "/public/data/.neopip/miniconda/envs/neopip/bin/pvacseq", line 10, in <module>
    sys.exit(main())
  File "/public/data/.neopip/miniconda/envs/neopip/lib/python3.7/site-packages/tools/pvacseq/main.py", line 92, in main
    args[0].func.main(args[1])
  File "/public/data/.neopip/miniconda/envs/neopip/lib/python3.7/site-packages/tools/pvacseq/run.py", line 81, in main
    lib.call_iedb.setup_iedb_conda_env()
  File "/public/data/.neopip/miniconda/envs/neopip/lib/python3.7/site-packages/lib/call_iedb.py", line 13, in setup_iedb_conda_env
    version_check = run("/bin/bash -c \"conda activate pvactools_py27 && python -c \\\"import platform; print(platform.python_version())\\\"\"", stdout=PIPE, check=True, shell=True)
  File "/public/data/.neopip/miniconda/envs/neopip/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/bin/bash -c "conda activate pvactools_py27 && python -c \"import platform; print(platform.python_version())\""' returned non-zero exit status 1.

```

I tried using `conda init bash` or `conda init` many times and did not work.

However `conda activate` works in terminal. I know the problem comes from a different shell is called by the python script. But I cannot figure it out why the result of `conda init` cannot apply to the shell called by python even `/bin/bash` is specified.

Best,
Shixiang

**Comment by susannasiebert** [comment]
What about running `/bin/bash -c "conda init"`? Have you already tried that?

**Comment by susannasiebert** [comment]
We determined that this is a bug in the latest version of pVACtools. We are working on a new release.

**Comment by susannasiebert** [comment]
The newest version 1.4.1 should fix this issue. Please give it a try and let me know if the error persists.

**Comment by ShixiangWang** [comment]
It works, thanks :).

**Comment by diaamayaram** [comment]
Hello, I yet get the same error:

- pvactools version: 1.4.1

- Operating System: Linux Mint 19

`CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.                                                                                   To initialize your shell, run                                                                                                                                                                                                                                                                                                                                 $ conda init <SHELL_NAME>                                                                                                                                                                                                                                                                                                                             Currently supported shells are:                                                                                                                                                - bash                                                                                                                                                                       - fish                                                                                                                                                                       - tcsh                                                                                                                                                                       - xonsh                                                                                                                                                                      - zsh                                                                                                                                                                        - powershell                                                                                                                                                                                                                                                                                                                                            See 'conda init --help' for more information and options.                                                                                                                                                                                                                                                                                                 IMPORTANT: You may need to close and restart your shell after running 'conda init'.                                                                                                                                                                                                                                                                                                                                                                                                                                                    Traceback (most recent call last):                                                                                                                                             File "/home/diegoamaya/miniconda2/envs/pavcseq_1_4_1_2/bin/pvacseq", line 10, in <module>                                                                                      sys.exit(main())                                                                                                                                                           File "/home/diegoamaya/miniconda2/envs/pavcseq_1_4_1_2/lib/python3.7/site-packages/tools/pvacseq/main.py", line 92, in main                                                    args[0].func.main(args[1])                                                                                                                                                 File "/home/diegoamaya/miniconda2/envs/pavcseq_1_4_1_2/lib/python3.7/site-packages/tools/pvacseq/run.py", line 81, in main                                                     lib.call_iedb.setup_iedb_conda_env()                                                                                                                                       File "/home/diegoamaya/miniconda2/envs/pavcseq_1_4_1_2/lib/python3.7/site-packages/lib/call_iedb.py", line 13, in setup_iedb_conda_env                                         version_check = run("/bin/bash -l -c \"conda activate pvactools_py27 && python -c \\\"import platform; print(platform.python_version())\\\"\"", stdout=PIPE, check=True, shell=True)                                                                                                                                                                    File "/home/diegoamaya/miniconda2/envs/pavcseq_1_4_1_2/lib/python3.7/subprocess.py", line 487, in run                                                                          output=stdout, stderr=stderr)                                                                                                                                            subprocess.CalledProcessError: Command '/bin/bash -l -c "conda activate pvactools_py27 && python -c \"import platform; print(platform.python_version())\""' returned non-zero exit status 1. `


Thanks in advance for your help

**Comment by ShixiangWang** [comment]
did you ever run conda init bash and try again?

**Comment by diaamayaram** [comment]
yes, I tried it but doesn't work

**Comment by tmooney** [comment]
@diaamayaram Because conda environments are not currently inherited by subshells (see conda/conda#7753), the fix in pvactools depends on conda initialization being part of your bash profile.  (In the [pvactools Docker image](https://hub.docker.com/r/griffithlab/pvactools) this is in handled in `/etc/profile.d/conda.sh`.)  Is conda initialization a part of your bash profile (either at the system level or personal `.bash_profile`)?
