### ISSUE TITLE
How to access output files by script

### ISSUE THREAD

**Issue by ShixiangWang** [griffithlab/pVACtools#398]
Dear author,

I want to access the output files by script. However [here](https://pvactools.readthedocs.io/en/latest/pvacseq/output_files.html) I see there are three cases, how can I know which directory will be created for results when HLA alleles and prediction algorithm are specified. Specially, MHCnuggests supports both MHC I and MHC II according to [the features](https://pvactools.readthedocs.io/en/latest/pvacseq/features.html).

And I see pvactools integrate NetChop and NetMHCstab, are they implemented by web API or built in pvactools?

Best,
Shixiang

**Comment by susannasiebert** [comment]
If you specify at least one class I prediction algorithm and a class I MHC allele that the class I prediction algorithm supports then the `MHC_Class_I` directory will be written. If you specify at least one class II prediction algorithm and a class II MHC allele that the class II prediction algorithm supports then the `MHC_Class_I`I directory will be written. If you specify both class I and class II prediction algorithms and class I and class II alleles then all three directories (`MHC_Class_I`, `MHC_Class_II`, `combined`) will be written.

To run MHCnuggets on class I MHC alleles you will need to specify the `MHCnuggetsI` prediction algorithm. For class II MHC alleles it's `MHCnuggetsII`.

pVACtools makes requests to the DTU Health Tech NetChop and NetMHCstabpan servers to add cleavage site and binding stability predictions.

**Comment by ShixiangWang** [comment]
Thank your reply. I understand the logic now.

**Comment by ShixiangWang** [comment]
BTW, is there a way to classify valid alleles supported by pvactools into MHC I and II?

**Comment by susannasiebert** [comment]
The `pvacseq valid_alleles` command doesn't provide this command directly but you can use the `-p` argument to specify a particular prediction algorithm and it will tell you which alleles are valid for it.

**Comment by ShixiangWang** [comment]
@susannasiebert Thanks again!
