### ISSUE TITLE
[Need Help] Could not perform "pvacseq run" using the docker image with the parameter "--iedb-install-directory /opt/iedb"

### ISSUE THREAD

**Issue by Chitanda-Satou** [griffithlab/pVACtools#404]
Greetings.

I have been using the docker image of pVACtools, but a strange error occured.

The code is:

![1](https://user-images.githubusercontent.com/32410912/58547055-42faf300-8239-11e9-81b1-6509626eac0a.png)

And the error is:
```
Executing MHC Class I predictions
Restart inputs are different from past inputs:
Past input: iedb_executable - None
Current input: iedb_executable - /opt/iedb/mhc_i/src/predict_binding.py
Aborting.

```

I built a new folder, which contained only the VCF file, but this error still occured.

What's the matter could it be?

The docker image version is:

![图片](https://user-images.githubusercontent.com/32410912/58547228-99683180-8239-11e9-8f77-7435d589e8b9.png)

Thanks a lot!

**Comment by susannasiebert** [comment]
As the error message says `Restart inputs are different from past inputs:`. On your first attempt you didn't use the `--iedb-install-directory` parameter but on the second attempt you did. When you change parameters between runs, pVACseq will abort since it can't guarantee that the outputs will be consistent with different inputs. You will need to delete the existing output directory or specify a new one.

**Comment by Chitanda-Satou** [comment]
Thanks a lot for the suggestion, @susannasiebert . But I still failed after builting a entirely new folder...
The folder only contained one VCF:
![图片](https://user-images.githubusercontent.com/32410912/58611286-30d48f80-82e1-11e9-9b81-3cd289be5934.png)

And the command is:
![图片](https://user-images.githubusercontent.com/32410912/58611327-4e095e00-82e1-11e9-98e8-b03e935614af.png)

But the error is the same as before: 
![图片](https://user-images.githubusercontent.com/32410912/58611482-dab41c00-82e1-11e9-964a-9245fc79b14d.png)


It is really weired...

**Comment by Chitanda-Satou** [comment]
Ah, I found out what's the matter. Because of some reasons, the results of last run will remain in the folder "/pvacseq_output_data" of the docker image. So, make a new $output_dir, regardless of whatever the $output_dir exists or not, will fix this issue.

Thanks a lot!
