### ISSUE TITLE
pVACviz doesn't visualize tsv files

### ISSUE THREAD

**Issue by KyleTCL** [griffithlab/pVACtools#409]
* pvactools version: 1.4.2
* Python version: 3.6.5
* Operating System: Debian (pvactools-docker), host - centos

**Describe the bug**
Opening tsv files in the Vizualizable Files does not show anything except sample name and path to the tsv file.

**To Reproduce**
1. Install pvactools using docker pull griffithlab/pvactools
2. Run the pvactools image with docker (bind 4200, 5432, 8080, 5006 to host)
3. Start postgresql, followed by pvacapi then pvacviz
4. Navigate to localhost:4200 with a browser
5. Run an analysis and complete
6. Open the tsv from the run
7. Tsv opened but no visualization of scatterplot

**Log Output**
This is the output from pvacapi.
```
172.17.0.1 - - [14/Jun/2019 14:01:27] "GET /api/v1/processes/6 HTTP/1.1" 200 -
Query: SELECT rowid,chromosome,start,stop,reference,variant,transcript,transcript_support_level,ensembl_gene_id,variant_type,mutation,protein_position,gene_name,hgvsc,hgvsp,hla_allele,peptide_length,sub_peptide_position,mutation_position,mt_epitope_seq,wt_epitope_seq,best_mt_score_method,best_mt_score,corresponding_wt_score,corresponding_fold_change,tumor_dna_depth,tumor_dna_vaf,tumor_rna_depth,tumor_rna_vaf,normal_depth,normal_vaf,gene_expression,transcript_expression,median_mt_score,median_wt_score,median_fold_change,netmhc_wt_score,netmhc_mt_score FROM data_6_11 ORDER BY rowid ASC LIMIT 1
172.17.0.1 - - [14/Jun/2019 14:01:27] "GET /api/v1/processes/6/results/11/visualize HTTP/1.1" 200 -
```

**Output File**

**Expected behavior**
Tsv result file open with scatterplot along with a set of tools.

**Comment by susannasiebert** [comment]
What's the size of the file you are trying to visualize?

**Comment by KyleTCL** [comment]
Hi, 
I have try to troubleshoot the problem, I found out:
I should have mentioned previously that I was setting up pVACtools on a server. Due to this, when I try to visualize it, it try to connect to 172.17.0.2 (the docker container ip address on the server) which doesn't exist in local network. To solve this, the docker need to use the host network `--network host` or specify the ip address when starting pvacapi and pvacviz. 

I try this and it works on local pc. However, it doesn't work on the server. When specifying the ip-address,  it does start except bokeh which state my ip xxx.xxx.xxx.xxx is not available. Any idea?

Thank you!

**Comment by susannasiebert** [comment]
Can you please provide the exact commands you are using the start pVACviz and pVACapi?

**Comment by susannasiebert** [comment]
@KyleTCL were you able to resolve this issue?

**Comment by KyleTCL** [comment]
@susannasiebert  Sorry for such a late reply.
The exact command I was using is:

```
docker run -it --rm --name pvac --network host griffithlab/pVACtools bash
/etc/init.d/postgresql start
pvacapi

docker exec -it pvac bash
pvacviz
```

Since I pass the host network to the container, the pvacapi and pvacviz uses the host IP address:port and the vizualization (Bokeh) no longer query 127.0.0.2 (which can't be reached outside the container). Now it works on local machine. (However, this only works on Linux since Mac/Win can't pass host network to the container)

However when I use it on a server with a floating IP, floating IP is not pass to the container. So, when i try to do the following:

```
pvacapi --ip-address = floatingip
```

It cannot find the ip-address since it doesn't exist in the container (thus my comment above). 

Now I am using it on my local machine but it will be nice to be able to deploy it to a server and just connect whenever/wherever i need it. Thanks!

**Comment by jmcmichael** [comment]
Hi @KyleTCL, the command line argument `proxy-ip-address` was implemented to handle your production use case. To launch pvacapi so that it's aware it is running through a proxy, use the following command:

`pvacapi --proxy-ip-address [ip-address]`

This will cause Bokeh to query that IP when loading the visualization.

Note that you should put pvacapi on a public server with extreme caution, as the bare-bones web server we are using was built only for use in development that thus does not have the security hardening that comes standard with web servers like Apache or nginx. It is also not optimized for heavy or even moderate traffic.

**Comment by KyleTCL** [comment]
> Hi @KyleTCL, the command line argument `proxy-ip-address` was implemented to handle your production use case. To launch pvacapi so that it's aware it is running through a proxy, use the following command:
> 
> `pvacapi --proxy-ip-address [ip-address]`
> 
> This will cause Bokeh to query that IP when loading the visualization.
> 
> Note that you should put pvacapi on a public server with extreme caution, as the bare-bones web server we are using was built only for local use and development, thus does not have the security hardening that comes standard with web servers like Apache or nginx. It is also not optimized for heavy or even moderate traffic.

Thank you, this works.
