### ISSUE TITLE
Update to new version of mhcnuggets

### ISSUE THREAD

**Issue by malachig** [griffithlab/pVACtools#421]
There is a shiny new version of MHCnuggets. 
https://github.com/KarchinLab/mhcnuggets-2.3

Update pvactools to support this version?  Should we just support the latest version or multiple versions?

**Comment by susannasiebert** [comment]
By default we will run whichever version is installed by the user via pip. Even though they made a new repo, it's still one package on pypi with different versions. I don't think there is a good way for the pVACtools user to choose which version to run as that would require us to install different versions of the packages for them.

**Comment by malachig** [comment]
Okay, this seems fine to me.

**Comment by susannasiebert** [comment]
To add to my previous comment: there is nothing we need to do on our end to add support for this new version. We might want to consider updating our test data to match the latest version but for now I pinned an old version of the package in the .travis.yml so that the travis-ci tests will continue passing.

**Comment by malachig** [comment]
To summarize, the user will get mhcnuggets-2.3 results in pvactools as long as they have installed that version via pypi.  We therefore do support this version but our code test results are based on a fixed older version for now. Has anyone tried and confirmed that it works as expected with the mhcnuggets-2.3 installed.

**Comment by susannasiebert** [comment]
Class I predictions seem to work fine in version 2.3 but there is a bug in the mhcnuggets class ii code that results in errors. A bug report has been filed here: https://github.com/KarchinLab/mhcnuggets-2.3/issues/1. I also pinned the 2.2 version in our docker image.

**Comment by malachig** [comment]
This bug report link is dead because they renamed the repo.  Susanna is going to submit a new bug report and/or just submit a PR.

**Comment by susannasiebert** [comment]
pull request submitted here: https://github.com/KarchinLab/mhcnuggets/pull/7
