### ISSUE TITLE
Error with PickPocket output file 

### ISSUE THREAD

**Issue by BenSDuggan** [griffithlab/pVACtools#427]
* pvactools version: 1.4.2
* Python version: 2.7
* Operating System: Linux

**Describe the bug**
I am running pvacseq with all prediction algorithms. I have ran over 150 different samples through the pipeline, all successful, but have been getting the error on a few:
```
Traceback (most recent call last):
  File "/opt/conda/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/tools/pvacseq/main.py", line 92, in main
    args[0].func.main(args[1])
  File "/opt/conda/lib/python3.6/site-packages/tools/pvacseq/run.py", line 163, in main
    pipeline.execute()
  File "/opt/conda/lib/python3.6/site-packages/lib/pipeline.py", line 427, in execute
    split_parsed_output_files = self.parse_outputs(chunks)
  File "/opt/conda/lib/python3.6/site-packages/lib/pipeline.py", line 388, in parse_outputs
    parser.execute()
  File "/opt/conda/lib/python3.6/site-packages/lib/output_parser.py", line 384, in execute
    iedb_results = self.process_input_iedb_file(tsv_entries)
  File "/opt/conda/lib/python3.6/site-packages/lib/output_parser.py", line 317, in process_input_iedb_file
    iedb_results = self.parse_iedb_file(tsv_entries)
  File "/opt/conda/lib/python3.6/site-packages/lib/output_parser.py", line 493, in parse_iedb_file
    protein_label  = int(line['seq_num'])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
I have also reran these files with the same result. Upon further investigation PickPocket is writing `* Warning: Potential DNA sequence(s) found! This tool is intended to predict for amino acid sequences. Please double check your input fasta file.` to its tsv file in the tmp folder. I believe this is causing the error as the file can't be parsed. Do you know why PickPocket would be saying this? All of these files were processed using the same pipeline.

**To Reproduce**
`pvacseq run --keep-tmp-files --n-threads 8 -e 8,9,10,13,15 --iedb-install-directory /opt/iedb --iedb-retries 50 <input_annotated_vcf> <sample_name> HLA-A*01:223,HLA-A*01:17,HLA-A*03:01P,HLA-B*08:01P,HLA-B*08:02,HLA-B*41:01P,HLA-B*41:42,HLA-C*17:01P,HLA-C*07:119,HLA-C*07:01P,HLA-F*01:01P,HLA-G*01:01P,DPA1*01:03P,DPA1*03:04,DPA1*03:01P,DPB1*04:01P,DPB1*03:01P,DQA1*01:02P,DQA1*04:01P,DQB1*06:04P,DQB1*03:01P,DQB1*03:197Q,DRA*01:01P,DRB1*14:03P,DRB1*14:06P,DRB1*08:03P,DRB3*01:01P,DRB3*02:02P,DRB4*01:01 MHCflurry MHCnuggetsI MHCnuggetsII NNalign NetMHC NetMHCIIpan PickPocket SMM SMMPMBEC SMMalign <output_folder>`

**Log Output**
These are the last few lines lines printed to the output:
```
Parsing prediction file for Allele HLA-C*07:119 and Epitope Length 10 - Entries 1-200 - Completed
Parsing binding predictions for Allele HLA-C*07:119 and Epitope Length 13 - Entries 1-200
Parsing prediction file for Allele HLA-C*07:119 and Epitope Length 13 - Entries 1-200
Parsing prediction file for Allele HLA-C*07:119 and Epitope Length 13 - Entries 1-200 - Completed
Parsing binding predictions for Allele HLA-C*07:119 and Epitope Length 15 - Entries 1-200
Parsing binding predictions for Allele HLA-A*01:17 and Epitope Length 8 - Entries 201-400
Parsing prediction file for Allele HLA-A*01:17 and Epitope Length 8 - Entries 201-400
```

**Expected behavior**
PickPocket completed successfully and continued to next prediction algorithm.

**Comment by susannasiebert** [comment]
It looks like Ben's run has some peptide sequences that look like this:
```
WGAAAAAAAAAAAAAAAAHLP
WGAAAAAAAAAAAAAAAHLP
```
Some of the epitopes then are all `A`s, which results in IEDB giving the helpful warning `Warning: Potential DNA sequence(s) found! This tool is intended to predict for amino acid sequences. Please double check your input fasta file.` We need to add handling for files that contain this warning.

**Comment by BenSDuggan** [comment]
#429 fixed this problem!
