### ISSUE TITLE
pvacbind output number of candidates does not match input 

### ISSUE THREAD

**Issue by huimingx** [griffithlab/pVACtools#435]
After running pvacbind with the input /gscmnt/gc2596/griffith/h.xia/r_shiny_app/anchor_analysis/anchor_9mer_input.fa, I noticed that while the input was 1800 (1629 if removing duplicates), the output number of candidates in the all_epitopes file was found to be 1229. 

Wondering if there are any internal filtering or removal happening?

**Comment by susannasiebert** [comment]
Can you please also post the full command that you ran?

**Comment by huimingx** [comment]
pvacbind run -e 9 --iedb-install-directory /opt/iedb --iedb-retries 50 --binding-threshold 500 --allele-specific-binding-thresholds --keep-tmp-files --n-threads 16 --net-chop-method cterm --netmhc-stab anchor_9mer_input.fa ANCHOR_9 HLA-A*01:01 MHCflurry MHCnuggetsI NetMHC NetMHCcons NetMHCpan PickPocket SMM SMMPMBEC ./
