### ISSUE TITLE
Investigate using the rank/percentile for interpreting binding affinity

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVACtools#454]
IEDB outputs a rank/percentile_rank along the ic50 binding affinity. We should investigate using this as an alternative to ic50. This would also allows us to support the Combinatorial library and Sturniolo Class II prediction algorithms (see #234) and other algorithms that only output ranks.

This would require us to rework our binding filter.

**Comment by hezt** [comment]
Thanks a lot for your remarkable project.
I need the percentile rank not only ic50, too.

**Comment by malachig** [comment]
Thanks @hezt.  We do consider this a priority as well.  We will let you know when we have more definitive idea of when this feature will be incorporated.

**Comment by malachig** [comment]
Susanna is going to start by reporting which algorithms we currently support that report an percentile rank.  We will also start reporting this in the output and discuss further how will more fully support working with percentiles instead of (or in addition to) IC50 values.

**Comment by susannasiebert** [comment]
I confirmed that all prediction algorithms we currently use except for MHCnuggets output a percentile rank. They are reported in full percentages and a lower number is better.

I propose that we output `NA` for MHCnuggets percentile rank and calculate the median and lowest percentile, similar to how we report the ic50 binding affinity.

**Comment by chrisamiller** [comment]
+1 to that proposal

**Comment by MatDal** [comment]
> I confirmed that all prediction algorithms we currently use except for MHCnuggets output a percentile rank. They are reported in full percentages and a lower number is better.
> 
> I propose that we output `NA` for MHCnuggets percentile rank and calculate the median and lowest percentile, similar to how we report the ic50 binding affinity.

+1
I think that percentile rank is very important. In some cases The ic50 is 1000 nM for example but the percentile rank is very low (0.5).

**Comment by susannasiebert** [comment]
#508 adds percentile ranks to the output reports. TODOs:

- [ ] Discuss and implement a filtering strategy
- [ ] Discuss and implement incorporating the percentile into the pVACseq rank

**Comment by susannasiebert** [comment]
Further development is being tracked on issues #517 and #518. Closing.
