### ISSUE TITLE
TSV files empty 

### ISSUE THREAD

**Issue by adbeggs** [griffithlab/pVACtools#455]
* pvactools version: 1.5.1 (via docker image)
* Python version: 3.65 (via docker image)
* Operating System: Ubuntu 18.04LTS

**Describe the bug**
I am trying to predict Class I MHC binding from some NGS data. I get the empty TSV file error despite there being indels in there (I have filtered as well from VEP). I have checked that the wildtype etc fields are there and they (as in the previous issue). I am a novice at pVacSeq so I can't quite understand why it isn't working - sorry!

**To Reproduce**
pvacseq run /pvacseq_example_data/P004027_combined.vep.vcf TUMOR HLA-A*30:01,HLA-B*13:02 MHCflurry MHCnuggetsI MHCnuggetsII NNalign NetMHC PickPocket SMM SMMPMBEC SMMalign /pvacseq_output_data -e 8,9,10 --iedb-install-directory /opt/iedb

**Log Output**
pvacseq run /pvacseq_output_data/P004027_pvac.vep.filtered.vcf TUMOR HLA-A*30:01,HLA-B*13:02 MHCflurry MHCnuggetsI MHCnuggetsII NNalign NetMHC PickPocket SMM SMMPMBEC SMMalign /pvacseq_output_data -e 8,9,10 --iedb-install-directory /opt/iedb
Executing MHC Class I predictions
Converting .vcf to TSV
Completed
The TSV file is empty. Please check that the input VCF contains missense, inframe indel, or frameshift mutations.
```

**Comment by adbeggs** [comment]
[example.filtered.vcf.gz](https://github.com/griffithlab/pVACtools/files/3566878/example.filtered.vcf.gz)

**Comment by susannasiebert** [comment]
You're sample is missing the GT field for all entries. Without it, pVACseq doesn't know which alleles to process and it skips all entries.

**Comment by susannasiebert** [comment]
I assume that you were able to resolve this problem so I will close this GitHub issue. Please feel free to reopen if you're still having issues.
