### ISSUE TITLE
How are MHC class I and II predictions combined in pvacseq's combined output?

### ISSUE THREAD

**Issue by kylec** [griffithlab/pVACtools#470]
* pvactools version: 1.5.2
* Python version: 3.7.3
* Operating System: red hat 6

I ran pvacseq with NetMHCpan and NetMHCpanII. The combined filtered output (295 lines) has is less than the lines in MHC class I and II combined (194 + 271 lines). 
`295 combined/sample.filtered.tsv`
`194 MHC_Class_I/sample.filtered.tsv`
`271 MHC_Class_II/sample.filtered.tsv`

What kind of filtering is done when Class I and II output are combined?

**Comment by malachig** [comment]
In general, our own workflow involves running class I and II separately so that one has more flexibility in interpreting them after the fact.

**Comment by nicoleversetwo** [comment]
Is there a way to manually filter this the same way? Using the docker version of pvacseq, during the stage where the files are combined and filtered, the job often stalls out or is auto-killed (see below)


Done: Pipeline finished successfully. File /opt/iedb/pvacseq_example_data/***-1768/MHC_Class_II/TUMOR.filtered.tsv contains list of filtered putative neoantigens.

Creating combined reports
Creating aggregated report
Tumor clonal VAF estimated as 0.6 (estimated from Tumor DNA VAF data). Assuming variants with VAF < 0.3 are subclonal
Killed
root@368e993f4f9a:/opt/iedb#

**Comment by susannasiebert** [comment]
You can run the standalone filter commands on the all_epitopes.tsv file in the `combined` directory. Please see the [documentation](https://pvactools.readthedocs.io/en/latest/pvacseq/filter_commands.html) for more info.

You might need use a machine with more memory if the aggregate report creation is failing. How big is your all_epitopes.tsv file? Which version of pVACtools are you using?

**Comment by nicoleversetwo** [comment]
Thank you! 

The all epitopes file is about 200MB. It seemed like the filtering process was taking between 2-4 hours, but it was only completing 50% of the time.

I'm using the desktop version of docker and griffithlab/pvactools:latest-slim

**Comment by susannasiebert** [comment]
Can you try with version 3.1.1? We made some improvements to the aggregate report step that should speed things up but your docker client might've cached an older version. You can explicitly use this version by referencing `3.1.1-slim` instead of `latest-slim`.
