### ISSUE TITLE
local IEDB database of IEDB_MHC_II-2.17.6.tar.gz

### ISSUE THREAD

**Issue by fgsjcathy** [griffithlab/pVACtools#473]
Hi,
I run the following script in environment Python 2, but it has some AssertionError errors.

tar -zxvf IEDB_MHC_II-2.17.6.tar.gz
cd mhc_ii
./configure.py

I observe the error information and find the content in configure.py is different from the  mhc_II_binding.py result,so it report the AssertionError.

I want to know how to deal with this condition and Whether it will affect the use of the database？

Thank you in advanced！

**Comment by susannasiebert** [comment]
Since this is a problem with IEDB, and not with pVACtools itself, we recommend filing a ticket in their help forum at help.iedb.org. Unfortunately, we are unable to provide support as the IEDB software is not created by us.
