### ISSUE TITLE
 phased VCF need to be annotated by VEP ?

### ISSUE THREAD

**Issue by zhangyafeng1** [griffithlab/pVACtools#478]
hi, 
Thanks for attention！
when i create a phased vcf ,  germline.vcf and somatic.vcf are required ，and my doubts are should i annotate them with VEP ? 
In my pipline , somatic.vcf was annotated with VEP ,and germline.vcf was not annotated with VEP . Will this affect the final result?
Thank you very much!

**Comment by susannasiebert** [comment]
You should re-annotate you phased VCF with VEP before using it in pVACseq. This ensures that all variants will have VEP annotations available.

**Comment by zhangyafeng1** [comment]
when I re-annotate my phased VCF with VEP ,  a warning file was generated,  its content is as follows:

"WARNING: Chromosome chr1_gl000191_random not found in annotation sources or synonyms on line 443388"

should I need to pay attention to these?

**Comment by susannasiebert** [comment]
I assume that just means that VEP/Ensembl doesn't know what `chr1_gl000191_random` is referring to so it can't annotate variants with that chromosome. They can then not be processed in pVACseq but pVACseq should just skip these entries.
