### ISSUE TITLE
pVACfuse does not recognize agfusion directory

### ISSUE THREAD

**Issue by CodyRamirez** [griffithlab/pVACtools#479]
* pvactools version: 1.5.3
* Python version: 2.7
* Operating System: ?
Using docker(griffithlab/pvactools:1.5.3) within MGI cluster research-hpc

**Describe the bug**
pVACfuse does not recognize that I am passing it agfusion results which it request a directory path. Instead pVAcfuse reads it in as a .bedpe file which it tries to convert to a tsv file, which is then empty obviously. Then because the file is empty, it immediately fails out.

**To Reproduce**
What is the pVACtools command you ran? Please also attach any input files that can be used to reproduce this problem.

**Log Output**
```
1.5.3: Pulling from griffithlab/pvactools
Digest: sha256:c51d9de741be087a31efe3173471d9ba550d52b6a25608e8ca87cd795864f7fb
Status: Image is up to date for griffithlab/pvactools:1.5.3
Executing MHC Class I predictions
Converting .bedpe to TSV
Completed
The TSV file is empty. Please check that the input bedpe file contains fusion entries.
------------------------------------------------------------
Sender: LSF System <lsf9@blade17-4-10.gsc.wustl.edu>
Subject: Job 8965175: <LYM001_tumor.pVACfuse> in cluster <lsfcluster9> Exited
Job <LYM001_tumor.pVACfuse> was submitted from host <blade18-2-13.gsc.wustl.edu> by user <cramirez> in cluster <lsfcluster9>.
Job was executed on host(s) <16*blade17-4-10.gsc.wustl.edu>, in queue <research-hpc>, as user <cramirez> in cluster <lsfcluster9>.
</gscuser/cramirez> was used as the home directory.
</gscmnt/gc2547/griffithlab/cramirez/follicular_lymphoma_neoepitope/RNA_seq_analysis/fusion_analysis> was used as the working directory.
Started at Thu Dec 12 13:59:26 2019
Results reported on Thu Dec 12 13:59:34 2019
Your job looked like:
------------------------------------------------------------
# LSBATCH: User input
pvacfuse run -e 8,9,10,11 --binding-threshold 1000 --allele-specific-binding-thresholds --n-threads 16 --downstream-sequence-length 1000 agfusion/ TUMOR HLA-A*01:01,HLA-A*02:01,HLA-B*08:01,HLA-B*35:01,HLA-C*04:01,HLA-C*07:01 MHCflurry MHCnuggetsI MHCnuggetsII NNalign NetMHC NetMHCIIpan NetMHCpan PickPocket SMM SMMPMBEC SMMalign LYM001_tumor.pVACfuse_output_dir/
------------------------------------------------------------
Exited with exit code 1.
Resource usage summary:
    CPU time :               0.11 sec.
    Total Requested Memory : 32000.00 MB
    Delta Memory :           -
    (Delta: the difference between Total Requested Memory and Max Memory.)
The output (if any) is above this job summary.
```

**Output File**
If your bug is related to the contents of an output file, please paste the output file here.

**Expected behavior**
I expect pVACfuse to recognize that I am giving it a directory of agfusion results.

**Comment by CodyRamirez** [comment]
Update: I was able to get pVACfuse to run successfully on a few set of patients. However, a large portion of patients are still failing with the above error even though fusion results exist.

**Comment by susannasiebert** [comment]
If it works for some I would just assume that there are no agfusion results processable by pVACfuse for those other samples. The warning message may simply be an oversight from the addition of agfusion.

**Comment by susannasiebert** [comment]
I'm looking at the `LYM001_tumor.AGFusion_outdir` directory and there are only two predicted fusions, none of which have a `_protein.fa` file. Therefore, there are no predicted fusions that can be processed by pVACfuse. I have noticed before that not all fusions will produce this file but it's not clear to me why that is. Either way, we need to improve the warning message to differentiate it from Integrate NEO.
