### ISSUE TITLE
pVACfuse complaining about peptide sequence length

### ISSUE THREAD

**Issue by yang-yangfeng** [griffithlab/pVACtools#48]
This warning pVACfuse seems a bit weird to me - but maybe I just don't understand what it's saying. 

Two separate runs with different inputs:

1)
input: `/gscmnt/gc2142/griffithlab/yafeng/cwl_toil_runs/unstranded/rna_only/fusion_antigen_out/fusions.bedpe.annot`

warning:
```Wildtype sequence length is shorter than desired peptide sequence length at position (10, -1, 32584304). Using wildtype sequence length (18) instead.```

2)
input: `/gscmnt/gc2142/griffithlab/yafeng/cwl_toil_runs/unstranded/paper_fusions/fusion_antigens_out/fusions.bedpe.annot`

warning:
```
Wildtype sequence length is shorter than desired peptide sequence length at position (1, -1, 167413114). Using wildtype sequence length (1) instead.
Wildtype sequence length is shorter than desired peptide sequence length at position (3, -1, 186787584). Using wildtype sequence length (7) instead.
Wildtype sequence length is shorter than desired peptide sequence length at position (3, -1, 186787584). Using wildtype sequence length (7) instead.
Wildtype sequence length is shorter than desired peptide sequence length at position (1, -1, 155717128). Using wildtype sequence length (8) instead.
Wildtype sequence length is shorter than desired peptide sequence length at position (20, -1, 45897040). Using wildtype sequence length (5) instead.
Wildtype sequence length is shorter than desired peptide sequence length at position (20, -1, 45897040). Using wildtype sequence length (5) instead.
Wildtype sequence length is shorter than desired peptide sequence length at position (16, -1, 67865229). Using wildtype sequence length (20) instead.
Wildtype sequence length is shorter than desired peptide sequence length at position (5, -1, 134910466). Using wildtype sequence length (9) instead.
```

**Comment by susannasiebert** [comment]
The full wildtype peptide is only 18 amino acids long, while your desired peptide length in your run `-l` (defaults to 21) is longer. So for this entry you won't have a peptide with the desired length of 21, but 18 instead.

**Comment by yang-yangfeng** [comment]
Ah I see, thanks.
