### ISSUE TITLE
Improve documentation of conceptual differences between output files. 

### ISSUE THREAD

**Issue by boyangzhao** [griffithlab/pVACtools#482]
Hi, I'm looking through the documentations and the results from my "pvacseq run", it's not quite clear to me the differences between .all_epitopes.tsv and .filtered.tsv. From my input vcf, it seems that the .all_epitopes.tsv consists of a shorter list of variants, which is filtered down further in the .filtered.tsv step. Does the .all_epitopes.tsv report a filtered variant from vcf based on pass-only, expn-val, cov and vaf cutoffs? And filtered.tsv further filters by binding? 

There are some other filtering criteria in "pvacseq run", and do they play a role in the all_epitopes.tsv step or the filtered.tsv step? Thanks!

**Comment by chrisamiller** [comment]
This doc page contains contains the diffs in the columns.  
https://pvactools.readthedocs.io/en/latest/pvacseq/output_files.html#all-epitopes-tsv-and-filtered-tsv-report-columns

The big picture difference is that the all_epitopes file contains all predictions for all peptides from all mutations. (note that only passing variants from the VCF will be considered if --pass-only is set).  The filtered/condensed file contains only a) sites that pass the additional pvacseq filters (expr/cov/vaf) and b) just the single "best" peptide for each mutation

You're right that a little more explanation might be useful in the docs (I'll leave this issue open until we find a place to document that more clearly)

**Comment by susannasiebert** [comment]
To add to this, the all_epitopes file also only contains predictions for the variants/transcripts that pVACseq supports, depending on the Consequence predicted by VEP. Currently pVACseq only supports missense_variant, inframe_insertion, inframe_deletion, frameshift_variant, and transcripts annotated as simply protein_altering. pVACseq skips transcripts that are also annotated as start_lost. A transcript would also be skipped if the resulting peptide sequence would be shorter than the longest epitope length.

**Comment by boyangzhao** [comment]
ah perfect! yes - it makes sense now, as some of my non-PASS and non-supported variants were excluded in the all_epitopes file. Thanks!
