### ISSUE TITLE
/bin/bash non-zero exit status 127

### ISSUE THREAD

**Issue by ktroule** [griffithlab/pVACtools#483]
* pvactools version: 1.5.4 (installed in conda environment with pip)
* Python version: 
* Operating System: Linux

**Describe the bug**
pvacseq fails when running it with the local IEDB database, when running it without the local db it works fine.

**To Reproduce**
What is the pVACtools command you ran? Please also attach any input files that can be used to reproduce this problem.

**Log Output**
```
/bin/bash: conda: command not found
Traceback (most recent call last):
  File "/home/miniconda3/envs/pVACtools/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/pVACtools/lib/python3.5/site-packages/tools/pvacseq/main.py", line 92, in main
    args[0].func.main(args[1])
  File "/home/miniconda3/envs/pVACtools/lib/python3.5/site-packages/tools/pvacseq/run.py", line 82, in main
    lib.call_iedb.setup_iedb_conda_env()
  File "/home/miniconda3/envs/pVACtools/lib/python3.5/site-packages/lib/call_iedb.py", line 13, in setup_iedb_conda_env
    version_check = run("/bin/bash -l -c \"conda activate pvactools_py27 && python -c \\\"import platform; print(platform.python_version())\\\"\"", stdout=PIPE, check=True, shell=True)
  File "/home/miniconda3/envs/pVACtools/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/bin/bash -l -c "conda activate pvactools_py27 && python -c \"import platform; print(platform.python_version())\""' returned non-zero exit status 127
```

**Output File**

**Expected behavior**
I've seen similar problems in this issue forum, but I've not been able to solve this issue.

I think its related to conda not being able to activate other enviroment 
Thanks

**Comment by susannasiebert** [comment]
The error seems to indicate that you don't have conda installed at all. The first step would be to ensure that you actually have conda installed correctly.

This might still be related to the new setup instructions for version >=4.4. Please see https://github.com/conda/conda/blob/master/CHANGELOG.md#440-2017-12-20 for more information on how to configure conda if you have version >=4.4 installed. Without knowing what version of conda you have and what things exactly you have tried, there isn't much additional help we can provide.

We generally recommend the use of our docker image for users having problems with conda in their environment.

**Comment by susannasiebert** [comment]
Closing since there has been no further activity on this ticket.
