### ISSUE TITLE
incorrect MT sequence for some fs insertions (?)

### ISSUE THREAD

**Issue by boyangzhao** [griffithlab/pVACtools#484]
* pvactools version: 1.5.1
* Python version: (in docker griffithlab/pvactool:1.5.1)
* Operating System:

**Describe the bug**
Is seems that for certain insertions, the pvacseq tool generates MT sequence incorrectly (?). I have a variant with the following characteristics (false/true positive variant aside):

NDUFC2
GRCh38 11:78073100 a frameshift insertion, -/A
HGVCc: c.207dup
	example transcript: ENST00000281031.4:c.207dup (amongst others)
HGVSp: p.Ala70CysfsTer9 (p.A70Cfs*9)
	example protein entry: ENSP00000281031.4:p.Ala70CysfsTer9 (amongst others)
Transcript: ENST00000281031 (among others)
Gene: NDUFC2
The mutation is labeled as -/X
Downstream protein: FCWILSCKT

The WT epitope is YITAFFFA
The MT epitope generated was YITAFFFF instead of YITAFFFC

I think the issue is that the Downstream protein (from VEP) starts with FC..., but so this was appended to the WT when there's an insertion. Although, the F in the Downstream refers to an unchanged aa. As HGVSp suggests, it is the A->C (the first changed aa), so the F in "Downstream" from VEP is not the inserted F, but in reference to the reference F. 

**More info**
I also retrieved the flanking sequences. 
Reference
ataatatccagcaaaaaaaaaggccgtaata
ITAFFFAGYY

In sample,
ataatatccagcaaaaaaaaaaggccgtaata
ITAFFFCWIL 

**Output File**
Attached is the pvacseq output with just this gene
[NDUFC2_example.xlsx](https://github.com/griffithlab/pVACtools/files/4002696/NDUFC2_example.xlsx)

**Expected behavior**
I expected the variant MT epitope to be YITAFFFC and not YITACFFFF

**Comment by susannasiebert** [comment]
Can you please attach a VCF with just the entry of this variant? This will make it easier for us to debug this issue.

**Comment by boyangzhao** [comment]
Yes, the input file as follows. I've also just ran it on pvactools:1.5.3 with the same results.
[NDUFC2_var.vcf.gz](https://github.com/griffithlab/pVACtools/files/4003012/NDUFC2_var.vcf.gz)

**Comment by susannasiebert** [comment]
I apologize for the delay on getting to work on this. Can you confirm whether all these cases have a mutation of `-/X`?

**Comment by boyangzhao** [comment]
yes all cases have mutation of `-/X`

**Comment by susannasiebert** [comment]
The latest version of pVACtools (1.5.5) should fix this issue. Please give it a try and let me know if it works.

**Comment by boyangzhao** [comment]
Hi Susan- I've tested using v1.5.5 and confirm that this issue is fixed! :)

**Comment by susannasiebert** [comment]
Wonderful. Closing this issue.
