### ISSUE TITLE
Allow for '.' in sample names

### ISSUE THREAD

**Issue by curlup** [griffithlab/pVACtools#490]
Currently pVACseq doesn't allow dots in `sample_name`s [as you can see here](https://github.com/griffithlab/pVACtools/blob/6ba980a3b0002a9175b9b74bd6f9b1652fb0511b/pvacseq/lib/main.py#L215), which is unfortunate for a project of ours.

Following this [brief discussion](https://github.com/griffithlab/pVACtools/commit/6ba980a3b0002a9175b9b74bd6f9b1652fb0511b#r37216781
) I want to open an issue to track everything related to that. 

As far as I dug into the code I think this description by @susannasiebert :
> We use the sample name in the filenames of downstream temporary files. However, we also encode other information in the file names using . as the separator. If the sample name also contains a . the naming of these temporary files now doesn't follow the expected pattern and we are unable to decode the temporary filenames properly.

catches the main reason for disallowing dots.

I think any code that relies on splitting those temp filenames by dots can be improved to allow for extra dots, as long as those will be only in the `sample_name` part. 

I would love to get feedback from somebody more familiar with the code base on whether there might be any other related nuances. 

If not we would like to attempt to improve the tools on that front.

**Comment by susannasiebert** [comment]
Another option would be to remove the sample name from the temporary files altogether. I assume we would want to keep them in the final output files to make them identifiable. This would be a more involved change, however.

@malachig @obigriffith @chrisamiller @jhundal What are your thoughts on this issue. What restrictions do we have when it comes to naming of the report files and temporary files to ensure that they are easily usable/identifiable by the clinicians? Would it hurt to remove the sample name from the temporary files?

@curlup , the link you provided is on a very outdated version of the repository. Please ensure that you work off of the latest version of the staging branch. The check you posted as been moved [here](https://github.com/griffithlab/pVACtools/blob/staging/tools/pvacseq/run.py#L66). Similar checks are also performed in the pVACfuse and pVACbind modules. Since those modules share a lot of code in their pipelines, you will want to ensure that all of them work with this change. You could start by removing this check from the above file and running pVACseq with a sample name that has a `.` in it to see what all breaks.

**Comment by curlup** [comment]
Thanks @susannasiebert !
We could probably approach it from the angle you're suggesting - removing `sample_name`s from temp file names. 
Whichever you think the best.
I'll wait for other comments too.

**Comment by chrisamiller** [comment]
Couple of thoughts:

- I haven't dug into that section of code, but if the software knows what the sample name is, my feeling is that it should be able use that to parse created file names with or without periods in the sample. (it gets a little more complex, but should be doable)

- I could care less what the temp file names are, as long as pvactools is only dumping out single samples into single directories, so dropping sample names there seems fine. It's probably a good idea to continue prepending the sample names to the final outputs, though, as those are the ones that would be passed around most often.

**Comment by curlup** [comment]
I wanted to start on this, I would appreciate any help setting up a development environment, because I'm having trouble making `pysam=0.9.0` (`pysam==0.9.0 is required by {'isovar'}`) working. 
What's your dev setup? 
Thanks.

**Comment by susannasiebert** [comment]
I use a python 3.5 conda environment on my MacBook. Here is my current `pip list` dump:
```
$ pip list
Package                Version   Location                                           
---------------------- --------- ---------------------------------------------------
absl-py                0.8.0     
appdirs                1.4.3     
argh                   0.26.2    
astor                  0.8.0     
astropy                3.2.2     
biopython              1.74      
bleach                 3.1.0     
bokeh                  0.13.0    
certifi                2018.8.24 
chardet                3.0.4     
Click                  7.0       
clickclick             1.2.2     
connexion              1.4.2     
datacache              1.1.5     
decorator              4.4.0     
docutils               0.15.2    
Flask                  1.1.1     
Flask-Cors             3.0.8     
future                 0.17.1    
gast                   0.2.2     
google-pasta           0.1.7     
grpcio                 1.24.1    
gtfparse               1.2.0     
h5py                   2.10.0    
html5lib               0.9999999 
idna                   2.8       
inflection             0.3.1     
isovar                 0.9.0     
itsdangerous           1.1.0     
Jinja2                 2.10.3    
joblib                 0.14.0    
jsonschema             2.6.0     
Keras                  2.2.5     
Keras-Applications     1.0.8     
Keras-Preprocessing    1.1.0     
Markdown               3.1.1     
MarkupSafe             1.1.1     
memoized-property      1.0.3     
mhcflurry              1.2.2     
mhcnames               0.4.8     
mhcnuggets             2.2       
mhctools               1.6.22    
mock                   3.0.5     
networkx               2.3       
np-utils               0.5.11.1  
numpy                  1.17.2    
opt-einsum             3.1.0     
packaging              19.2      
pandas                 0.25.2    
pathtools              0.1.2     
pdfkit                 0.6.1     
Pillow                 6.2.0     
pip                    18.0      
pkginfo                1.5.0.1   
progressbar33          2.4       
protobuf               3.10.0    
pvactools              1.5.5            
py-postgresql          1.2.1     
pyensembl              1.8.3     
Pygments               2.4.2     
pymp-pypi              0.4.2     
pypandoc               1.4       
pyparsing              2.4.2     
pysam                  0.9.0     
python-dateutil        2.8.0     
pytz                   2019.3    
PyVCF                  0.6.8     
PyYAML                 5.1.2     
readme-renderer        24.0      
requests               2.22.0    
requests-toolbelt      0.9.1     
roman                  3.2       
scikit-learn           0.21.3    
scipy                  1.3.1     
sercol                 0.1.4     
serializable           0.1.1     
setuptools             41.4.0    
shellinford            0.4.1     
simanneal              0.5.0     
simplejson             3.16.0    
six                    1.12.0    
swagger-spec-validator 2.1.0     
tensorboard            1.14.0    
tensorflow             1.14.0    
tensorflow-estimator   1.14.0    
termcolor              1.1.0     
testfixtures           6.10.0    
tinytimer              0.0.0     
tornado                5.0.2     
tqdm                   4.36.1    
twine                  1.15.0    
typechecks             0.1.0     
typing                 3.7.4.1   
urllib3                1.25.6    
varcode                1.0.0      
vaxrank                1.0.2       
vcfpy                  0.12.1    
watchdog               0.9.0     
webencodings           0.5.1     
Werkzeug               0.16.0    
wget                   3.2       
wheel                  0.32.0    
wrapt                  1.11.2    
xlrd                   1.2.0     
XlsxWriter             1.2.1     
xvfbwrapper            0.2.9     
```
You might need an older version of tensorflow depending on your hardware. These requirements might also differ if you run a newer Python version.

**Comment by curlup** [comment]
@susannasiebert 
I produced a very basic fix for the issue - lease see the first PR linked above (#504).
I also tried to modify existing test in order to show that the fix works - that's in a separate commit, which I included in a separate PR - #505 - because I was not sure that's the way you'd want me to test it.

If have any suggestions on what I should change in the way I approached this - please let me know, I'm happy to work towards you target implementation.

Thanks

**Comment by susannasiebert** [comment]
@curlup thank you for those PRs. I will review them first thing Monday.

**Comment by malachig** [comment]
Thanks @curlup, always great to get contributions from the community!

**Comment by curlup** [comment]
Any comments?

**Comment by susannasiebert** [comment]
@curlup I made a PR (https://github.com/CIMAC-CIDC/pVACtools/pull/1 ) on top of your pull request branch with some additional tests. Once you merge that PR We’ll be good to merge #505

**Comment by curlup** [comment]
Done!

**Comment by susannasiebert** [comment]
I merged your pull request into the staging branch. I will be closing this issue since development has been finished. This feature will be part of the next major release (2.0) and has been added to the 2.0 milestone.
