### ISSUE TITLE
Problems annotating with VEP

### ISSUE THREAD

**Issue by lbdarragh** [griffithlab/pVACtools#491]
Hello, 

I am having issues getting the correct file for pVACseq input. I spliced out individuals of interest using the online VEP GRCh37 splice tool which outputted a VCF file. I then ran that file through VEP with the added Wildtype.pm plugin addition and it seemed to have worked. When I look at the file that was outputted, there is no protein single-letter amino acid sequence as in the example input file provided. I believe that the plugins are working, but I was wondering if the spliced VCF file that I started with lacked sufficient information to annotate the protein AA sequence into the VEP output VCF file? I included a zipped version of the file that I have been running through the code below. 
[B27_Con_2.gz](https://github.com/griffithlab/pVACtools/files/4183129/B27_Con_2.gz)

./vep --cache --offline --format vcf --vcf \
--input_file ~/vep_data/B27_pvacseq/B27_Input/B27_Controls/B27_Con_2.vcf \
--output_file ~/vep_data/B27_pvacseq/B27_Output/B27_Controls/B27_Con_2.vcf \
--force_overwrite \
--symbol \
--terms SO --tsl \
--dir_cache ~/.vep/ \
--assembly GRCh37 \
--hgvs --fasta ~/.vep/homo_sapiens/99_GRCh37/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa \
--plugin Downstream \
--plugin Wildtype 

Thank you!
Laurel

**Comment by susannasiebert** [comment]
The Wildtype plugin is a custom plugin we wrote and, unfortunately, not supported by online VEP. You will need to use the standalone tool either by installing it (instructions can be found [here](https://pvactools.readthedocs.io/en/latest/pvacseq/input_file_prep/vep.html#installing-vep) locally or by using a Docker container that has VEP installed.

**Comment by susannasiebert** [comment]
Unless I'm misunderstanding and you did use standalone VEP. If that is the case you can check the `CSQ` header in your output VCF and see if it contains a `WildtypeProtein` key. If that key is there, then the Wildtype plugin ran; otherwise it didn't

**Comment by lbdarragh** [comment]
I did use the standalone VEP. I do have the WildtypeProtein key in my output file. I just don't have any single AA sequence information in the output file. I was wondering if that meant it was an input file issue? Like the file I downloaded and spliced from the 1000 genomes project didn't contain enough information or something? I am just not sure where I went wrong.

**Comment by susannasiebert** [comment]
Could you please share your annotated file with use?

**Comment by lbdarragh** [comment]
Yes. Thank you!
[Experiment_Output.vcf.zip](https://github.com/griffithlab/pVACtools/files/4183610/Experiment_Output.vcf.zip)

**Comment by susannasiebert** [comment]
This is indeed odd. I see that VEP predicted the affected transcript, so I would expect the WildtypeProtein field to reflect the transcript protein sequence. However, these variants aren't processable by pVACseq either way because the predicted consequences from VEP are things like `non_coding_transcript_exon_variant`, `non_coding_transcript_variant`, `upstream_gene_variant` etc. pVACseq only supports `missense_variant`, `inframe_insertion`, `inframe_deletion`, `frameshift_variant`, and `protein_altering_variant`. This might also be the reason for the WildtypeProtein field being empty.

**Comment by lbdarragh** [comment]
Do you have any recommendations for how I should proceed? Thank you for your help!

**Comment by susannasiebert** [comment]
I'm not sure if there is anything you can do in this situation. pVACseq is simply not designed to handle the mutations in your VCF since they don't affect the protein sequence (as far as I understand it; I'm not a bioinformatician). @chrisamiller do you have any advice?

**Comment by chrisamiller** [comment]
If VEP does not annotate a mutation as protein-altering, then you should not get amino acid predictions from VEP, or peptide predictions from pVACtools. If this sounds wrong, and you expect these mutations to have protein-altering consequences, then you need to check your inputs to VEP, including genome build, etc.

**Comment by lbdarragh** [comment]
Great! Thank you both.
