### ISSUE TITLE
additional columns output

### ISSUE THREAD

**Issue by MatDal** [griffithlab/pVACtools#498]
Hello,

which parameter I have to use to return the additional columns in the output?
 
![image](https://user-images.githubusercontent.com/28292208/75032611-3befd100-54a9-11ea-91fb-f592f2850744.png)

Thanks
Best

**Comment by susannasiebert** [comment]
Cleavage site predictions are enabled by picking a `--net-chop-method` (either `cterm` or `20s`). Stability predictions are enabled by using the `--netmhc-stab ` flag.

**Comment by MatDal** [comment]
Thanks!!
