### ISSUE TITLE
Can pvcaseq process many sample in one time?

### ISSUE THREAD

**Issue by wt12318** [griffithlab/pVACtools#499]
Hello,
I have read the docs for `pvacseq`, and I noticed that `pvacseq` can accept multi-sample VCF as input.
I want to know can it take multiple sample name as input in the argument `sample_name`
Thanks

**Comment by susannasiebert** [comment]
pVACseq only supports processing a single sample at a time. In a multi-sample VCF the sample_name is used to identify the variants to process (only variants called in the sample are being processed).

**Comment by wt12318** [comment]
Thanks a lot
