### ISSUE TITLE
Problem with "X" aa in fasta input

### ISSUE THREAD

**Issue by MatDal** [griffithlab/pVACtools#500]
Hello,
I have protein sequences that in some cases contain the character "X" as an amino acid after mapping with Diamond. If I use sequences containing "X" as input, pcavbind returns this error:

![image](https://user-images.githubusercontent.com/28292208/75120340-5da8ae00-568b-11ea-9caa-7d25a7ecc75a.png)

Is it possible to use this type of sequence as input? How can I solve this problem?

Thanks

**Comment by susannasiebert** [comment]
@MatDal Unfortunately, pVACbind doesn't appear to handle sequences containing `X` yet, however, it totally should. I will make a bugfix for it.

**Comment by susannasiebert** [comment]
This should be solved in the latest version 1.5.6. I'm resolving this issue but please do reopen it if the issue persists when running with the newest version.
