### ISSUE TITLE
The TSV file is empty. Please check that the input VCF contains missense, inframe indel, or frameshift mutations

### ISSUE THREAD

**Issue by wt12318** [griffithlab/pVACtools#502]
hello,
sorry to bother you again.
I read the `docs`, it said `None of the variants in the VCF file are supported by pVACseq.`. But I checked my vcf file, it  contains `missense` in the `CSQ` field. Here is my vcf file. I got this file by `head -1000` from a big vcf file.
[test.annoated.zip](https://github.com/griffithlab/pVACtools/files/4248881/test.annoated.zip)
thanks

**Comment by susannasiebert** [comment]
pVACseq was conceived as a tool for clinical application where we expect to have a somatic input VCF with one tumor and one normal sample for the same patient. pVACseq then only processes variants called in the tumor sample (i.e. 0/1 genotype). However, this approach sometimes doesn't work well for non-clinical applications like the one you appear to want to use pVACseq for. 

It looks like this is a merged VCF from multiple TCGA samples of some sort. As a result of this merging, the samples in your VCF don't have any variants that are actually called (they only have `.` in the GT field). I would expect this VCF to still have GT information to indicate which variants are called in which sample unless this VCF contains only variants that were called in every single sample.

If your VCF only contains variants that overlap between all of your TCGA samples and you simply want to process all variants in this VCF, you can add an additional (dummy) sample to this VCF using the `vcf-genotype-annotator` from our VAtools convenience tools suite (https://vatools.readthedocs.io/en/latest/vcf_genotype_annotator.html). When you run this tool you specify which GT value to use (you'll want `0/1`) and it will append another sample to your VCF with that genotype. You can then use the new dummy sample name when running pVACseq and it will process all the variants in the VCF.

However, if your VCF contains all variants for all these TCGA samples, we would expect the GT field to show which variant was called for which sample. If that is the case you will want to retrace the steps you took to create this VCF and figure out why it is missing the GT information.

**Comment by susannasiebert** [comment]
I assume that my suggestion resolved you problem. I will close this issue but feel free to reopen if you have any other questions related to this issue.

**Comment by Admera2020** [comment]
Adding questions directly here as the discussion is quite relevant. I am using Strelka2 as a somatic variant caller, which doesn't add GT field at all. Reason explained here: https://github.com/Illumina/strelka/issues/16

In my case "vcf-genotype-annotator" doesn't work, likely because GT is completely missing from the header. It wouldn't be too hard to add a fake "0/1" GT myself, however, I am concern about the effect of adding the GT field on downstream steps.  
So curious to know if GT field is simply used to filter out variants at the first step or may have another impact as well? 

Best, 
Nihir

**Comment by susannasiebert** [comment]
I'm curious to dig more into why the vcf-genotype-annotator doesn't work for you. It is designed for VCFs that don't have a GT field and header at all. Is the problem that you want to add the GT field to an existing sample? That is not currently supported (but on the to-do list; see https://github.com/griffithlab/VAtools/issues/37). Can you just add a new dummy sample to your VCF?

pVACseq attempts to support a variety of use cases, some of which can result in complex VCF entries. The GT field is used to determine the variants that were actually called in a particular sample, e.g. for merged multi-sample VCFs. It is also used to determine the VAF which requires identifying the alt allele that was called for that sample. Depending on how you ran your pipeline you might end up with multiple alt alleles in a VCF entry, which we attempt to handle (although it is recommend to split multi-alt entries, e.g. using `vt decompose`).

**Comment by Admera2020** [comment]
Thanks for quick response 
No adding a dummy sample to VCF is no issue at all.  Below is the error I am getting, when I ran genotype annotator 
Command `vcf-genotype-annotator strelka2.dna.VEP.Final.vcf Tumor2 "0/1"`

```
Traceback (most recent call last):
  File "/home/miniconda3/envs/pvactools/bin/vcf-genotype-annotator", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/pvactools/lib/python3.7/site-packages/vatools/vcf_genotype_annotator.py", line 67, in main
    entry.FORMAT = entry.FORMAT.appened('GT')
AttributeError: 'list' object has no attribute 'appened'
```
Adding a minimal VCF here
[testVCF.txt](https://github.com/griffithlab/pVACtools/files/4955770/testVCF.txt)
 for troubleshooting.

Thanks for the explanation and I do indeed use vt decompose and thus have no multi-allelic sites. 

Best, 
Nihir

**Comment by susannasiebert** [comment]
Oh, that's an actual bug with the tool. Looks like a misspelling in that method call (`appened` instead of `append`). Do you mind making a bug report in the VAtools repository with that error?

**Comment by Admera2020** [comment]
Sounds good, reported https://github.com/griffithlab/VAtools/issues/39
