### ISSUE TITLE
Add option to run reference proteome similarity feature with standalone Blast

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVACtools#516]
Right now we use bippython's blast wrapper for the reference proteome search. This is pretty slow. We should add the ability to use a standalone Blast installation. We would then also install Blast in our Docker container to use by default.

**Comment by MatDal** [comment]
You can try also with Diamond. Is very fast.

**Comment by malachig** [comment]
Thanks for the suggestion.  I assume this is what you are referring to?
https://github.com/bbuchfink/diamond

Has anyone created any Python interfaces to it?

**Comment by MatDal** [comment]
Yes. It is very fast and the performances are comparable with Blast.
For the Python interfaces for Diamond I don't know, sorry.
