### ISSUE TITLE
agfusion version 1.252 output .csv not .txt

### ISSUE THREAD

**Issue by plsysu** [griffithlab/pVACtools#530]
https://github.com/griffithlab/pVACtools/blob/a032e72ee952c515594bda0c11c111e2961172c2/lib/input_file_converter.py#L479

The latest agfusion version 1.252 output csv format file and pvacfuse only read .txt file. Would you like to fix this issue ?

Thanks!

**Comment by susannasiebert** [comment]
Thank you for bringing this to our attention. I have added this issue to the 2.0 development milestone.
