### ISSUE TITLE
The default length do not work wit NetMHCpanII

### ISSUE THREAD

**Issue by riederd** [griffithlab/pVACtools#539]
https://github.com/griffithlab/pVACtools/blob/e6fbd8dccdbd2de4042d2d413c30aebbc7f8995d/lib/run_argument_parser.py#L48

see pVACtools docker /opt/iedb/mhc_ii/mhc_II_binding.py line 246
The minimum length is 15.

**Comment by riederd** [comment]
...furthermore mhc_II_binding.py is not using the provided lengths at all, it always uses 15.
sys.argv[4] is not parsed by that script, so netMHCIIpan is run with the default length of 15. See NetMHCIIpan-3.1.pl line 134.

**Comment by riederd** [comment]
....and mhcii_predictor.py from IEDB tools imported by mhc_II_binding.py is only working with length 15.

**Comment by susannasiebert** [comment]
Can you please check which version of the IEDB class II package you are one. I ran into this problem with an older version of the IEDB package we are using in our current Docker containers. Since this is a new feature from IEDB it doesn't work with older IEDB versions. I had to upgrade to class II package to version 2.22.3 to get this new feature.

**Comment by susannasiebert** [comment]
I will also confirm on my end whether this feature works for NetMHCpanII specifically in the 2.22.3 package.

**Comment by susannasiebert** [comment]
I confirmed that in a container with IEDB class ii 2.22.3 predictions with different epitope lengths for NetMHCpanII work as expected. My test command was:

**Comment by riederd** [comment]
I'm on 2.17.6 downloaded from https://downloads.iedb.org/tools/mhcii/2.17.6/IEDB_MHC_II-2.17.6.tar.gz as indicated in your docker file from https://github.com/griffithlab/docker-pvactools/blob/master/Dockerfile

**Comment by susannasiebert** [comment]
yes, the 2.17.6 version of IEDB class II unfortunately does not have the epitope length feature. You will need to either make a new docker container that has the newest IEDB class II version or you are welcome to try out `susannakiwala/pvactools:2.0.0-alpha.2` which has that version installed. It also already has to correct version of the pVACtools code.

**Comment by riederd** [comment]
Oh, great.
I'm using a slightly extended image that also includes the tools to do readcount annotations and so on, so I have to rebuild it anyway.

**Comment by riederd** [comment]
I just rebuild my singularity image and I can confirm it works nicely with the ISDB version 2.22.3
Thanks

**Comment by susannasiebert** [comment]
Wonderful. I assume we can close this issue then?

**Comment by riederd** [comment]
sure, thanks again
