### ISSUE TITLE
Couldn't detect frameshift mutations in VCF

### ISSUE THREAD

**Issue by wenweiliang** [griffithlab/pVACtools#547]
* pvactools version: docker
* Python version: python 3.6
* Operating System: Linux

**Describe the bug**
We annotated self-made VCF with VEP( and with Downstream and Wildtype plugins), but pvactools failed to detect frameshift mutations in the annotated VCF. 
The VEP-annotated VCF is attached
[test3.vcf.gz](https://github.com/griffithlab/pVACtools/files/4541012/test3.vcf.gz)

**To Reproduce**
```
docker run -v /path/2/data:/data -it griffithlab/pvactools
cd /data
pvacseq run test3.vcf Test HLA-A*01:01,HLA-A*30:01,HLA-B*07:02,HLA-B*13:02,HLA-C*06:02,HLA-C*07:02 NetMHCpan output -e 8,9,10 --iedb-install-directory /opt/iedb
```

**Log Output**
```
Executing MHC Class I predictions
Converting .vcf to TSV
Completed
The TSV file is empty. Please check that the input VCF contains missense, inframe indel, or frameshift mutations.
```

**Output File**
Empty TSV with header only.

**Expected behavior**
Perform prediction based on frameshift mutations

**Comment by susannasiebert** [comment]
pVACseq requires that your VCF indicates which variants are called in your sample using the GT field (`0/1` GT). Your VCF is missing the GT field. You can do this using the vcf-genotype-annotator tool of the `vatools` package (https://vatools.readthedocs.io/en/latest/vcf_genotype_annotator.html). However, that tool only works for adding a new sample. If you want to use the NORMA sample in your VCF you will need to add the GT field manually.

**Comment by wenweiliang** [comment]
It works! Thanks!
