### ISSUE TITLE
Add a section to the pVACseq documentation describing adding GT field

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVACtools#548]
pVACseq requires the GT field to indicate which samples are called. We need a section in the input file prep for those users that don't have clinical VCFs and are instead trying to process VCFs that don't have a GT field.

**Comment by susannasiebert** [comment]
We should also add this to the FAQ

**Comment by Chitanda-Satou** [comment]
Thanks @susannasiebert . I found the VCFs of Strelka2 do not contain "GT" information and cannot be used for pVACseq.
