### ISSUE TITLE
Mhcflurry dependency problems

### ISSUE THREAD

**Issue by Stikus** [griffithlab/pVACtools#550]
* pvactools version: 1.5.8
* Python version: 3.7
* Operating System: Ubuntu 18.04

Hello @susannasiebert 
For now, we having dependency problems with `mhcflurry 1.6.0`.
Reason:

- pVACtools:

https://github.com/griffithlab/pVACtools/blob/master/setup.py
```
'mhcflurry',
...
'vaxrank==1.0.2',
```

- vaxrank 1.0.2

https://github.com/openvax/vaxrank/blob/aad68224461553d79ffdb72c794a71cd3f8c855d/setup.py
```
'mhctools>=1.5.0'
```
And even current release: https://github.com/openvax/vaxrank/blob/master/setup.py
```
'mhctools>=1.5.0'
```

- mhctools
https://github.com/openvax/mhctools/blob/master/setup.py
```
'mhcflurry>=1.2.2,<1.5.0',
```

I submitted [issue](https://github.com/openvax/mhctools/issues/150) in mhctools, but maybe you have any info about it?

**Comment by susannasiebert** [comment]
I agree that mhctools needs to update their pinned version of mhcfurry. I don't think unpinning vaxrank will solve that (or anything we can do on our end). However, I haven't seen any indication that mhctools will not work with the new mhcflurry 1.6.0. Are you seeing any actual errors during install or just incompatibility warning messages? If it's the latter, I think you can ignore them. If it's the former, you might be able to get around them by installing vaxrank, mhcflurry, and mhctools manually first.

**Comment by Stikus** [comment]
They removed upper limit in https://github.com/openvax/mhctools/pull/151
So I'm closing this issue.
