### ISSUE TITLE
"pvacfuse generate_protein_fasta -h" command not working 

### ISSUE THREAD

**Issue by ShahiRB** [griffithlab/pVACtools#557]
Hi Susanna,

pVACtools 1.5.8

1. I wonder why "pvacfuse generate_protein_fasta -h" command is emitting an error like "Error: No command specified". The documentation is also broken/not clear.

2. Isn't the command similar to pvacseq, except for the path for the fusion variants( AGFusion)

Regards,
Rajendra

**Comment by susannasiebert** [comment]
I'm sorry you're running into an error using this command. I will look into it!

On the surface, the commands are similar but under the hood they need to execute different code to process AGfusion files vs a VCF. So you couldn't use the `pvacfuse generate_protein_fasta` command.

**Comment by ShahiRB** [comment]
When is the next hotfix release, please :)

**Comment by susannasiebert** [comment]
There are a few other bugs that need addressing but I'm hoping for a new release either later this week or next.

**Comment by susannasiebert** [comment]
This bug has been fixed in version 1.5.9.
