### ISSUE TITLE
pVACvector visualization is a bit messy

### ISSUE THREAD

**Issue by yang-yangfeng** [griffithlab/pVACtools#56]
Low priority, but on this image at least, the binding affinity text overlaps with the vector sketch itself.

https://gscweb.gsc.wustl.edu/gscmnt/gc2142/griffithlab/yafeng/cwl_toil_runs/pvacseq_output/hcc1395_vector_chosen/vector.jpg

**Comment by susannasiebert** [comment]
The overlap looks to be very slight to me. I wonder if it displays differently on your machine than mine? I wonder if it would make sense to round these numbers? Maybe that would help with this issue.

**Comment by yang-yangfeng** [comment]
hmm I think maybe I was looking at it in the xQuartz window when I made this issue. I also see very slight overlap when using the link above and viewing in chrome. Perhaps not an issue then. Although rounding seems like it would clean things up regardless.

**Comment by susannasiebert** [comment]
Any preference as to how many digits to round to?
