### ISSUE TITLE
MHCflurry pre-trained model reloaded multiple times

### ISSUE THREAD

**Issue by arglog** [griffithlab/pVACtools#563]
The [current implementation](https://github.com/griffithlab/pVACtools/blob/master/lib/prediction_class.py#L249) of MHCflurry is through the binary executable `mhcflurry-predict`. At a high level, pVACtools calls MHCflurry to predict sequences in a FASTA like this
```python
for record in SeqIO.parse(input_file, "fasta"):
    call mhcflurry-predict to predict record
```
Every calling of `mhcflurry-predict` will first load the pre-trained Tensorflow model and then make predictions. As the calling is inside a for loop, the Tensorflow model will be repeatedly loaded for several times (= the number of sequences in the FASTA). In my local tests. the repeat loading of the model is a huge overhead, which made the MHCflurry (though running on GPU) hundreds of times slower than the (API-query based) NetMHC tools.

Can this be improved? For example, we can pre-process the FASTA file to collect all peptides and call `mhcflurry-predict` only once, and then do a post-processing to map the prediction to each sequence.

**Comment by susannasiebert** [comment]
This is a good suggestion. I will provisionally add this issue to the 2.0 milestone.
