### ISSUE TITLE
RNAseq depth is not annotated

### ISSUE THREAD

**Issue by Admera2020** [griffithlab/pVACtools#569]
Hello, 

I am running the latest version of the pVACtools and followed the direction from [here  ](https://pvactools.readthedocs.io/en/latest/pvacseq/input_file_prep/readcounts.html) to add Tumor RNA Coverage to the VCF file. I managed to complete the step. However, when I ran pVACseq  all the entries in the  Tumor RNA Depth and VAF are "NA".

Here is the minimal example,

`chr16   166053  .       G       C       .       PASS    AS_FilterStatus=SITE;AS_SB_TABLE=48%2C36|3%2C4;DP=92;ECNT=1;GERMQ=93;MBQ=20,20;MFRL=238,199;MMQ=60,60;MPOS=65;NALOD=1.32;NLOD=5.97;POPAF=6.0;ROQ=59.0;TLOD=14.93;CSQ=C|missense_variant|MODERATE|HBM|ENSG00000206177|Transcript|ENST00000356815.4|protein_coding|1/3||ENST00000356815.4%3Ac.56G>C|ENSP00000349270.3%3Ap.Gly19Ala|76|56|19|G/A|gGc/gCc|||1||HGNC|HGNC%3A4826|1||||MLSAQERAQIAQVWDLIAGHEAQFGAELLLRLFTVYPSTKVYFPHLSACQDATQLLSHGQRMLAAVGAAVQHVDNLRAALSPLADLHALVLRVDPANFPLLIQCFHVVLASHLQDEFTVQMQAAWDKFLTGVAVVLTEKYR       GT:AD:AF:DP:F1R2:F2R1:SB:RDP:RAF:RAD    0/1:61,7:0.12:68:24,4:37,3:37,24,3,4:1873:0.00000:1871,0 0/0:23,0:0.046:23:11,0:11,0:11,12,0,0:.:.:.`

```

Chromosome | chr16
-- | --
Start | 166052
Stop | 166053
Reference | G
Variant | C
Transcript | ENST00000356815.4
Transcript Support Level | 1
Ensembl Gene ID | ENSG00000206177
Variant Type | missense
Mutation | G/A
Protein Position | 19
Gene Name | HBM
HGVSc | ENST00000356815.4:c.56G>C
HGVSp | ENSP00000349270.3:p.Gly19Ala
HLA Allele | HLA-A*02:05
Peptide Length | 9
Sub-peptide Position | 3
Mutation Position | 9
MT Epitope Seq | AQVWDLIAA
WT Epitope Seq | AQVWDLIAG
Best MT Score Method | NetMHCpan
Best MT Score | 38.7
Corresponding WT Score | 1780.7
Corresponding Fold Change | 46.013
Tumor DNA Depth | 68
Tumor DNA VAF | 0.12
Tumor RNA Depth | NA
Tumor RNA VAF | NA
Normal Depth | 23
Normal VAF | 0.046
```

As you can see the DNA data is clearly annotated but RNA data is always "NA".

Best, 
Nihir

**Comment by susannasiebert** [comment]
Unfortunately, I'm unable to reproduce this error. Did you by any chance previously run a VCF without the Tumor RNA annotations in the same output directory? If so, pVACseq does not reprocess the updated VCF. Please try again with an empty output directory and see if that resolves the problem.

**Comment by Admera2020** [comment]
OK, thank you for your quick response. The wrong VCF was indeed the issue.
