### ISSUE TITLE
"pvacfuse generate_protein_fasta" generates 27-mer peptide fasta with truncated epitope

### ISSUE THREAD

**Issue by ShahiRB** [griffithlab/pVACtools#578]
Hi Susanna,

pvactools-1.5.9 ;

I have two epitopes for  ARRDC3-ADAM10 gene fusion due to different ADAM10 gene transcripts.

When I tried to generate 27-mer fasta for both of them, for one (**LQWENFTPK**/ENST00000265138-ENST00000402627) I got correct peptide (APVSACDDFERALCL**QWENFTPK**RNLL) whereas for other (**SLSHYFCSR**/ENST00000265138-ENST00000260408) the peptide generated is truncated (APVSACDDFERALLWVSCTSQ**SLSHYF**) eventually slicing a part of the epitope.

For your reference AGFusion/1.2 generated fasta files for both of the fusions are mentioned below:

\>ENSP00000265138-ENSP00000386056 length=394, kD: 44.293930300000056, transcripts: ENST00000265138-ENST00000402627, genes: ARRDC3-ADAM10, effect: out-of-frame
MVLGKVKSLTISFDCLNDSNVPVYSSGDTVSGRVNLEVTGEIRVKSLKIHARGHAKVRWT
ESRNAGSNTAYTQNYTEEVEYFNHKDILIGHERDDDNSEEGFHTIHSGRHEYAFSFELPQ
TPLATSFEGRHGSVRYWVKAELHRPWLLPVKLKKEFTVFEHIDINTPSLLSPQAGTKEKT
LCCWFCTSGPISLSAKIERKGYTPGESIQIFAEIENCSSRMVVPKAAIYQTQAFYAKGKM
KEVKQLVANLRGESLSSGKTETWNGKLLKIPPVSPSILDCSIIRVEYSLMVYVDIPGAMD
LFLNLPLVIGTIPLHPFGSRTSSVSSQCSMNMNWLSLSLPERPEAPPSYAEVVTEEQRRN
NLAPVSACDDFERAL*C**LQWENFTPK**RNLLSHHLQ

\>ENSP00000265138-ENSP00000260408 length=395, kD: 44.30788730000008, transcripts: ENST00000265138-ENST00000260408, genes: ARRDC3-ADAM10, effect: out-of-frame
MVLGKVKSLTISFDCLNDSNVPVYSSGDTVSGRVNLEVTGEIRVKSLKIHARGHAKVRWT
ESRNAGSNTAYTQNYTEEVEYFNHKDILIGHERDDDNSEEGFHTIHSGRHEYAFSFELPQ
TPLATSFEGRHGSVRYWVKAELHRPWLLPVKLKKEFTVFEHIDINTPSLLSPQAGTKEKT
LCCWFCTSGPISLSAKIERKGYTPGESIQIFAEIENCSSRMVVPKAAIYQTQAFYAKGKM
KEVKQLVANLRGESLSSGKTETWNGKLLKIPPVSPSILDCSIIRVEYSLMVYVDIPGAMD
LFLNLPLVIGTIPLHPFGSRTSSVSSQCSMNMNWLSLSLPERPEAPPSYAEVVTEEQRRN
NLAPVSACDDFERAL*LWVSCTSQ**SLSHYFCSR**SWT

Regards,
Rajendra

**Comment by ShahiRB** [comment]
What I also noticed is that when you give argument for --input-tsv option in "pvacfuse generate_protein_fasta" the output fasta is not generated (i.e. file with 0 size is generated) . 

Command given:
pvacfuse generate_protein_fasta \
--input-tsv foo.filtered.tsv \
/out/dir \
27 \
foo.fasta

**Comment by susannasiebert** [comment]
Hi Rajendra,

Can you please attach the full AGfusion result directory as well as the foo.filtered.tsv input file for further debugging.

Thanks,
Susanna

**Comment by ShahiRB** [comment]
Hi Susanna,

Please find the files you have asked for.

[annotate_agfusion.tar.gz](https://github.com/griffithlab/pVACtools/files/5062914/annotate_agfusion.tar.gz)
[foo.filtered.tsv.tar.gz](https://github.com/griffithlab/pVACtools/files/5062917/foo.filtered.tsv.tar.gz)

Regards,
Rajendra

**Comment by susannasiebert** [comment]
Unfortunately, I'm unable to reproduce the issue you are seeing with the truncated peptide sequence. I ran the following command with your input AGfusion directory:
```
pvacfuse generate_protein_fasta ~/Downloads/annotate_agfusion/ 27 pvacfuse.fasta
```
For `ENST00000265138-ENST00000260408` I see the following result:
<pre>
>5.ARRDC3-ADAM10.frameshift_fusion.375
APVSACDDFERALLWVSCTSQ<b>SLSHYFCSRSWT</b>
</pre>
I have attached the result fasta: [pvacfuse.fasta.zip](https://github.com/griffithlab/pVACtools/files/5084837/pvacfuse.fasta.zip)

Do you get the same header (`>5.ARRDC3-ADAM10.frameshift_fusion.375`) for this protein sequence?

In regards to your second issue, I was able to reproduce the issue you are seeing when using the `--input-tsv` argument and a bugfix PR is currently open (#582).

**Comment by ShahiRB** [comment]
Hi Susanna,

I am sorry, I forgot to mention that it was in the case when we choose "--downstream-sequence-length 14 " ;  which is logical as we limit downstream peptide length to 14. This suggests us that we have to be careful while opting downstream peptide length :)

KR
Rajendra

**Comment by susannasiebert** [comment]
Aah yes, that explains it. You will want to use the same downstream sequence length here as you did in your pVACseq command to ensure that you get the same peptide sequences.
