### ISSUE TITLE
Error when using local installation of IEDB

### ISSUE THREAD

**Issue by nickhir** [griffithlab/pVACtools#579]
Hi everybody,

I am currently trying to run the "example data" to check if I have everything set up the right way.
When I am using the IEDB RESTful web interface, everything runs smoothly and I get the desired output.
Afterwards I wanted to try my local IEDB installation (``` --iedb-install-directory ../IEDB/ ```).

In the beginning, everything seemed fine, and the a conda enviroment is set up (``` pvactools_py27 ```).
Then the following error appears: 

```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Traceback (most recent call last):
  File "/home/miniconda3/envs/pVAC/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/pVAC/lib/python3.7/site-packages/tools/pvacseq/main.py", line 95, in main
    args[0].func.main(args[1])
  File "/home/miniconda3/envs/pVAC/lib/python3.7/site-packages/tools/pvacseq/run.py", line 89, in main
    lib.call_iedb.setup_iedb_conda_env()
  File "/home/miniconda3/envs/pVAC/lib/python3.7/site-packages/lib/call_iedb.py", line 13, in setup_iedb_conda_env
    version_check = run("/bin/bash -l -c \"conda activate pvactools_py27 && python -c \\\"import platform; print(platform.python_version())\\\"\"", stdout=PIPE, check=True, shell=True)
  File "/home/miniconda3/envs/pVAC/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/bin/bash -l -c "conda activate pvactools_py27 && python -c \"import platform; print(platform.python_version())\""' returned non-zero exit status 1.

```

I am using version 1.5.10 and I used a conda enviroment in which I installed pvactools.

Can anybody point me to a solution of that problem? Any help is appreciated.
Thanks!

**Comment by susannasiebert** [comment]
I believe your conda hasn't been correctly configured to work in your shell. Try following the instructions [here](https://github.com/conda/conda/blob/master/CHANGELOG.md#440-2017-12-20) and see if that fixes things.

**Comment by nickhir** [comment]
Thanks for the quick answer!
Indeed, my ```.bashrc```  had the outdated configuration.
I changed it to the recommanded configuration, but the error was still ocurring...
I then changed 
```version_check = run("/bin/bash -l -c \"conda activate pvactools_py27 && python -c \\\"import platform; print(platform.python_version())\\\"\"", stdout=PIPE, check=True, shell=True)``` to
```version_check = run("/bin/bash -l -c \"source activate pvactools_py27 && python -c \\\"import platform; print(platform.python_version())\\\"\"", stdout=PIPE, check=True, shell=True)```.
If I know run the example test with only one core, everything works fine. However as soon as I use more cores (```-t 8```) the same error as abouve occures several times.
I guess that only for one subprocess the correct conda enviroment was actually activated.
Do you have any idea how I could fix that?
Thank you very much.

**Comment by susannasiebert** [comment]
I'm not really sure why this would cause an error during multithreading. Are you able to use docker instead of trying to manage your own installation?

**Comment by nickhir** [comment]
Im sorry, the multithreading doesn't cause a problem. I wrote the answer while the single core process was running. The error occures as soon as NetMHC is used. Again ``` conda activate pvactools_py27``` causes the problem.
I did not try docker yet. Ill continue looking for a solution for conda, but then I'll try docker. 
If you have another idea, let me know.
Thanks!

**Comment by susannasiebert** [comment]
You could try an older version of conda (4.3 or older), which uses the old-style PATH export and might not have the problem you're seeing.

**Comment by nickhir** [comment]
I figured out my problem: 
The ```.bashrc``` file was not the problem. 
I suspect, that because of the ``` -l ``` argument when executing bash, the ```.bashrc``` was not actually sourced. Instead, the ```.profile``` file gets sourced. So I added ```. "/home/miniconda3/etc/profile.d/conda.sh"``` to my ```.profile``` file and now everything works as intended.
