### ISSUE TITLE
Question about the adding coverage data to your VCF step

### ISSUE THREAD

**Issue by aditisk** [griffithlab/pVACtools#587]
Hi,

Thank you for the detailed documentation, it is very helpful for new users. I'm currently on the step that adds coverage data to my VCF. 

For my VCF from RNA data, I have fields DP and AD (instead of RDP and RAD that are required) in my VCF file. Will just replacing DP and AD with RDP and RAD respectively be enough or do I need to follow the next few steps mentioned in that section ?

Thanks

**Comment by susannasiebert** [comment]
Renaming the fields sounds like the right thing to do in this case. Otherwise pVACseq would interpret these coverage metrics as tumor dna coverage metrics and use incorrect cutoffs. 

Our team is curious, though, what your input VCF looks like. pVACseq is designed to work on a tumor DNA VCF. Does your VCF then have RNA positional/ref/alt information? I'm not sure if VEP supports this either but I haven't tried it.

**Comment by aditisk** [comment]
Thanks for the prompt response. I have used Mutect2 to call somatic variants from paired exome data and VarScan to call somatic variants from paired RNASeq data. So I have 2 VCFs currently. Is this going to be a problem ? Do I need to annotate both these VCFs with VEP ? Currently I only annotated the DNA VCF file.

Do you recommend a certain variant caller for RNAseq to generate the VCF ? I could try that instead.

**Comment by chrisamiller** [comment]
If you intend to have one set of pvactools calls coming from these two callers, I'd recommend merging those VCFs into one set of calls (see this for an example: https://github.com/genome/analysis-workflows/blob/master/definitions/tools/combine_variants.cwl).  Then you could annotated with readcounts from both DNA and RNA, as described elsewhere.  That would simplify your workflow, right?

**Comment by aditisk** [comment]
Hi @chrisamiller, thanks for the suggestion. Does it matter where the variant call comes from (DNA vs RNA) ? My initial thought was that I needed to call variants twice but if that is not necessary, I can just use my VCF from Mutect2 and add readcounts from DNA and RNA to that VCF.

Thanks for your help

**Comment by chrisamiller** [comment]
> Does it matter where the variant call comes from (DNA vs RNA) 
That depends upon your priors about which is more likely to yield reliable variant calls.  In our experience, variants called from RNA tend to have a very high false-positive rate. (but it's also true that in extremely impure tumors, variants in highly-expressed genes might be more visible in the RNA).  Our general preference is to use DNA calls only, if possible. 

In any case, the CombineVariants tool has the set field that allows you to trace the origins of your calls, if that's useful.

**Comment by aditisk** [comment]
Thank you so much for your input.
