### ISSUE TITLE
Error when running pVACseq

### ISSUE THREAD

**Issue by leldershaw** [griffithlab/pVACtools#591]
Error occurs quickly after running pVACseq. Tried `conda init bash`, and can activate the pvactools_py27 environment with no issues outside of pVACseq using `conda activate pvactools_py27`. 

**Command used:** 
/home/ubuntu/anaconda3/bin/pvacseq run -e 9 --iedb-install-directory ../restart/iedb -b 1000000 -l 17 Mel5_tumor_v_Mel5_normal.combine_variants.phased.annotated.vcf.gz Mel5_tumor_v_Mel5_normal HLA-A*01:01,HLA-B*08:01,HLA-C*07:01 NetMHCpan ../restart

**Error message:**
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/tools/pvacseq/main.py", line 95, in main
    args[0].func.main(args[1])
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/tools/pvacseq/run.py", line 89, in main
    lib.call_iedb.setup_iedb_conda_env()
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/lib/call_iedb.py", line 13, in setup_iedb_conda_env
    version_check = run("/bin/bash -l -c \"conda activate pvactools_py27 && python -c \\\"import platform; print(platform.python_version())\\\"\"", stdout=PIPE, check=True, shell=True)
  File "/home/ubuntu/anaconda3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/bin/bash -l -c "conda activate pvactools_py27 && python -c \"import platform; print(platform.python_version())\""' returned non-zero exit status 1.

**Comment by susannasiebert** [comment]
pVACseq uses a child process to activate the conda environment and run the standalone IEDB command. Something about your conda installation is not set up correctly to support this. We usually recommend switching to docker in this case.

**Comment by leldershaw** [comment]
Ok, thank you. The docker implementation worked.

**Comment by susannasiebert** [comment]
Awesome. I'll close this issue.
