### ISSUE TITLE
Wildtype/Downstream mismatch

### ISSUE THREAD

**Issue by vladsaveliev** [griffithlab/pVACtools#596]
* pvactools version: 1.5.10
* Python version: 3.7.8
* Operating System: linux

**Describe the bug**

```
Exception: Leading amino acid of the Downstream protein sequence (KRKHSSFGRTDYFD) expected to match the wildtype amino acid at postion 46 (R). You may need to reannotate your VCF with a newer version of
 VEP.
```

The variant is:

```
chr20   18142252        .       G       GA      275     PASS    MH=A;RC=CGGAAAAAAAG;RC_MH=A;RC_NM=1;RC_REPC=7;RC_REPS=A;REP_C=6;REP_S=A;TIER=HIGH_CONFIDENCE;TNC=GGA;TUMOR_VD=13;NORMAL_VD=0;RNA_VD=41;TUMOR_DP=50;NORMAL_DP=34;RNA_DP=99;TUMOR_AF=0.26;NORMAL_AF=0;RNA_AF=0.414;PCGR_SYMBOL=PET117;PCGR_TIER=TIER_4;PCGR_CONSEQUENCE=frameshift_variant;PCGR_TCGA_PANCANCER_COUNT=1;COSMIC_CNT=0;ICGC_PCAWG_HITS=1;CSQ=A|frameshift_variant|HIGH|PET117|ENSG00000232838|Transcript|ENST00000432901|protein_coding|2/2||ENST00000432901.4:c.147dup|ENSP00000397881.2:p.Glu50ArgfsTer14|234-235|141-142|47-48|-/X|-/A|||1||HGNC|HGNC:40045|1|6|KRKHSSFGRTDYFD|-18|MSRSSKVVLGLSVLLTAATVAGVHVKQQWDQQRLRDGVIRDIERQIRKKENIRLLGEQIILTEQLEAEREKMLLAKGSQKS      GT:AD:AF:DP:RABQ:RAD:RC_CNT:RC_IPC:RC_JIT:RC_QUAL:RDP   0/0:34,0:0:34:1364,0:37,0:0,0,0,0,34,34:0:31,0,23:0,0,0,0,865,865:37    0/1:57,41:0.414:99:3818,0:101,0:38,3,0,0,57,99:0:52,0,39:987,45,0,0,1463,2522:102       0/1:37,13:0.26:50:1457,453:41,13:10,3,0,0,37,50:0:33,0,24:266,33,0,0,926,1225:54
```

VEP version is 101

UPD: with VEP 95, it doesn't reproduce, with annotation being different: 

```
chr20   18142252        .       G       GA      275     PASS    MH=A;RC=CGGAAAAAAAG;RC_MH=A;RC_NM=1;RC_REPC=7;RC_REPS=A;REP_C=6;REP_S=A;TIER=HIGH_CONFIDENCE;TNC=GGA;TUMOR_VD=13;NORMAL_VD=0;RNA_VD=41;TUMOR_DP=50;NORMAL_DP=34;RNA_DP=99;TUMOR_AF=0.26;NORMAL_AF=0;RNA_AF=0.414;PCGR_SYMBOL=PET117;PCGR_TIER=TIER_4;PCGR_CONSEQUENCE=frameshift_variant;PCGR_TCGA_PANCANCER_COUNT=1;COSMIC_CNT=0;ICGC_PCAWG_HITS=1;CSQ=A|frameshift_variant|HIGH|PET117|ENSG00000232838|Transcript|ENST00000432901|protein_coding|2/2||ENST00000432901.4:c.147dup|ENSP00000397881.2:p.Glu50ArgfsTer14|234-235|141-142|47-48|-/X|-/A|||1||HGNC|HGNC:40045|1|6|RKKRKHSSFGRTDYFD|-18|MSRSSKVVLGLSVLLTAATVAGVHVKQQWDQQRLRDGVIRDIERQIRKKENIRLLGEQIILTEQLEAEREKMLLAKGSQKS  GT:AD:AF:DP:RABQ:RAD:RC_CNT:RC_IPC:RC_JIT:RC_QUAL:RDP   0/0:34,0:0:34:1364,0:37,0:0,0,0,0,34,34:0:31,0,23:0,0,0,0,865,865:37      0/1:57,41:0.414:99:3818,0:101,0:38,3,0,0,57,99:0:52,0,39:987,45,0,0,1463,2522:102       0/1:37,13:0.26:50:1457,453:41,13:10,3,0,0,37,50:0:33,0,24:266,33,0,0,926,1225:54
```

**Comment by susannasiebert** [comment]
This is a known error with newer VEP versions (see also .https://github.com/griffithlab/pVACtools/issues/576) We're currently working on a fix but it will probably be a while before we can get it finalized as it requires a lot of testing on our end. For now, please use VEP version < 100.

**Comment by susannasiebert** [comment]
This problem has been resolved in the newly released pVACtools version 2.0. In this version, we switched from using the `Downstream` plugin to our own plugin, `Frameshift`. This requires installing this new plugin in your VEP plugins directory and reannotating your VCFs to include this plugin. Please see the [VEP instructions](https://pvactools.readthedocs.io/en/latest/pvacseq/input_file_prep/vep.html#vep) for more information.

**Comment by snashraf** [comment]
Hi Susan,

We are trying to install the Frameshift plugin using below command
pvacseq install_vep_plugin /gpfs/software/genomics/VEP/ensembl-tools-release-99/ensembl-vep/plugins/Plugins/
This command is quitting without any error but I don't see any Frameshift plugin inside the Plugin folder. I can found the Wildtype plugin but not the Frameshift. Can you please let us know what we are doing wrong? I am using pvactools/v1.5.7

**Comment by susannasiebert** [comment]
@snashraf I apologize for the confusion but you will need to update to pVACtools 2.0 before running this command. The Frameshift plugin is only distributed with the latest version of pVACtools so it can only be installed when you have pVACtools 2.0 installed first.
