### ISSUE TITLE
incorporation of foreignness?

### ISSUE THREAD

**Issue by boyangzhao** [griffithlab/pVACtools#597]
In light of the recent Wells et al Cell paper, examining the different feature contributions, is there any plan to also include foreignness in pVACseq? Thanks!

**Comment by malachig** [comment]
Yes, this is on our development road map.  It is not part of the 2.0 release which is coming soon, but we hope to address this shortly after that release.

**Comment by boyangzhao** [comment]
Good to know! Thanks for the speedy response!

**Comment by susannasiebert** [comment]
This feature has been added to our new release version 2.0. You can turn on this feature by adding the `--run-reference-proteome-similarity` flag in your `pvacseq run` command. This will blast the peptide sequence to the reference proteome and report whether any hits were found. Please see [the documentation](https://pvactools.readthedocs.io/en/latest/pvacseq/output_files.html#filtered-tsv-reference-matches-report-columns) for more information on this feature.
