### ISSUE TITLE
Memory usage at "Combining Parsed IEDB Output Files" step

### ISSUE THREAD

**Issue by chrisamiller** [griffithlab/pVACtools#60]
When processing about 13k variants (which means 26k fasta entries), the memory usage skyrockets at the step where it's combining the files (over 4Gb). It's probably worth looking into a more mem-efficient way to merge/sort the data.

**Comment by susannasiebert** [comment]
Can you point me to the vcf and post the example command that failed on your machine so I can use it for benchmarking?

**Comment by chrisamiller** [comment]
Sure thing.  Given that it took something like 48h to do the predictions, you're probably better off just letting it shortcut through all the results to get to the problematic step. 
/gscmnt/gc2708/info/medseq/tmp/pvac_bigmem
