### ISSUE TITLE
Warning when using the --phased-proximal-variants-vcf option

### ISSUE THREAD

**Issue by nickhir** [griffithlab/pVACtools#609]
Hello,
i am running the pvacseq command with the `-p` option. The phased vcf file I created according to [this](https://pvactools.readthedocs.io/en/latest/pvacseq/input_file_prep/proximal_vcf.html). (Before running `bgzip`, I also annotated the phased VCF with `VEP`, I am not sure if this is necessary.)

The following warning appears when running pvacseq:

```
Warning: There are multiple CSQ entries (consequences) for proximal variant Record(CHROM=1, POS=161695817, REF=A, ALT=[C]) and alternate allele C. Using the first one.     
Warning: There are multiple CSQ entries (consequences) for proximal variant Record(CHROM=1, POS=161695817, REF=A, ALT=[C]) and alternate allele C. Using the first one.     
Warning: Proximal variant transcript is not the same as the somatic variant transcript. Proximal variant will be skipped: Record(CHROM=1, POS=161695817, REF=A, ALT=[C])   
 Warning: There are multiple CSQ entries (consequences) for proximal variant Record(CHROM=1, POS=161695817, REF=A, ALT=[C]) and alternate allele C. Using the first one.     
Warning: Proximal variant transcript is not the same as the somatic variant transcript. Proximal variant will be skipped: Record(CHROM=1, POS=161695817, REF=A, ALT=[C])    
Warning: There are multiple CSQ entries (consequences) for proximal variant Record(CHROM=1, POS=161695817, REF=A, ALT=[C]) and alternate allele C. Using the first one.     
Warning: Proximal variant transcript is not the same as the somatic variant transcript. Proximal variant will be skipped: Record(CHROM=1, POS=161695817, REF=A, ALT=[C])    
Warning: There are multiple CSQ entries (consequences) for proximal variant Record(CHROM=1, POS=161695817, REF=A, ALT=[C]) and alternate allele C. Using the first one.     
Warning: Proximal variant transcript is not the same as the somatic variant transcript. Proximal variant will be skipped: Record(CHROM=1, POS=161695817, REF=A, ALT=[C])   
 Warning: There are multiple CSQ entries (consequences) for proximal variant Record(CHROM=1, POS=161695817, REF=A, ALT=[C]) and alternate allele C. Using the first one.     
Warning: Proximal variant transcript is not the same as the somatic variant transcript. Proximal variant will be skipped: Record(CHROM=1, POS=161695817, REF=A, ALT=[C])
```

A very similar warning message was printed for at least 10 other variants. 
I am quite unsure what exactly this means or how I can circumvent this warning, because when I look at the specified variants, they look just like other variants (I do not see multiple CSQ entries). The only thing I noticed, is that oftentimes another variant is close by.
I have attached a subset of the variants which were specified in the warning message and a few surrounding variants as an example. 

[phased_subset.txt](https://github.com/griffithlab/pVACtools/files/5549490/phased_subset.txt)

I am asking this here, because I didn't find any documentation on this and I thought that maybe some other users also encountered this warning. 

Cheers!

**Comment by susannasiebert** [comment]
When running VEP, it will make predictions for each transcript of the gene that overlaps the variant position. The main pVACseq tool processes all transcript consequences predicted by VEP since they can potentially result in differing amino acid protein sequences. For example, in your attached VCF, the CSQ fields each contain multiple entry, one for each transcript. These are comma separated, e.g., 

```
CSQ=C|missense_variant|MODERATE|FCGR3B|ENSG00000162747|Transcript|ENST00000294800.3|[...],
C|intron_variant|MODIFIER|FCGR2B|ENSG00000072694|Transcript|ENST00000367960.5|[...],
C|intron_variant|MODIFIER|FCGR2B|ENSG00000072694|Transcript|ENST00000367962.4|[...]
```
are consequences for ENST00000294800.3, ENST00000367960.5, and ENST00000367962.4 (example abbreviated and formatted for clarity).
When processing the proximal VCF however, pVACseq only considers the first transcript in this list (ENST00000294800.3) and then matches that up with the appropriate CSQ entry for the same transcript from the main somatic variant of interest. As a result, this proximal variant would only be incorporated for ENST00000294800.3 and not for any of the other transcripts of your main somatic variant of interest.

This is a know shortfall that we are addressing in version 2.0.0, which will be release either later this month or next. For now, we recommend to run VEP on your proximal VCF with the `--pick` option which will only return the consequence for the most impactful (per VEP) transcript. Unfortunately, there are some caveats here as well because VEP's algorithm doesn't necessarily always pick the best transcript (most of the time it does). However, this would at least ensure that the proximal variant is incorporated into the transcript that has the higher likelihood of being the correct one.

**Comment by nickhir** [comment]
Thank you very much for the quick and comprehensive responds! 
As you said, running the pipeline with the `pick` option makes the warning disappear.

**Comment by zhouxinyi520** [comment]
Hello,
i am also running the pvacseq command with the -p option.  I created The phased vcf file by the recommended GATK ReadBackedPhasing . (after annotated the VCF with VEP with -- pick  aurgment and combine with the germline mutation by GATK haplotypecall ),but i meet this similar problem ,i do not how to solve it or it  dose not matter at all ,here are the WRANINGS ,So many something like this ,sincerely expect your reply !

Warning: Proximal variant is not a missense mutation and will be skipped: Record(CHROM=21, POS=33576418, REF=G, ALT=[GCCCAATTGTATGTTTTTCTTGAATAGGTATTGATAAATGGAAGCGCTTACCAG])
Warning: Proximal variant is not a missense mutation and will be skipped: Record(CHROM=21, POS=33576421, REF=T, ALT=[TCCCAATTGTATGTTTTTCTTGAATAGGTATTGATAAATGGAAGCGCTTACCAG])
Warning: Proximal variant is not a missense mutation and will be skipped: Record(CHROM=21, POS=33576422, REF=T, ALT=[TCCCAATTGTATGTTTTTCTTGAATAGGTATTGATAAATGGAAGCGCTTACCAG])
Warning: Proximal variant is not a missense mutation and will be skipped: Record(CHROM=21, POS=33576423, REF=G, ALT=[GCCCAATTGTATGTTTTTCTTGAATAGGTATTGATAAATGGAAGCGCTTACCAG])
Warning: Proximal variant is not a missense mutation and will be skipped: Record(CHROM=21, POS=33576424, REF=A, ALT=[ACCCAATTGTATGTTTTTCTTGAATAGGTATTGATAAATGGAAGCGCTTACCAG])
Warning: Proximal variant is not a missense mutation and will be skipped: Record(CHROM=21, POS=33576425, REF=T, ALT=[TCCCAATTGTATGTTTTTCTTGAATAGGTATTGATAAATGGAAGCGCTTACCAG])
Warning: Proximal variant is not a missense mutation and will be skipped: Record(CHROM=21, POS=33576427, REF=A, ALT=[ACCCAATTGTATGTTTTTCTTGAATAGGTATTGATAAATGGAAGCCCTTACCAG])
Warning: Proximal variant is not a missense mutation and will be skipped: Record(CHROM=21, POS=33576428, REF=A, ALT=[ACCCAATTGTATGTTTTTCTTGAATAGGTATTGATAAATGGAAGCGCTTACCAG])
Warning: Proximal variant is not a missense mutation and will be skipped: Record(CHROM=21, POS=33576429, REF=T, ALT=[TCCCAATTGTATGTTTTTCTTGAATAGGTATTGATAAATGGAAGCCCTTACCAG])
Warning: Proximal variant is not a missense mutation and will be skipped: Record(CHROM=21, POS=33576430, REF=G, ALT=[GGAAGCGCTTACCAGCCCAATTGTATGTTTTTCTTGAATAGGTATTGATAAATT])
...

my pvactools  version is 2.0.4 ,the code is as follows

pvacseq run /mnt/DATA/zxy/somatic/NPC002_somatic.vcf.gz NPC002D HLA-A*33:03,HLA-A*11:02,HLA-B*15:02,HLA-B*58:01,HLA-C*08:01,HLA-C*03:02 NetMHCpan NetMHC NetMHCcons PickPocket SMM SMMPMBEC MHCflurry MHCnuggetsI  /mnt/DATA/zxy/pvacseq/NPC002_pvac_result1 -e1 8,9,10,11 --iedb-install-directory ~ -p /mnt/DATA/zxy/combine/NPC002_phased.vcf.gz --normal-sample-name NPC002B --top-score-metric lowest --net-chop-method cterm --netmhc-stab -d full -t 10 &

                                                                                                                                                           Cheers!
                                                                                                                                                           sincerely

**Comment by malachig** [comment]
For the warning: `Warning: Proximal variant is not a missense mutation and will be skipped:`.

When we created support for proximal variants we only implemented a solution for proximal variants of the single nucleotide variant type (SNVs). 

If your mutation has a proximal variant nearby that is a small insertions or deletions the impact of that proximal variant will not be determined automatically.  These are pretty rare but do happen.  In these cases you might want to manually review such variants and determine if the proximal insertion or deletion is likely to impact the sequence of your neoantigen peptide.  If it is in phase with your somatic variant and very close by, it could impact the peptide sequence and the one that pVACseq reports could be incorrect.  But again this will be very rare overall.  

For more details on this concept, please refer to this manuscript:
https://www.nature.com/articles/s41588-018-0283-9

**Comment by zhouxinyi520** [comment]
Thanks  for your quick and comprehensive responds.
Sadly,I got so many warnings like this ,i guess whether that was because i combined the somatic mutation results (mutect2,strealka,varscan2) including  pindel ,which contained so many indels?   Interestingly ,i got the totally  same  filtered neoantigen results  whether i run pvacseq with or without the -p phased.vcf.gz ,and i  only got a few neoantigens ,most of  the number of  filterd results were less than 10;  according to my understanding ,the warnings of Proximal variants should not affect the number of results?Am i right?

I am a new guy in this field . Sincerely expect your reply !
Cheers!

**Comment by chrisamiller** [comment]
- Variant calling is a little outside the scope of this tool, but pindel is giving you a very large number of indels, you may want to consider doing filtering - one example workflow is here: https://github.com/genome/analysis-workflows/blob/master/definitions/subworkflows/pindel.cwl
- The proximal variant procedure does "correction" of the amino acid sequences being evaluated before they are fed into the prediction algorithms (to account for nearby snps or adjacent somatic mutations).  If you set binding thresholds, for example, this could affect your number of results if the corrected peptides have different binding than the originals. A change in the number of results is not necessarily expected to occur - it depends completely on the characteristics of your sample and mutations, and whether there are proximal variants affecting your mutations of interest.
- The errors you're seeing do not affect the number of results - they are only warnings about indels not being "corrected", as Malachi described above
- The overall number of neoantigens returned depends on a number of factors, including the number of coding variants fed in, the thresholds you're using for filtering, etc.

Best of luck!

**Comment by zhouxinyi520** [comment]
Oh,I got it,thank you very much ,I'd try filter the results of pindel first;I learned a lot from you ,thanks!

Best Wishes!
