### ISSUE TITLE
installation error with pysam

### ISSUE THREAD

**Issue by nknewnew** [griffithlab/pVACtools#610]
I am using conda to install pvactools. But it kept reporting error with the pysam installation. I am using python 3.7 in the conda env, and it seems pysam==0.9.0 cannot be compiled in this env. But it kept trying to install pysam 0.9.0 when I use "pip install pvactools" (even if I already have pysam 0.16 installed in the env). Can anyone tell me how to solve this problem? Thanks.

**Comment by susannasiebert** [comment]
It's difficult to debug installation issues like this remotely so in this situation we would recommend to switching to the Docker image, if you're able to do so.

**Comment by nknewnew** [comment]
@

> It's difficult to debug installation issues like this remotely so in this situation we would recommend to switching to the Docker image, if you're able to do so.

I am just using standard conda env. Is it possible to use pysam 0.16 instead of pysam 0.9? And how stop the pip install from compiling pysam 0.9.0 in the pip install command line?

**Comment by susannasiebert** [comment]
Version 1.5.12 removes a dependency to an older version of the vaxrank package (which in turn was causing the dependency on pysam 0.9). pVACtools 1.5.12 should now install without trouble. Let me know if you're running into any problems with it.
