### ISSUE TITLE
How does net-chop scores are calculated for Pvacbind 

### ISSUE THREAD

**Issue by Admera2020** [griffithlab/pVACtools#614]
Hello, 

I wanted to get MHC-I predictions + Cleavage predictions for a list of peptides which shown to have an immunogenic effect. Given my starting point is peptide sequences I opt to run Pvacbind. 
As per the documentation, the input to Pvacbind is "a FASTA file of peptide sequences." which I assumed to be a mutant epitope sequence. The input of NetChop is the protein sequence [here](http://tools.iedb.org/netchop/). 

Curious if the use of mutant epitope was the right approach. 

Best,
Nihir

**Comment by susannasiebert** [comment]
That's correct. pVACbind will work on a list of mutant peptides. You will just want to be careful when choosing your epitope length(s) and selecting final epitopes that the epitope still overlaps the mutation. The cleavage site prediction will also happen on a per-eptiope basis, not on the original peptide.

**Comment by Admera2020** [comment]
Thank you for your quick response.  I did a quick test used a full protein sequence run through NetChop followed by 9 AA long peptides the scores were different.  Is it expected? 

Here the output with the entire protein 

```

# | amino_acid | prediction_score
-- | -- | --
1 | M | 0.618935
2 | S | 0.046833
3 | L | 0.923545
4 | L | 0.756254
5 | T | 0.037353
6 | E | 0.025171
7 | V | 0.523328
8 | E | 0.023849
9 | T | 0.039626
10 | P | 0.058487
11 | I | 0.853657
12 | R | 0.239428
13 | N | 0.034104
14 | E | 0.0362
15 | W | 0.974923
.
.
.
```

Here is the output from the first 9 AA, as you can see the difference is not small enough that can be ignored. 

```
# | amino_acid | prediction_score
-- | -- | --
1 | M | 0.618935
2 | S | 0.033137
3 | L | 0.904844
4 | L | 0.679278
5 | T | 0.069754
6 | E | 0.02842
7 | V | 0.907133
8 | E | 0.073135
9 | T | 0.270143

```

Nihir

**Comment by susannasiebert** [comment]
Can you please include the epitopes/peptides for each score in both cases?

**Comment by Admera2020** [comment]
I am not sure I understood and Just to confirm this was tested on NetChop http://tools.iedb.org/netchop. as below.


> Input1: Protein Sequence
MSLLTEVETPIRNEWGCRCNDSSDPLVVAASIIGIVHLILWIIDRLFSKSIYRIFKHGLKRGPSTEGVPESMREEYREEQQNAVDADDGHFVSIELE

> Input2 : 9 AA
MSLLTEVET

**Comment by malachig** [comment]
There is a lot of nuance here, but the short answer is that the cleavage predictions depend on sequence context (flanking amino acids).  And the window being used to calculate the cleavage prediction for each position is larger than the peptide.  Try your test again but increase the short peptide length to 9AA, 10AA, 11AA ...  Look at the impact of the score for each position.  

We know that our incorporation of this tool needs to accommodate this nuance better.  But it's something we haven't been able to prioritize quite yet.

**Comment by susannasiebert** [comment]
I made issue #615 to track development on improvements to this feature. It is currently scheduled for the 2.1 version.

**Comment by Admera2020** [comment]
Thank you both for your help with this, really appreciate your prompt response and clarification on this. I will keep reviewing the changes.
