### ISSUE TITLE
Rework cleavage site predictions

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVACtools#615]
Right now cleavage sites are calculated on a per-eptiope basis. However, this doesn't give accurate results.

Cleavage predictions depend on sequence context (flanking amino acids). It appears that the predictions are only stable if a flanking region of 10 amino acids is added on either side of the peptide (this number should be double checked).

We should update the code to create a netchop-specific fasta (with 10 aa flanking length) and feed that to the algorithm. Subsequent calculations on the netchop result should only happen on the amino acids for the epitope of interest.

**Comment by worker000000** [comment]
> Right now cleavage sites are calculated on a per-eptiope basis. However, this doesn't give accurate results.
> 
> Cleavage predictions depend on sequence context (flanking amino acids). It appears that the predictions are only stable if a flanking region of 10 amino acids is added on either side of the peptide (this number should be double checked).
> 
> We should update the code to create a netchop-specific fasta (with 10 aa flanking length) and feed that to the algorithm. Subsequent calculations on the netchop result should only happen on the amino acids for the epitope of interest.

thanks a lot
do you here mean  the following options is not good to use?
![image](https://user-images.githubusercontent.com/25199946/102001182-f64b1000-3d29-11eb-8105-a53c829c3e83.png)
<br>
if use  --net-chop-method, can just add  --net-chop-method cterm,20s   --netmhc-stab True --net-chop-threshold 0.5 

. is this right?

**Comment by susannasiebert** [comment]
It will still be informative to run NetChop with the current implementation but you just need to be aware that the output in the report will not be comprehensive and you will need to do some additional manual analysis downstream.

You cannot run `--net-chop-method cterm,20s`. You need to pick one method or the other so either `--net-chop-method cterm` or `--net-chop-method 20s`.
