### ISSUE TITLE
no filtered.tsv all_epitopes.tsv filtered.condensed.ranked.tsv

### ISSUE THREAD

**Issue by worker000000** [griffithlab/pVACtools#620]
Thanks a lot
I can meet such situation, the program ended, but does not has file filtered.tsv all_epitopes.tsv filtered.condensed.ranked.tsv.

and there is also no error included in my error log, is there any inner error log of pvactools?
![image](https://user-images.githubusercontent.com/25199946/102015909-2da4d580-3d99-11eb-8cc1-e5ef5661cf09.png)

**Comment by susannasiebert** [comment]
Log messages are written to stdout. It might contain some information about why your run didn't succeed.

**Comment by worker000000** [comment]
thanks a lot
there is only a inputs.yml there,  it just contains the parameter options and nothing else.

```
additional_report_columns: null
allele_specific_binding_thresholds: false
alleles:
- HLA-A*02:01
- HLA-A*24:02
- HLA-B*40:02
- HLA-B*46:01
- HLA-C*03:04
- HLA-C*15:02
binding_threshold: 500
downstream_sequence_length: 1000
epitope_lengths:
- 8
- 9
- 10
- 11
exclude_NAs: false
expn_val: 1.0
fasta_size: 200
iedb_executable: /opt/iedb/mhc_i/src/predict_binding.py
iedb_retries: 5
trna_cov: 10
trna_vaf: 0.25
```

**Comment by susannasiebert** [comment]
Please check your [stdout](https://en.wikipedia.org/wiki/Standard_streams#Standard_output_(stdout)). I suspect that the way you are running Docker is suppressing the stdout so you will need to check the Docker documentation to figure out how to capture the stdout from the commands run inside of a Docker container.

**Comment by worker000000** [comment]
thanks a lot
can you share me your command, I just ran as the doc, and I see no --debug option in pvacseq

**Comment by susannasiebert** [comment]
This is an example of what the beginning of the STDOUT from a pVACseq run looks like. If you don't see messages like this your are either suppressing or redirecting STDOUT and you will need to figure out where your STDOUT is written to. I will only be able to help you further once you post the STDOUT from your pVACseq run.
<img width="1357" alt="Screen Shot 2020-12-18 at 9 22 20 AM" src="https://user-images.githubusercontent.com/6617192/102630979-d8f3b880-4112-11eb-9f24-e903e12f4cae.png">

**Comment by worker000000** [comment]
thanks a lot
I generated log like this, and I have already describe it in the last github reply. which talks about parsed.tsv_ or .netmhcpan.HLA-.
I have already send to the help email of the log for a more detailed check.

**Comment by susannasiebert** [comment]
I can't seem to find this file in my email. Can you please attach it to this GitHub issue directly?

**Comment by worker000000** [comment]
thanks a lot.
you can refresh the email.
you should receive it now

**Comment by susannasiebert** [comment]
Thank you. I received them. It appears that your runs choke, which usually means they ran out of memory. Can you check the fasta files in the `tmp` folder and see if there are any frameshift peptide sequences in those files that are very long? Very long sequences can easily chocked complex prediction algorithms like NetMHCpan. I would try reducing the `--downstream-sequence-length` parameter to something shorter, like 100, and see if that helps.

**Comment by worker000000** [comment]
wait a moment, I will download all the files and sent to your email for your future check, to betther compare resoure, I change the threads from 1 4 8 12 16 20 24 30 36 40 48, and ran 1 vcf or many vcf parappele, it is really making me hopeless

**Comment by susannasiebert** [comment]
Please try with 1 thread, only one VCF, and `--downstream-sequence-length 100` and report back with the results from that run.

**Comment by worker000000** [comment]
thanks a lot
the t=1 file I have ready sent to you is 1 thread, it failed also
apart from reduce the length, is there any other advice?

**Comment by susannasiebert** [comment]
That's the next thing I would try, since you already tried with only one thread. We've had success with 100 in the past. If that works you could try adding more threads again.

**Comment by worker000000** [comment]
thanks a lot
ok, I will try now, it will need almost one day, which is really too much time. I will report the result to you as long as I get result through email

**Comment by worker000000** [comment]
It's sad。
 try with 1 thread, only one VCF, and --downstream-sequence-length 100 ， it runs choke. just endde here, without parsing prediction result
![image](https://user-images.githubusercontent.com/25199946/102684578-b21dab00-4214-11eb-8e61-896645aed8ce.png)

**Comment by susannasiebert** [comment]
Which sample is this? Can you please, for this specific run email me (1) the input VCF (2) the full stdout (not just a screenshot), (3) the output directory.

**Comment by worker000000** [comment]
thanks a lot.
last night I have sent you a whole zip of two vcf.  here I will send you another 4 whole files contains everything

**Comment by worker000000** [comment]
thanks a lot @susannasiebert 
all the needed files have send

**Comment by susannasiebert** [comment]
I have not received your latest email with these files. It might've been too large? Can you upload these files to Google Drive, Box, or somewhere similar and email me a download link?

**Comment by worker000000** [comment]
Thanks  a lot.
I sent it to you 2 days ago, maybe too large. I will upload google drive in 5 minutes,it is my fault,.
if you receive it, please tell me.

**Comment by worker000000** [comment]
have you received it?

**Comment by susannasiebert** [comment]
I have received your email with the Google Drive link.

**Comment by worker000000** [comment]
thanks for your kind help, hope [pvactools can be the best, I am going to sleep now, it is 12:00 night here,

**Comment by susannasiebert** [comment]
Looking into this more I don't actually think that this job is stuck or failed but that it's simply taking a long time. I just made a new release to pVACtools (1.5.13) which improves how we call MHCnuggets which should speed things up significantly. Please switch to the newest version by changing your script to use the `griffithlab/pvactools:1.5.13` Dockerfile and see if that helps with this problem.

**Comment by worker000000** [comment]
thanks a lot.
but in my many tests, I can clear see it stopped, because I used `htop` to see whether it is running, I am sure it does not because it takes a long time and will end successfully.
<br>
the reason why I used MHCflurry because NetMHCpan do not support every hla allele, so I guess MHCflurry may act as a substitution, because it is written in python, it is too slow, while NetMHCpan is fast.  and can you describe the effect of --iedb-install-directory /opt/iedb, why we need it

**Comment by susannasiebert** [comment]
pVACtools 1.5.13 makes MHCflurry much faster. Please try it.

pVACseq can run IEDB either with the IEDB API or with standalone IEDB. Using `--iedb-install-directory /opt/iedb` makes it so you're using the standalone IEDB installed in the Docker container. It is faster than the IEDB API.

**Comment by worker000000** [comment]
thanks a lot.
I want to ask is either netmhcpan and mhcflurry can run alone to predict mhc binding, why IEDB is still needed

**Comment by susannasiebert** [comment]
I mistyped in my original comment. The speed improvement is to MHCflurry, not MHCnuggets.

pVACtools uses IEDB to make predictions with NetMHCpan as well 8 other prediction algorithms.

**Comment by worker000000** [comment]
but when I used NetMHCpan in other neo pipeline tools, I downloaded the files without IEDB,it does not need IEDB, thanks a lot

**Comment by susannasiebert** [comment]
It’s easier.

**Comment by worker000000** [comment]
so when I used the new docker, do I need to use --downstream-sequence-length 100 or the default 1000? you said the speed up significantly under which situation.
thanks a lot

**Comment by susannasiebert** [comment]
I tested with both successfully.

**Comment by worker000000** [comment]
thanks a lot, so will 1000 and 100 affect the neo predction accuray?

**Comment by susannasiebert** [comment]
> do you make mhcfullry stop repeating creating the initalized model?
yes (see https://github.com/griffithlab/pVACtools/pull/623 for a more detailed explanation)

A higher downstream sequence length will include more amino acids after a frameshift mutation so it will predict a larger number of neoeptiopes.

**Comment by worker000000** [comment]
so I just use the default 1000 will make a more resonable result?
thanks a lot

**Comment by worker000000** [comment]
thanks a lot
Merry Christmas
I found some tumor dna vaf is 1 in the output, which is impossible, is this a bug of bam-readcount?

**Comment by chrisamiller** [comment]
Why would that be impossible? If you have 10 reads and 10 of them are variant-supporting, your vaf will be 1
