### ISSUE TITLE
some tumor dna vaf is 1

### ISSUE THREAD

**Issue by worker000000** [griffithlab/pVACtools#628]
thanks a lot
Merry Christmas
I found some tumor dna vaf is 1 in the output, which is impossible, is this a bug of bam-readcount?

**Comment by susannasiebert** [comment]
As @chrisamiller replied to your identical comment on https://github.com/griffithlab/pVACtools/issues/620#issuecomment-750569165: If you have, for example, 10 reads and 10 of them are variant-supporting, your vaf will be 1.

**Comment by malachig** [comment]
Not only is 1 NOT impossible, this is indeed the expected VAF for all homozygous variants and for variants in regions of LOH...    For heterozygous variants, when coverage is low one can simply get unlucky.  e.g. instead of seeing 3/6 reads supporting the variant, by chance you see 0/6 or 6/6.
