### ISSUE TITLE
NetMHCpan run into error on example data

### ISSUE THREAD

**Issue by hliu2016** [griffithlab/pVACtools#629]
Hi, I am using the docker image to run pvactools. When I tried to run NetMHCpan on the example data. My full command is
`  pvacseq run input.vcf H_NJ-HCC1395-HCC1395 HLA-A*02:01,HLA-B*35:01 MHCflurry MHCnuggetsII NetMHCcons output -e 8,9,10 --iedb-install-directory /opt/iedb/` . But it run into the following error:

> 
> Generating Variant Peptide FASTA and Key Files
> Generating Variant Peptide FASTA and Key Files - Entries 1-128
> Completed
> Making binding predictions on Allele HLA-A*02:01 and Epitope Length 8 with Method MHCflurry - File /opt/pvacseq_example_data/output/MHC_Class_I/tmp/H_NJ-HCC1395-HCC1395.MHCflurry.HLA-A*02:01.8.tsv_1-128
> Making binding predictions on Allele HLA-A*02:01 and Epitope Length 8 with Method MHCflurry - File /opt/pvacseq_example_data/output/MHC_Class_I/tmp/H_NJ-HCC1395-HCC1395.MHCflurry.HLA-A*02:01.8.tsv_1-128 - Completed
> Making binding predictions on Allele HLA-A*02:01 and Epitope Length 8 with Method NetMHCpan - File /opt/pvacseq_example_data/output/MHC_Class_I/tmp/H_NJ-HCC1395-HCC1395.netmhcpan.HLA-A*02:01.8.tsv_1-128
> mesg: ttyname failed: Inappropriate ioctl for device
> Traceback (most recent call last):
>   File "/opt/iedb/mhc_i/src/predict_binding.py", line 452, in <module>
>     Prediction().main()
>   File "/opt/iedb/mhc_i/src/predict_binding.py", line 431, in main
>     stdin = sys.stdin.readline().strip()
> IOError: [Errno 9] Bad file descriptor
> An exception occured in thread 0: (<class 'subprocess.CalledProcessError'>, Command '['/bin/bash', '-l', '-c', 'conda activate pvactools_py27; python /opt/iedb/mhc_i/src/predict_binding.py netmhcpan HLA-A*02:01 8 /opt/pvacseq_example_data/output/MHC_Class_I/tmp/H_NJ-HCC1395-HCC1395_21.fa.split_1-128']' returned non-zero exit status 1.).
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.6/site-packages/lib/pipeline.py", line 342, in call_iedb
>     lib.call_iedb.main(arguments)
>   File "/opt/conda/lib/python3.6/site-packages/lib/call_iedb.py", line 55, in main
>     raise err
>   File "/opt/conda/lib/python3.6/site-packages/lib/call_iedb.py", line 50, in main
>     (response_text, output_mode) = prediction_class_object.predict(args.input_file, args.allele, args.epitope_length, args.iedb_executable_path, args.iedb_retries)
>   File "/opt/conda/lib/python3.6/site-packages/lib/prediction_class.py", line 57, in predict
>     response = run(['/bin/bash', '-l', '-c', 'conda activate pvactools_py27; python {}'.format(arguments)], stdout=response_fh, check=True)
>   File "/opt/conda/lib/python3.6/subprocess.py", line 418, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['/bin/bash', '-l', '-c', 'conda activate pvactools_py27; python /opt/iedb/mhc_i/src/predict_binding.py netmhcpan HLA-A*02:01 8 /opt/pvacseq_example_data/output/MHC_Class_I/tmp/H_NJ-HCC1395-HCC1395_21.fa.split_1-128']' returned non-zero exit status 1.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/bin/pvacseq", line 8, in <module>
>     sys.exit(main())
>   File "/opt/conda/lib/python3.6/site-packages/tools/pvacseq/main.py", line 95, in main
>     args[0].func.main(args[1])
>   File "/opt/conda/lib/python3.6/site-packages/tools/pvacseq/run.py", line 171, in main
>     pipeline.execute()
>   File "/opt/conda/lib/python3.6/site-packages/lib/pipeline.py", line 443, in execute
>     self.call_iedb(chunks)
>   File "/opt/conda/lib/python3.6/site-packages/lib/pipeline.py", line 343, in call_iedb
>     p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
>   File "/opt/conda/lib/python3.6/site-packages/pymp/__init__.py", line 148, in __exit__
>     raise exc_t(exc_val)
> TypeError: __init__() missing 1 required positional argument: 'cmd'

**Comment by hliu2016** [comment]
Can anybody help to resovle this problem?

**Comment by susannasiebert** [comment]
The command you posted doesn't match the logging messages. I think you are running NetMHCpan instead of NetMHCcons?

This error comes from IEDB itself, not pVACseq, so it will be difficult to debug:
```
File "/opt/iedb/mhc_i/src/predict_binding.py", line 431, in main
stdin = sys.stdin.readline().strip()
IOError: [Errno 9] Bad file descriptor
```

Which version of the Docker container are you running?

Does this error persist if you execute the command again?

Do you still have the output directory? If so, can you run the following from inside the Docker container:
```
/bin/bash -l -c 'conda activate pvactools_py27; python /opt/iedb/mhc_i/src/predict_binding.py netmhcpan HLA-A*02:01 8 /opt/pvacseq_example_data/output/MHC_Class_I/tmp/H_NJ-HCC1395-HCC1395_21.fa.split_1-128'
```

**Comment by susannasiebert** [comment]
Since there has been no more activity on this issue, I will close it but please do reopen it if you are still running into problems.
