### ISSUE TITLE
Proximal variants not supported in generate_protein_fasta?

### ISSUE THREAD

**Issue by boyangzhao** [griffithlab/pVACtools#630]
* pvactools version: 1.5.13
* Python version: 3.6.10

Hi guys,

It seems the current `generate_protein_fasta.py` does not take into account the proximal variants? Even though proximal variants can be handled (only for missense?) and is done during the normal `pvacseq run` routine, in the separate `generate_protein_fasta.py` script, it seems params `proximal_variants_file` is purposely left out when calling the `FastaGenerator` class.

https://github.com/griffithlab/pVACtools/blob/da18907e82f19825fe5479a2e94f037c12fd53d2/tools/pvacseq/generate_protein_fasta.py#L63

I've run also these bits the code and the output fasta seems to confirm this. Is there a plan to incorporate proximal variants?

Thanks,
Bo

**Comment by susannasiebert** [comment]
This feature will be added in version 2.0 (please see #522 and #531 for the corresponding issue and pull request, respectively). This feature has been merged into the staging branch so if you need to access it before the 2.0 release you can do so off of that branch. We can also make a new hotfix release to incorporate this into the 1.5 release if it is urgent.

**Comment by boyangzhao** [comment]
Thanks! It's not urgent for us at the moment- we have only observed one variant with a proximal variant that we for now just manually accounted for, in extending our peptide. We have some other codes to detect these discrepancies so it's not a huge issue. Looking forward to the 2.0 release - including some of those other features. :)

**Comment by susannasiebert** [comment]
Sounds good. I will close this issue but feel free to reopen if anything changes. We are working very hard to get 2.0 out of the door as soon as possible.
