### ISSUE TITLE
Errors during install pVactools in WSL+Conda+python3.7

### ISSUE THREAD

**Issue by ahua217** [griffithlab/pVACtools#631]
* pvactools version: the current version
* Python version:3.7.9
* Operating System: Ubuntu in WSL

**Describe the bug**
Hello! I met several errors when I tried to install pvactools.
I set up and activated python3.7 environment with WSL, Ubuntu and Conda.  I run the command:
pip install pvactools
With some progress threads almost completed, it returned such errors:
Building wheel for shellinford (setup.py) ... error
...
Failed to build shellinford
...
Running setup.py install for shellinford ... error

What does these mean and how can I fix them? I also tried python3.5, but there were other errors stuck the installation. Thank you very much!

-Jane

**Comment by ahua217** [comment]
Thank you Susan! I installed docker and typed this command `docker run -it griffithlab/pvactools` as the instruction I found at https://pvactools.readthedocs.io/en/latest/pvacseq/getting_started.html. This was my first time to use docker and am pretty unfamiliar about it.
It returned 
Unable to find image 'griffithlab/pvactools:lastest' locally
latest: Pulling from griffithlab/pvactools
XXXXXXX:downloading[=====> ]
...
docker: unexpected EOF
See 'docker run --help'.

The issue in my downloading is that it always stops with some unfinished parts after several retries. How can I let it resume from break-point or automatically retry until all the data are downloaded? Thank you very much!

**Comment by susannasiebert** [comment]
Hm, I haven't encountered this error before. Can you post the full output message after you try to run `docker run -it griffithlab/pvactools`?

**Comment by ahua217** [comment]
Yes. This is the full output message
Unable to find image 'griffithlab/pvactools:latest' locally
latest: Pulling from griffithlab/pvactools
cc1a78bfd46b: Downloading [==================================================>]  11.08MB/11.08MB
49eab01d36f3: Downloading [==================================================>]  38.14MB/38.14MB
c2c2cfea0213: Downloading [==================================================>]  59.06MB/59.06MB
419499c9a4cf: Download complete
f7550509e92e: Download complete
aa254197193e: Downloading [==================================================>]  73.97MB/73.97MB
e900eced2cc3: Downloading [==================================================>]  80.13MB/80.13MB
d10b72843f99: Download complete
241d293f87df: Download complete
8db6b8706f82: Downloading [==================================================>]  263.6MB/263.6MB
28cbf9abcbfc: Downloading [==================================================>]  250.6MB/250.6MB
972594feec3a: Download complete
548611ff4ff7: Download complete
3cdce2f13d3f: Download complete
7d949fac8a4a: Downloading [==================================================>]  271.2MB/271.2MB
a4863abe2ad6: Downloading [==================================================>]    261MB/261MB
f9f2182203d7: Download complete
7a8dca71d1b7: Download complete
8f67dc9b8393: Download complete
432451f20597: Download complete
27d8cecd5f48: Downloading [>                                                  ]  2.677MB/1.417GB
b57ce694bb67: Downloading [==================================================>]  276.5MB/276.5MB
docker: unexpected EOF.
See 'docker run --help'.

**Comment by ahua217** [comment]
The second last downloading just stuck there without further retries.

**Comment by susannasiebert** [comment]
I wonder if this might be caused by a slow internet connection? You might want to try one or both of the things suggested int his comment: https://stackoverflow.com/a/62763902

**Comment by susannasiebert** [comment]
If this doesn't fix it, you can try building your own version of the docker container locally by checking out the pVACtools docker repository: https://github.com/griffithlab/docker-pvactools
```
git clone git@github.com:griffithlab/docker-pvactools.git
cd docker-pvactools
docker build .
```
This will output a bunch of log messages but the last message should be something along the lines of:
```
Successfully built XXXX
```
where `XXXX` is a build hash of your docker build. You can then run this docker image with `docker run -it XXXX` (replace `XXXX` with the actual build hash from above)

**Comment by ahua217** [comment]
Hi Susan, thank you for your suggestion. I already tried the first method from the stackoverflow link, and my last post was actually what after this. It looks my internet network is too weak. I will try your second suggestion. Thanks!

**Comment by ahua217** [comment]
Hi Susan, I still got some problems when trying the git clone method:`$ git clone git@github.com:griffithlab/docker-pvactools.git`

Cloning into 'docker-pvactools'...
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Fortunately, my wifi works faster now and I swithced back to `docker run -it griffithlab/pvactool`. And this time it complete the pulling and so on. My next question is what is the best practice for first-time user to use pvactools? I should enter `docker run -it griffithlab/pvactool` at every begining, right? I found "ahua217@DESKTOP-CVSDKH5:" is gone after this and I enter the commands as below.
`pvacseq download_example_data /data/`
`pvacseq run pvacseq_example_data/input.vcf Test HLA-G*01:09,HLA-E*01:01,H2-IAb NetMHC PickPocket NNalign example_output/ -e 9,10 -i pvacseq_example_data/additional_input_file_list.yaml --tdna-vaf 20 --net-chop-method cterm --netmhc-stab --top-score-metric=lowest -d full --keep-tmp-files --iedb-install-directory /data/`

But there is no any response and the lines are just quite until I close the terminal. Could you please give me some advice as a start?
Thank you very much!

**Comment by susannasiebert** [comment]
The first thing I'm noticing is that you are using an old option (`-i pvacseq_example_data/additional_input_file_list.yaml`) that is no longer supported in pVACtools. In addition, the `--tdna-vaf` parameter in the current version is a decimal fraction instead of an integer percentage so you will want to use `--tdna-vaf 0.2`. Are you using an old documentation? Please see https://pvactools.readthedocs.io/en/latest/pvacseq/getting_started.html for the current version of the documentation.

Using the nonexistent `-i` option should normally abort your run and show you the command prompt again.

<img width="1462" alt="Screen Shot 2021-01-11 at 9 38 54 AM" src="https://user-images.githubusercontent.com/6617192/104202692-dbcf8980-53f0-11eb-85e7-b09491b4ce0e.png">

Can you maybe post a screenshot of what your terminal output looks like?

**Comment by ahua217** [comment]
Really appreciate you for sharing the screenshot! I tried to follow what you entered but nothing came out from the beginning docker run. Even my command prompt was gone.
![image](https://user-images.githubusercontent.com/71511628/104208058-7edad000-53fe-11eb-855e-be60caad5cb0.png)
My computer was not frozen and I can still type anything in this status.
![image](https://user-images.githubusercontent.com/71511628/104210416-dbd78580-5400-11eb-9681-ab97506182a1.png)
But it looks none of the command line works.
I noticed the current document is indeed different from what I referred two days ago. I guess what I primarily used in my last post was old document.
Looking forward to further suggestion.
Thank you so much!

**Comment by susannasiebert** [comment]
To me it looks like your docker container is not even booting up correctly. Notice how I get a new command prompt from inside my docker container that looks like this `(base) root@d4d6f74d8b57:/opt/iedb#`. After you run your `docker run -it griffithlab/pvactools` you don't appear to get this prompt. It appears docker is still trying to boot up that image. Are you able to execute other docker commands such as `docker images`?

**Comment by ahua217** [comment]
My `docker images` returned nothing as before. But `docker --help` gave somethings.
![image](https://user-images.githubusercontent.com/71511628/104212876-b0a26580-5403-11eb-9e63-e34f1459e95c.png)

**Comment by ahua217** [comment]
I set my docker as this link
https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly
I remember my first try of `dock run` gave something  like this `(base) root@d4d6f74d8b57:/opt/iedb# ` , but at that time the machine was very slow. I closed the terminal and restarted my computer, and there is the problem in this post.

**Comment by susannasiebert** [comment]
Hm, unfortunately, I'm not sure that we can provide much help here since this is a problem with docker itself, not with pVACtools. This link here (https://linuxandevops.wordpress.com/2017/05/08/docker-all-commands-hangs/) seems to describe a similar situation to yours.

**Comment by ahua217** [comment]
Thank you Susan. As what you indicated, I reinstalled my docker and now it runs smoothly and I got my first result from pvactools sample data. Hooray! Thank you for your patience and help!
