### ISSUE TITLE
Improvements for aggregate report (visualization) 

### ISSUE THREAD

**Issue by huimingx** [griffithlab/pVACtools#632]
1. Variant Information to be added in main tsv (HGVS.c)
2. Add gene expression entry to metric file
3. change underscore to spaces in main tsv header (Huiming to check why HLA allele names are being changed) 

Additional Questions:
1. What does the number of HLA allele under each column in main tsv mean?
2. Transcript Expression is the same across all good binding transcripts?

**Comment by susannasiebert** [comment]
- RNA VAF * Gene Expression column to the right of the RNA VAF
- In the metrics file: 
  - transcript expression as a list in the same order as `good_binders_transcripts`
- If there is no wildtype sequence, instead of displaying NA, display `FS-NA` or `INS-NA` (depending on variant type).

**Comment by susannasiebert** [comment]
I think all of these have been added to the `aggregate_metrics` branch here (https://github.com/griffithlab/pVACtools/tree/aggregate_metrics).
