### ISSUE TITLE
New feature for aggregate report 

### ISSUE THREAD

**Issue by huimingx** [griffithlab/pVACtools#633]
Binding affinity across different algorithms to be added to metrics file for display

**Comment by susannasiebert** [comment]
For MT peptides only:
```
"peptide1": {
  "individual_calls: {
    "WT": {
      "HLA1: [
        ic50_1,
        ic50_2,
        [...],
      ],
      "algorithms": [
      ]
    }
    "MT": {
...
```

**Comment by susannasiebert** [comment]
I think all of these have been added to the `aggregate_metrics` branch here (https://github.com/griffithlab/pVACtools/tree/aggregate_metrics).
