### ISSUE TITLE
Error when processing proximal variant

### ISSUE THREAD

**Issue by zhangyafeng1** [griffithlab/pVACtools#636]
hello:
I had this error when I used pvacseq for analysis :

![image](https://user-images.githubusercontent.com/52239895/105978709-d13e1100-60cd-11eb-8303-e735e62488b7.png)

"Using TensorFlow backend.
Error when processing proximal variant.
The wildtype amino acid for variant 1710.IFITM1.ENST00000408968.3.FS.13-14GCCAC/G with substring KEEHEVAVLG is different than expected.
Actual wildtype amino acid: E
Wildtype amino acid of the proximal_variant: P
"

I don't know what caused it. Could you help me see how I should rule out it ?
Thank you !!

**Comment by susannasiebert** [comment]
Can you confirm that the proximal VCF was annotated with the exact same VEP version, VEP cache, and VEP command as the main somatic input VCF?

**Comment by susannasiebert** [comment]
I will be closing this issue since there has been no further activity on it. Please do feel free to reopen if you're still running into this error.
