### ISSUE TITLE
Alter the ranking script to degrade gracefully when there is no expression data

### ISSUE THREAD

**Issue by chrisamiller** [griffithlab/pVACtools#643]
Right now, everything just gets binned into the no expression group, but that's not particularly useful.

**Comment by susannasiebert** [comment]
I would like to tackle this issue next. We currently backfill certain columns with NAs as 0. These are `Tumor RNA Depth`, `Tumor RNA VAF`, `Tumor DNA VAF`, `Gene Expression`. Tiers are then calculated as usual so any filtering/tiers involving one or more of these criteria will fail. Do we want to skip any criteria when the value is NA and only test the rest of the criteria for each tier?

**Comment by chrisamiller** [comment]
That seems right - any test that relies on expression or RNA VAF/Depth would just be skipped if the entire experiment has no RNAseq data.  There should probably also be a flag `--ignore-rna-in-tiering`(?) that allows for tiering to treat the experiment as if it has no RNA (even if some of those values exist) - this could be useful when the RNA is of really poor quality.

**Comment by susannasiebert** [comment]
@chrisamiller I made a new issue for your suggestion (#910). I will be closing this issue since everything else has been implemented.
