### ISSUE TITLE
pVACseq 2.0.0 can't find genotype (GT) in VCF file

### ISSUE THREAD

**Issue by venkataddala** [griffithlab/pVACtools#647]
Hello, 

I'm facing this issue wtith recent pVACtool 2.0.0, I can see genotype info in VCF file (attached here). 
Could you please have a look and let me know If i'm missing anything here.

Run command:
`pvacseq run --iedb-install-directory /software/IEDB_MHC/IEDB_MHC-20190827 -c 1 -t 8 -e1 9 --netmhc-stab --net-chop-method cterm --allele-specific-binding-thresholds --run-reference-proteome-similarity TestSample_VEP88_pVAC2_0.vcf TestSampleID HLA-A*02:01 NetMHCpan OutDirectory`

Error
Executing MHC Class I predictions
Converting .vcf to TSV
VCF doesn't contain any sample genotype information. Add a dummy sample using the vcf-genotype-annotator tool available as part of the vatools package.

Used VEP88, Plugins --Framshif, Wildtype (Rest as mentioned in VEP pVAC support page) 
[TestSample_VEP88_pVAC2_0.vcf.gz](https://github.com/griffithlab/pVACtools/files/5994217/TestSample_VEP88_pVAC2_0.vcf.gz)

**Comment by susannasiebert** [comment]
Your VCF file is malformed. It is missing the header definition lines for the `GT` field, as well as almost all other INFO and FORMAT fields used in your entries.

**Comment by malachig** [comment]
Not sure what you workflow is here, occasionally we have variants that been converted to tabular format and then further analyzed, filtered before doing neoantigen analysis.  When I have done this, I have recreated a VCF of the variants of interest by going back to the original VCF and grabbing the entire header and variant records of interest to avoid this kind of problem.
