### ISSUE TITLE
--netmhc-stab doesn't work

### ISSUE THREAD

**Issue by TinaGuo-hku** [griffithlab/pVACtools#648]
Below is my commends to run a fasta file:
pvacbind run A0201.fasta Test HLA-A*02:01 MHCflurry MHCnuggetsI MHCnuggetsII NNalign NetMHC PickPocket SMM SMMPMBEC SMMalign A0201 -e1 9,10,11 --netmhc-stab

it works well on making binding predictions on allele, but when running NetMHCStabPan, there are some issues:

raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.cbs.dtu.dk', port=80): Max retries exceeded with url: /cgi-bin/webface2.fcgi (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa6c4692390>: Failed to establish a new connection: [Errno 60] Operation timed out'))

I double checked my internet connect, it works well. 
Could you please help me out?

**Comment by venkataddala** [comment]
I do have the same issue when i'm running with `--netmhc-stab --net-chop-method cterm --allele-specific-binding-thresholds --run-reference-proteome-similarity` and filtered.tsv file is blank only with headers

**Comment by susannasiebert** [comment]
It looks like the NetMHCstabpan server was down last night but has since recovered. pVACtools uses that website to make stability predictions. Now that the site is back up, please try again and see if that resolves your issue.

**Comment by venkataddala** [comment]
I ran again just now and NetMHCstab up and running on their site. I can see  all_epitopes.aggregated.tsv,  all_epitopes.tsv, but no sign of filtered.tsv.reference_matches file and blank filtered.tsv file

**Comment by TinaGuo-hku** [comment]
Solved. Thank you.

**Comment by TinaGuo-hku** [comment]
> I do have the same issue when i'm running with `--netmhc-stab --net-chop-method cterm --allele-specific-binding-thresholds --run-reference-proteome-similarity` and filtered.tsv file is blank only with headers

same thing here. All filtered.tsv files are blank with only headers.

**Comment by susannasiebert** [comment]
This usually means that none of your epitope candidates passed our default filters. For a list of filters that are being applied please see the documentation [here](https://pvactools.readthedocs.io/en/latest/pvacseq/output_files.html#filters-applied-to-the-filtered-tsv-file). You can try running the [standalone filter commands](https://pvactools.readthedocs.io/en/latest/pvacseq/filter_commands.html#filter-commands) on your all_epitopes file to get a better idea which filter your candidates are failing.

**Comment by TinaGuo-hku** [comment]
> This usually means that none of your epitope candidates passed our default filters. For a list of filters that are being applied please see the documentation [here](https://pvactools.readthedocs.io/en/latest/pvacseq/output_files.html#filters-applied-to-the-filtered-tsv-file). You can try running the [standalone filter commands](https://pvactools.readthedocs.io/en/latest/pvacseq/filter_commands.html#filter-commands) on your all_epitopes file to get a better idea which filter your candidates are failing.

Thanks for your reply. However, I don't agree that none of my epitope candidates passed our default filters since I ran the same fasta file early this week, everything went well : I got couple epitopes remained. But after the NetMHCstabpan server was down (even though it works right now), the filtered.tsv becomes empty now. And it doesn't make sense that everybody here got the same empty filtered.tsv

**Comment by susannasiebert** [comment]
I've confirmed that using the `--netmhc-stab` option results in an empty filtered file.

**Comment by susannasiebert** [comment]
Even though the old NetMHCstabpan server is still online, it doesn't appear to currently return any results. It appears that the tool is being moved to a different url. PR #650 switches NetMHCstabpan and NetChop to use their new URLs which appears to fix this issue. I plan on making a hotfix release on Monday.

**Comment by malachig** [comment]
Thanks for this report @TinaGuo-hku

**Comment by susannasiebert** [comment]
@TinaGuo-hku @venkataddala I just release pVACtools 2.0.1 which uses the new server addresses for NetChop and NetMHCstabpan. Please give that version a try and let me know if that fixes this issue.

**Comment by TinaGuo-hku** [comment]
> @TinaGuo-hku @venkataddala I just release pVACtools 2.0.1 which uses the new server addresses for NetChop and NetMHCstabpan. Please give that version a try and let me know if that fixes this issue.

Hi, I tried the new version. It solved this issue. Thank you !

**Comment by susannasiebert** [comment]
Wonderful. Thank you.
