### ISSUE TITLE
generate_protein_fasta returns no fasta sequence for some variants

### ISSUE THREAD

**Issue by boyangzhao** [griffithlab/pVACtools#651]
* pvactools version: 2.0.0
* Docker: griffithlab/pvactools:2.0.0

**Describe the bug**
For a noticeable number of variants, using the pvacseq generate_protein_fasta tool to retrieve fasta of longer peptide sequences return no sequences. The tool does work generally and we do get a large number of variants with the right flanking sequences. But some variants, these are protein coding, and should return a sequence, but somehow the tool is not returning the sequence.

**To Reproduce**
I've isolated 7 examples and attached are vcf.gz, vcf.gz.tbi, and .tsv files which can be used as direct input to pvacseq, and it returns an empty fasta file. The run was executed via running the CWLs. The extracted commands look something like this,

ln -s $TMPDIR /tmp/pvacseq && export TMPDIR=/tmp/pvacseq && /usr/local/bin/pvacseq generate_protein_fasta --input-tsv problems.tsv --sample-name TESLApt1_tumor problems_filtered.vcf.gz 30 test.fasta

**Output File**
If you run these example problematic ones, returns empty fasta and manufacturability.tsv files.
[problems_filtered.vcf.gz](https://github.com/griffithlab/pVACtools/files/6078194/problems_filtered.vcf.gz)

[problems.zip](https://github.com/griffithlab/pVACtools/files/6078197/problems.zip)

**Comment by susannasiebert** [comment]
Thank you for this report. 

The generate_protein_fasta command depends on the input VCF being the exact same as the one used to create the input TSV. Because the provided VCF only has a subset of entries the unique identifiers that are used to match up the TSV entries to their respective VCF entries don't match up anymore.

When you run your command with the full VCF and the problems.tsv, do you see the same behavior? You should be getting results for 5 out of the 7 TSV entries. The other two are getting filtered out because at a flanking sequence length of 30 their sequences now include a `*` which results in these sequences getting filtered out. `565.LGI4.ENST00000587780.5.missense.20E/K` and `571.IFNL4.ENST00000634680.1.missense.22E/K` are both affected by this.

**Comment by boyangzhao** [comment]
Thanks! Is this related to the Index column in the tsv file? With the full vcf (also attached), where in for example `565.LGI4.ENST00000587780.5.missense.20E/K`, 565 is an index in reference to the position (row) in the original full vcf file? With the full VCF, it was the same behavior where these examples returned a blank fasta.

As for the filtering, if the flanking sequence length is larger than the possible length (because of epitope nearing start or terminal aa), does it get filtered out or can it output the length that is possible, up to the flanking length as max?

[_2_annotated_filtered.vcf.gz](https://github.com/griffithlab/pVACtools/files/6105082/_2_annotated_filtered.vcf.gz)

**Comment by susannasiebert** [comment]
Yes, the Index column is used to make that association. The number is a counter in regards to all variant-transcript combinations in the input VCF that are processable by pVACseq. If you look at the `index` column in the in the intermediate <sample_name>.tsv file in your MHC directory, you will notice how that counter corresponds to the line number in that tsv.

In regards to the length, this command works as you're describing. pVACseq is able to handle cases with the mutation position near the beginning or end of the transcript and will just output a shorter flanking sequence at the respective start/end.

**Comment by boyangzhao** [comment]
>  The other two are getting filtered out because at a flanking sequence length of 30 their sequences now include a `*` which results in these sequences getting filtered out. `565.LGI4.ENST00000587780.5.missense.20E/K` and `571.IFNL4.ENST00000634680.1.missense.22E/K` are both affected by this.

Thanks! - I've used a slightly different vcf connection in my workflow, so indeed resulted in some mismatch in the Index ids. It's fixed on my end. One question, can you clarify a bit on what did you mean by those two examples with 30 flanking seq length, now includes a * and gets filtered out? It's entering into a stop codon? Or the * meant something else? 

I've checked for the ENST00000587780.5, below is the entry in CSQ in the vcf, including the wt seq.

`T|missense_variant|MODERATE|LGI4|ENSG00000153902|Transcript|ENST00000587780.5|protein_coding|2/6||ENST00000587780.5%3Ac.58G>A|ENSP00000467044.2%3Ap.Glu20Lys|57|58|20|E/K|Gag/Aag|rs775813102&COSM1213298||-1|cds_start_NF||SNV|HGNC|HGNC%3A18712|||1|||ENSP00000467044||K7ENQ0|UPI000333517E|1|deleterious(0.01)|possibly_damaging(0.78)|Gene3D%3A3.80.10.10&Pfam_domain%3APF13855&PROSITE_profiles%3APS51450&hmmpanther%3APTHR24367&hmmpanther%3APTHR24367%3ASF268&SMART_domains%3ASM00369&Superfamily_domains%3ASSF52058|||||||||||5.481e-06|9.662e-05|0|0|0|0|0|0|0|9.662e-05|gnomAD_AFR||0&1|0&1|||||||||XVIEDDAFAGLSHLQYLFIEDNEIGSISKNALRGLRSLTHLSLANNHLETLPRFLFRGLDTLTHVDLRGNPFQCDCRVLWLLQWMPTVNASVGTGACAGPASLSHMQLHHLDPKTFKCRAIELSWFQTVGESALSVEPFSYQGEPHIVLAQPFAGRCLILSWDYSLQRFRPEEELPAASVVSCKPLVLGPSLFVLAARLWGGSQLWARPSPGLRLAPTQTLAPRRLLRPNDAELLWLEGQPCFVVADASKAGSTTLLCRDGPGFYPHQSLHAWHRDTDAEALELDGRPHLLLASASQRPVLFHWTGGRFERRTDIPEAEDVYATRHFQAGGDVFLCLTRYIGDSMVRLGLGAGGWLFSTDPILHTKPLNSDLPSHADL`

**Comment by susannasiebert** [comment]
I must've been mistaken in my first debugging then. On second check, it looks like only transcript `ENST00000634680.1` has this problem. The wildtype amino acid sequence for this transcript in your original VCF is `MRPSVWAAVAAGLWVLCTVIAEGPPALPALALPLAGAPDAGGCQGAEGPLRGRGAELGAAQLLLPPQEGSSAAIA*AGTARLLQEGPRGPEEASQTPESGLASVPQSQRGLQPPAPAHVGAPAGCTLWALPL`. I believe this is supposed to represent a stop codon but it's odd that this would appear in the middle of the sequence. pVACseq filters such sequences out proactively since they appear to be problematic.

**Comment by boyangzhao** [comment]
Ah ok, thanks! When I shorten the flanking length, it seems I can get the sequences for all the variants. For the other variant with transcript `ENST00000587780.5`, where the wild type aa sequence starts with `XVIEDDAFAGLSHLQ...`, is it because the first aa is `X` that pVACseq would filter this out? And I presume issue with the `X` and * has something to do with VEP? As these were annotated with VEP, and using the Wildtype plugin.

**Comment by susannasiebert** [comment]
yes, that could be the issue for `ENST00000587780.5`. pVACseq does filter out sequences with `X` in it.

The sequence does come from the Wildtype plugin, which is a custom plugin which should just take the Ensembl nucleotide sequence for that transcript and translate it. I would need to look into the nucleotide sequences for these transcripts to determine why they are resolved to this amino acid sequence.

**Comment by boyangzhao** [comment]
Thanks- yes it was mainly a bug in my cwl that is now fixed. There are cases where the plugin returns those X or *, but they're not often observed.
