### ISSUE TITLE
Mutation to peptide sequence without binding prediciton

### ISSUE THREAD

**Issue by marshelma** [griffithlab/pVACtools#653]
Is it possible to just get the WT and Mut peptide pairs (28mer with the mutation in the middle) that generated by the mutation without binding prediction?

**Comment by susannasiebert** [comment]
Yes! Please use the `pvacseq generate_protein_fasta` command for this use case. The documentation for this command can be found [here](https://pvactools.readthedocs.io/en/latest/pvacseq/optional_downstream_analysis_tools.html#generate-protein-fasta).

**Comment by marshelma** [comment]
> Yes! Please use the `pvacseq generate_protein_fasta` command for this use case. The documentation for this command can be found [here](https://pvactools.readthedocs.io/en/latest/pvacseq/optional_downstream_analysis_tools.html#generate-protein-fasta).

Thank you so much!
