### ISSUE TITLE
vt error decompose biallelic block substitutions into its constituent SNPs

### ISSUE THREAD

**Issue by worker000000** [griffithlab/pVACtools#654]
in vt wiki , it said Decomposes biallelic block substitutions into its constituent SNPs. this is not always suitable to do so, and the author gives 2 added args -m and -d , 
![image](https://user-images.githubusercontent.com/25199946/113433814-7947c180-9412-11eb-9218-9c46b5a36bce.png)

but in your docs, it seems missed this part, should I add? 
![image](https://user-images.githubusercontent.com/25199946/113433746-574e3f00-9412-11eb-90c1-01ea0ec3a158.png)
Thanks a lot

**Comment by susannasiebert** [comment]
I just realized, that the documentation you posted is for a totally different command. We are using `vt decompose` and the command you posted is for `vt decompose_blocksub`. I don't believe that this issue affects the `vt decompose` command. I'm closing this issue.
