### ISSUE TITLE
Evaluate NextProt as a possible alternative to BLAST for assessing uniqueness of neoantigen within the wild type proteome

### ISSUE THREAD

**Issue by malachig** [griffithlab/pVACtools#671]
The neXtProt peptide uniqueness checker: a tool for the proteomics community

https://www.nextprot.org/

Has a web form implementation, and API, and a standalone tool implemented in C:
https://github.com/calipho-sib/pepx

**Comment by susannasiebert** [comment]
I'm planning on running a all_eptiopes file through blastp and compare the output to nextprot to see if it finds the same hits.

**Comment by susannasiebert** [comment]
Closing in favor of using a reference proteome fasta to string search against.
