### ISSUE TITLE
Package naming pollutes python package namespace with very common names

### ISSUE THREAD

**Issue by rpep** [griffithlab/pVACtools#698]
* pvactools version: all
* Python version: all
* Operating System: all

**Describe the bug**
Not really a bug, but the current layout + design of pVACTools means that:
```
import tools
import utils
import lib
```
all import packages from pVACTools. Because these are very common names for parts of other packages + python files internally, it's very likely to at least confuse people. It can easily be rectified by moving the folders within a 'pvactools' folder at the top level, and naming the packages for e.g. 'pvactools.tools', 'pvactools.utils', 'pvactools.lib'

**Comment by susannasiebert** [comment]
Thank you for this suggestion. I think this would be a good problem to resolve with our next major release. I will add it to that milestone.

**Comment by susannasiebert** [comment]
#714 addresses this issue. This fix will be released with our next major version.

**Comment by rpep** [comment]
Thanks!
