### ISSUE TITLE
Update mutation position column or create new column with all mutated positions

### ISSUE THREAD

**Issue by huimingx** [griffithlab/pVACtools#701]
Currently the mutation position column only shows where the mutation starts. In the case of frameshift or small indels, this does not show all the positions differing between the MT and WT peptide. 

A new approach would be to update the mutation position column or make a new column that lists or gives a range for the mutated aa in an epitope.

**Comment by susannasiebert** [comment]
We would then use the updated/new column to identify anchor sites more precisely for tiering during aggregate report creation as well as in the anchor highlighting in pVACview.
