### ISSUE TITLE
Parallelize the calls made to IEDB

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVACtools#72]
Original issue: https://github.com/griffithlab/pVAC-Seq/issues/162

We have users that want to run pvacseq with all alleles, all methods, and all epitope lengths. Right now this results in thousands of call_iedb calls that are run in serial. In order to reduce runtime we should explore threading those calls.

An example for threading was implemented by @agraubert for NetChop.

**Comment by malachig** [comment]
We have been processing some melanoma case recently where we somewhat routinely have thousands of variants to consider.  We can break the variants into chunks run pvactools in threads and cat the results together at the end.  But it would be really nice if pvactools had a threading option that would handle this for you.

**Comment by jasonwalker80** [comment]
A user at MGI reported long running vaccine design processes. @susannasiebert can you work with Mike McLellan to determine the cause of the long running process. Perhaps using multiple threads is a solution to his issue as well.

**Comment by susannasiebert** [comment]
Multithreading has been implemented in version 1.2.0 (`--n-threads` parameter`).
