### ISSUE TITLE
pVACseq: Generating Variant Peptide FASTA and Key File. Error when processing proximal DNV variant.

### ISSUE THREAD

**Issue by tetsuro90** [griffithlab/pVACtools#721]
Hi, while running pVACseq, the following error occurred.

* pvactools version: docker image pVACtools:2.0.4
* Operating System: ubuntu 20.04

**Describe the bug**
The error occurred in the `add_proximal_variants` function in "fasta_generator.py".
I investigated which mutation was causing the error, and found that it was happening when processing two specific proximal mutations.
* mutation ... missense SNV
* phased mutation ... missense DNP (e.g. GC -> AT)
It seems that this was caused by the fact that the protein position index of the phasing mutation was a string (i.e. "192-193").

Since mutations other than SNVs are not subject to phasing, I thought the following process was not necessary for phased mutation or phased SNPs. 
```
position = int(line['protein_position'].split('-', 1)[0]) - 1
```
However, am I correct in understanding that DNP is also targeted?

**To Reproduce**
If necessary, send a mutation vcf and a phased vcf with only the minimum information.

**Log Output**
```
Completed
Generating Variant Peptide FASTA and Key File
Traceback (most recent call last):
  File “/usr/local/bin/pvacseq”, line 8, in <module>
    sys.exit(main())
  File “/usr/local/lib/python3.7/site-packages/tools/pvacseq/main.py”, line 95, in main
    args[0].func.main(args[1])
  File “/usr/local/lib/python3.7/site-packages/tools/pvacseq/run.py”, line 122, in main
    pipeline.execute()
  File “/usr/local/lib/python3.7/site-packages/lib/pipeline.py”, line 458, in execute
    self.generate_combined_fasta()
  File “/usr/local/lib/python3.7/site-packages/lib/pipeline.py”, line 173, in generate_combined_fasta
    generate_combined_fasta.main(params)
  File “/usr/local/lib/python3.7/site-packages/tools/pvacseq/generate_protein_fasta.py”, line 155, in main
    generate_fasta(args.flanking_sequence_length, downstream_sequence_length, temp_dir, proximal_variants_tsv)
  File “/usr/local/lib/python3.7/site-packages/tools/pvacseq/generate_protein_fasta.py”, line 102, in generate_fasta
    fasta_generator.execute()
  File “/usr/local/lib/python3.7/site-packages/lib/fasta_generator.py”, line 215, in execute
    wildtype_subsequence_with_proximal_variants = self.add_proximal_variants(line[‘index’], wildtype_subsequence, mutation_start_position, position, False)
  File “/usr/local/lib/python3.7/site-packages/lib/fasta_generator.py”, line 114, in add_proximal_variants
    proximal_variant_position = int(protein_position) - 1 - mutation_offset
ValueError: invalid literal for int() with base 10: ‘192-193’
```

Thanks,

**Comment by susannasiebert** [comment]
I apologize for the delay in addressing this issue. It slipped through the cracks. I made a PR (#754) to fix this issue and will make a new bugfix release next week.

**Comment by tetsuro90** [comment]
@susannasiebert 
Thank you very much.
I'll check when it's updated.

**Comment by susannasiebert** [comment]
@tetsuro90 I made a new hotfix release 2.0.6 that should resolve this issue. Please give it a try and let me know should you still run into any problems.
