### ISSUE TITLE
Unexpected return value from NetMHCstabpan server

### ISSUE THREAD

**Issue by asmlgkj** [griffithlab/pVACtools#725]
Thanks a lot.

after change the method from  NetMHCpan to MHCnuggetsI
<br>
command
<br>
docker run --rm --user id -u:id -g -v $4:/data docker.io/griffithlab/pvactools pvacseq run /data/$3 $1 ${content_hla}  MHCnuggetsI  /data/pvacseq -e1 8,9,10,11 --iedb-install-directory /opt/iedb -t 4 --tdna-vaf 0.01 --normal-sample-name $1_N -k --downstream-sequence-length 1000 -c 1 --exclude-NAs --netmhc-stab --net-chop-method cterm
<br>
the cannot fork disappers, but I still do not know how to solve the problem.
<br>
but new error comes, 
<br>
    raise Exception("Unexpected return value from NetMHCstabpan server. Unable to parse response.\n{}".format(response.content.decode()))
Exception: Unexpected return value from NetMHCstabpan server. Unable to parse response.
![image](https://user-images.githubusercontent.com/50854682/138088286-81c0ec43-6001-4c85-80fd-2286286e11d5.png)

**Comment by rbowenj** [comment]
I am also encountering this issue. 
Roughly half the pVACtools jobs I run error out with this NetMHCStabPan exception, but the other half don't. Usually rerunning a failed job overcomes the issue.
