### ISSUE TITLE
"Tier" value in the final report is not consistent with "RNA_expr "

### ISSUE THREAD

**Issue by gudeqing** [griffithlab/pVACtools#727]
Hi:
* pvactools version: 2.0.4
* Python version: 3.7
* Operating System:  latest docker image used

**Describe the bug**
"Tier" value in the final report is not consistent with "RNA_expr ". 
I guess this maybe caused by No RNA_VAF provided since you may calculate this by "RNA-expr*RNA_VAF" ?

**To Reproduce**
vcf having gene expression but no RNA_VAF and RNA_Depth

**Output File**
![image](https://user-images.githubusercontent.com/30919159/138235760-32f2f90d-9215-47e1-bd5b-8d7ad779740d.png)

**Expected behavior**
"Tier" value in the final report is consistent with "RNA_expr ".

**Comment by susannasiebert** [comment]
You are correct that the aggregate report's definition of "Expression" is defined as "RNA-expr*RNA_VAF"  so if either of those or 0 or NA the variant gets binned in the NoExpr tier. The naming is confusing. We've started to call this new metric "Allele Expression" and with our next release will be including this metric in the aggregate report as an additional output column. Would it makes things easier to understand if we then also renamed the tier to be "NoAlleleExpr", "LowAlleleExpr", etc?
