### ISSUE TITLE
Report NetMHCstabpan distance metric when different HLA allele was picked

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVACtools#732]
NetMHCstabpan was only trained on a few HLA alleles. When running an unsupported allele it will pick the nearest neighbor and report a distance metric which would indicate how good of a match the picked HLA allele is to the patient HLA allele, which would indicate reliability of the results.

One option is to report the distance in our filtered output files. There, we we could add it to the existing `NetMHCstab Allele` column, which already reports the allele chosen by NetMHCstabpan. This could take a format like so: `HLAxxx (distance: x.xx)`

Alternatively, we could write this information to the stdout in a message like so:
```
15 variants processed from vcf abcde.vcf.gz
3 HLA Class I alleles used: HLA-A*1:23 , HLA-B*2:34
12345 peptides checked using 8 algorithms
456 peptides passed all filters
NetMHCstabpan substituted HLA-C*2:01 for HLA-C*2:02 (distance: x.xx)
Tiering report created with 9 PASS peptides
Successfully completed
```
As shown above, such a message could contain additional helpful data unrelated to NetMHCstabpan

**Comment by malachig** [comment]
I believe this same concept also applies to NetMHCpan itself.  It also has data for only some alleles and must sometimes pick a closest neighbor.  It then reports the distance.  

You can see this under the output format tab here:
https://services.healthtech.dtu.dk/service.php?NetMHCpan-4.1
