### ISSUE TITLE
how pvacseq  select netchop result

### ISSUE THREAD

**Issue by asmlgkj** [griffithlab/pVACtools#738]
Thanks a lot for developing such a powerful tool.
I am a little confused when pvacseq used netchop to predict the netchop score.

for example,  a fasta sequnece

<br>
$cat test.txt1

\>KAVYNFATC
FQPQNGQFI
<br>
command
<br>
netchop test.txt1 > test.myout12
<br>
result is
NetChop 3.0 predictions using version C-term. Threshold 0.500000

--------------------------------------
 pos  AA  C      score      Ident
--------------------------------------
   1   F  S   0.678299  KAVYNFATC
   2   Q  .   0.023621  KAVYNFATC
   3   P  .   0.066250  KAVYNFATC
   4   Q  .   0.078159  KAVYNFATC
   5   N  .   0.034841  KAVYNFATC
   6   G  .   0.040971  KAVYNFATC
   7   Q  .   0.264217  KAVYNFATC
   8   F  S   0.704804  KAVYNFATC
   9   I  .   0.355054  KAVYNFATC
--------------------------------------

Number of cleavage sites 2. Number of amino acids 9. Protein name KAVYNFATC
<br>
how will pvacseq give the score for this peptide?

**Comment by susannasiebert** [comment]
Running NetChop will output 3 additional columns in the pVACseq filtered report ([documentation](https://pvactools.readthedocs.io/en/latest/pvacseq/output_files.html#all-epitopes-tsv-and-filtered-tsv-report-columns)):

>Best Cleavage Position: Position of the highest predicted cleavage score
Best Cleavage Score: Highest predicted cleavage score
Cleavage Sites: List of all cleavage positions and their cleavage score where the cleavage score is above the chosen threshold (`--net-chop-threshold`)

**Comment by asmlgkj** [comment]
thanks  a lot
