### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by d88020** [griffithlab/pVACtools#739]
* pvactools version: 2.0.4
* Python version: 3.7.11
* Operating System: ubuntu 14

Hi.
I used pvacseq with about 200 samples.
But I got an error message with one sample only.
I captured the error message.
![error_capture_P161](https://user-images.githubusercontent.com/42161370/143512431-86b5895e-b5c4-4d25-8f22-7ef6477e9944.png)

I add the input vep annotated vcf file that I used. 
[Input_vcf.zip](https://github.com/griffithlab/pVACtools/files/7605682/Input_vcf.zip)

**Comment by susannasiebert** [comment]
Thank you for this error report. I made a pull request to fix this issue (#740) and hope to get a new hotfix version out in the next couple of days.

**Comment by susannasiebert** [comment]
I a new version if pVACtools (2.0.5) has been released which should fix this error.
