### ISSUE TITLE
pip install pvactools not work

### ISSUE THREAD

**Issue by agnesfoi** [griffithlab/pVACtools#746]
The latest version of pvactool cannot be installed with the Conda environment.

I have tried to install several pvactool versions in different conda environments, but the installation stopped every time at "pip is looking at multiple versions of aaa packages". 

I appreciate your help. Thanks in advance !

**Comment by susannasiebert** [comment]
This is, unfortunately, a problem when using newer versions of pip. In this situation we recommend using the `-r` option with the requirements.txt file in the master branch of the repo.

**Comment by agnesfoi** [comment]
Thanks very much!

**Comment by susannasiebert** [comment]
Glad it worked.
