### ISSUE TITLE
Exception handling if with wrong input_file parameter in "pvacfuse run" command

### ISSUE THREAD

**Issue by gschang** [griffithlab/pVACtools#747]
* pvactools docker image: `susannakiwala/pvactools:3.0.0rc6`
* Systems: WashU RIS compute0/storage0

**No exception handling if with wrong input_file parameter in "pvacfuse run" command**

`pvacfuse run` command doesn't show any error message if a user feeds a wrong input_file parameter, which actually doesn't exist. It ends up with empty outputs but without any error message. This wrong input_file parameter can happen by user's mistake.

**Example command to reproduce with "./3.annotate_NOT_EXIST**

$ /usr/local/bin/pvacfuse run --iedb-install-directory /opt/iedb 
        -b 500 -d 100
        -e1 8,9,10,11
        -e2 12,13,14,15,16,17,18
        --n-threads 8 -m lowest
        `./3.annotate_NOT_EXIST`                                      <<< user enters a wrong parameter by mistake!
        'H_MT-TumorDNA'
        'HLA-A*02:01,HLA-A*04:02,HLA-B*05:01.......'
        'NetMHC' 'NetMHCcons' 'PickPocket' 'SMM' 'SMMPMBEC' 'MHCflurry' 'MHCnuggetsI......
        'pvacfuse_predictions' > pvacfuse.log

**Output File**
It looks like running as normal and ending up with empty outputs, but without any error message about the wrong `input_file` parameter.

**Expected behavior**
If any user feeds an `input_file` parameter in `pvacfuse run`, which actually doesn't exist, it should show an error about this wrong input and stops running.

**Comment by susannasiebert** [comment]
@gschang can you check that the following is in the stderr file of your test run above: 
```
The intermediate FASTA file for epitope length 8 is empty. Please check that the input AGfusion directory contains fusion entries with `*_protein.fa` files. Fusion entries without this file cannot be processed by pVACfuse.
```

**Comment by gschang** [comment]
Thank you for this feedback, @susannasiebert. Actually, I am sorry that I didn't catch the error log (`stderr`). I will do it next time.

Below, I want to attach what the log (`stdout`) looks like when I ran the `pvacfuse run` command with a wrong `input_file` parameter.

```
Executing MHC Class I predictions
Converting Fusion file to TSV
Completed
Generating Variant Peptide FASTA and Key File
Completed
Parsing the Variant Peptide FASTA and Key File
Completed
Calculating Manufacturability Metrics
Completed
Splitting FASTA into smaller chunks
Splitting FASTA into smaller chunks - Entries 1-24
Completed
Epitope Length 8 is not valid for Method SMM and Allele HLA-B*58:01. Skipping.
Epitope Length 8 is not valid for Method SMMPMBEC and Allele HLA-B*58:01. Skipping.
Allele HLA-C*03:02 not valid for Method NetMHC. Skipping.
Allele HLA-C*03:02 not valid for Method SMM. Skipping.
Allele HLA-C*03:02 not valid for Method SMMPMBEC. Skipping.
Epitope Length 8 is not valid for Method SMM and Allele HLA-C*03:03. Skipping.
Epitope Length 8 is not valid for Method SMMPMBEC and Allele HLA-C*03:03. Skipping.
Making binding predictions on Allele HLA-A*02:01 and Epitope Length 8 with Method SMM - File /gscmnt/gc2764/cad/gchang/work/15_CANCER-GILLANDERS/211115-PAC-8124-014-pvacfuse/pvacfuse_predictions/MHC_Class_I/8/tmp/H_MT-8124-014-014-2TumorDNA-B29FFSl.smm.HLA-A*02:01.8.tsv_1-24
Making binding predictions on Allele HLA-A*24:02 and Epitope Length 8 with Method NetMHCcons - File /gscmnt/gc2764/cad/gchang/work/15_CANCER-GILLANDERS/211115-PAC-8124-014-pvacfuse/pvacfuse_predictions/MHC_Class_I/8/tmp/H_MT-8124-014-014-2TumorDNA-B29FFSl.netmhccons.HLA-A*24:02.8.tsv_1-24
Making binding predictions on Allele HLA-B*35:01 and Epitope Length 8 with Method MHCflurry - File /gscmnt/gc2764/cad/gchang/work/15_CANCER-GILLANDERS/211115-PAC-8124-014-pvacfuse/pvacfuse_predictions/MHC_Class_I/8/tmp/H_MT-8124-014-014-2TumorDNA-B29FFSl.MHCflurry.HLA-B*35:01.8.tsv_1-24
......
```

**Comment by susannasiebert** [comment]
Oh, that's really strange. For me, I got the `The intermediate FASTA file for epitope length 8 is empty` error message and it aborted after that. I can't quite explain why it would continue processing in your example.

I did add a PR to add some additional error handling around this case. It sounds like a good idea for you to try and run with that change to see if it works on your end. I can make a new Docker image that includes my change.

**Comment by gschang** [comment]
Sure, thank you so much for this help. When I get a next release, I will test it and report back to you. Since this request is for feature enhancement (by adding exception handling caused by user's mistake), but not involving a critical error, please take your time as with your priority.
