### ISSUE TITLE
BAM and VCF files when Creating a phased VCF of proximal variants

### ISSUE THREAD

**Issue by yzhan360** [griffithlab/pVACtools#751]
Hi, when creating a phased VCF of proximal variants, I am not clear on the following input files:
- tumor.bam: A BAM file of tumor reads
Q: is it DNA or RNA bam file?
- somatic.vcf: A VCF of somatic variants
Q: Is it tumor only somatic.vcf or both tumor and normal samples included? I use MuTect2 which results in both tumor and normal samples.
- germline.vcf: A VCF of germline variants
Q: Again, is it tumor only germline.vcf or both tumor and normal? Here I use haplotypecaller which results in tumor.vcf and normal.vcf separately. Should I first combine tumor and normal germline vcfs to match the Mutect2 samples, and then combine somatic and germline VCFs?

Thanks!

**Comment by susannasiebert** [comment]
@yzhan360 we have recently updated our documentation to clarify some of these questions you had: https://pvactools.readthedocs.io/en/stable/pvacseq/input_file_prep/proximal_vcf.html. Can you please try the updated steps here and see if that works for you?
