### ISSUE TITLE
Problem with indel positions in .tsv output

### ISSUE THREAD

**Issue by LodovicoTerzi** [griffithlab/pVACtools#789]
Hello, thank you for the great tool! I am facing an issue with indels, in particular deletion, when running pvacseq. I have annotated with VEP my vcf file, including a 2bp deletion of TA at position chr15:45007689-45007690. My input vcf is below (seems correct given the REF bp C at position 45007688 - as expected in hg19).

15	45007688	15_45007689_TA/-	CTA	C	.	.	CSQ=-|intron_variant&NMD_transcript_variant|MODIFIER|B2M|ENSG00000166710|Transcript|ENST00000349264|nonsense_mediated_decay||1/3||||||||||1||HGNC|914|||MSRSVALAVLALLSLSGLERELKKWSIQTCLSARTGLSISCTTLNSPPLKKMSMPAV,-|frameshift_variant|HIGH|B2M|ENSG00000166710|Transcript|ENST00000544417|protein_coding|2/2||||166-167|136-137|46|Y/X|TAt/t|||1||HGNC|914|CVWVSSIRH|-67|MSRSVALAVLALLSLSGLEAIQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWGKSYILL,-|frameshift_variant&NMD_transcript_variant|HIGH|B2M|ENSG00000166710|Transcript|ENST00000557901|nonsense_mediated_decay|2/4||||153-154|125-126|42|L/X|cTA/c|||1||HGNC|914|LCLGFIHPTLKLTY|5|MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWVSSIRH,-|frameshift_variant|HIGH|B2M|ENSG00000166710|Transcript|ENST00000558401|protein_coding|2/4||||206-207|136-137|46|Y/X|TAt/t|||1||HGNC|914|CVWVSSIRH|-64|MSRSVALAVLALLSLSGLEAIQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWDRDM,-|upstream_gene_variant|MODIFIER|PATL2|ENSG00000229474|Transcript|ENST00000558573|processed_transcript|||||||||||4175|-1||HGNC|33630|||,-|intron_variant&non_coding_transcript_variant|MODIFIER|B2M|ENSG00000166710|Transcript|ENST00000559220|processed_transcript||1/1||||||||||1||HGNC|914|||,-|frameshift_variant&NMD_transcript_variant|HIGH|B2M|ENSG00000166710|Transcript|ENST00000559720|nonsense_mediated_decay|2/3||||196-197|136-137|46|Y/X|TAt/t|||1||HGNC|914|CVWVSSIRH|-67|MSRSVALAVLALLSLSGLEAIQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWGKSYILL,-|non_coding_transcript_exon_variant|MODIFIER|B2M|ENSG00000166710|Transcript|ENST00000559907|processed_transcript|2/4||||163-164|||||||1||HGNC|914|||,-|frameshift_variant|HIGH|B2M|ENSG00000166710|Transcript|ENST00000559916|protein_coding|2/3||||170-171|136-137|46|Y/X|TAt/t|||1||HGNC|914|CVWVSSIRH|-64|MSRSVALAVLALLSLSGLEAIQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWDRDM,-|upstream_gene_variant|MODIFIER|B2M|ENSG00000166710|Transcript|ENST00000560556|processed_transcript|||||||||||234|1||HGNC|914|||,-|non_coding_transcript_exon_variant|MODIFIER|B2M|ENSG00000166710|Transcript|ENST00000560681|retained_intron|2/3||||131-132|||||||1||HGNC|914|||,-|upstream_gene_variant|MODIFIER|B2M|ENSG00000166710|Transcript|ENST00000561139|nonsense_mediated_decay|||||||||||8|1|cds_start_NF|HGNC|914|||GFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWDRDM,-|frameshift_variant&NMD_transcript_variant|HIGH|B2M|ENSG00000166710|Transcript|ENST00000561424|nonsense_mediated_decay|2/5||||174-175|136-137|46|Y/X|TAt/t|||1||HGNC|914|CVWVSSIRH|-64|MSRSVALAVLALLSLSGLEAIQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWDRDM	GT	0/1

However my pvacseq result is as follow. Could you help me in understand why the REF base is now a T? Also the position is shifted?

15	45007686	45007688	TTA	T	ENST00000557901	ENSG00000166710	FS	FI/FX	41-42	B2M	HLA-A*02:05	10	11	1	FMCLGFIHPT	NA	NetMHCpan	94.99	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	166.795	NA	NA	NA	94.99	NA	238.6	NA	NA

This is my code I am running.

pvacseq run inputdir/Sample_138_VEPannotated_samplennot.vcf Sample_138 HLA-A*02:05,HLA-B*15:220,HLA-C*04:01,HLA-A*03:02,HLA-B*35:02,HLA-C*12:03 {NetMHC,NetMHCpan,PickPocket} outputdir/Sample_138 -e 8,9,10

Thank you!

**Comment by susannasiebert** [comment]
I believe that the variant in the VCF is a different one than the variant from your pVACseq result. Can you attach your full VCF file to this issue for further debugging?

**Comment by LodovicoTerzi** [comment]
Sure, here is the full VCF (I added .txt for the upload). Thank you!
[Sample_138_VEPannotated_samplennot.vcf.txt](https://github.com/griffithlab/pVACtools/files/8381093/Sample_138_VEPannotated_samplennot.vcf.txt)

**Comment by susannasiebert** [comment]
Hi @LodovicoTerzi,

I apologize for the late reply. I'm unable to reproduce this error. When I run your VCF, I do not get the TSV entry you provided.

```
# grep CTA -R Sample_138/MHC_Class_I/Sample_138.tsv
15	45007688	45007690	CTA	C	B2M	ENST00000544417	NA	Y/X	TAt/t	ENSG00000166710			MSRSVALAVLALLSLSGLEAIQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWGKSYILL	CVWVSSIRH		FS	46	NA	NA	NA	NA	NA	NA	NA	NA	8.B2M.ENST00000544417.FS.46CTA/C	-67
15	45007688	45007690	CTA	C	B2M	ENST00000557901	NA	L/X	cTA/c	ENSG00000166710			MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWVSSIRH	LCLGFIHPTLKLTY		FS	42	NA	NA	NA	NA	NA	NA	NA	NA	9.B2M.ENST00000557901.FS.42CTA/C	5
15	45007688	45007690	CTA	C	B2M	ENST00000558401	NA	Y/X	TAt/t	ENSG00000166710			MSRSVALAVLALLSLSGLEAIQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWDRDM	CVWVSSIRH		FS	46	NA	NA	NA	NA	NA	NA	NA	NA	10.B2M.ENST00000558401.FS.46CTA/C	-64
15	45007688	45007690	CTA	C	B2M	ENST00000559720	NA	Y/X	TAt/t	ENSG00000166710			MSRSVALAVLALLSLSGLEAIQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWGKSYILL	CVWVSSIRH		FS	46	NA	NA	NA	NA	NA	NA	NA	NA	11.B2M.ENST00000559720.FS.46CTA/C	-67
15	45007688	45007690	CTA	C	B2M	ENST00000559916	NA	Y/X	TAt/t	ENSG00000166710			MSRSVALAVLALLSLSGLEAIQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWDRDM	CVWVSSIRH		FS	46	NA	NA	NA	NA	NA	NA	NA	NA	12.B2M.ENST00000559916.FS.46CTA/C	-64
15	45007688	45007690	CTA	C	B2M	ENST00000561424	NA	Y/X	TAt/t	ENSG00000166710			MSRSVALAVLALLSLSGLEAIQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWDRDM	CVWVSSIRH		FS	46	NA	NA	NA	NA	NA	NA	NA	NA	13.B2M.ENST00000561424.FS.46CTA/C	-64
```
```
# grep TTA -R Sample_138/MHC_Class_I/Sample_138.tsv
[no output]
```

Was there maybe a sample mixup with your files?

**Comment by LodovicoTerzi** [comment]
Dear Susanna, 
Many thanks for your response. Indeed I finally got the same results, not sure what the problem was as I used the same line of code..
Anyway, many thanks for looking into this and sorry for wasting your time.
Lodovico

**Comment by susannasiebert** [comment]
You're welcome. Glad you were able to get a successful set of results.
