### ISSUE TITLE
Problem with fasta generation: wrong epitope length

### ISSUE THREAD

**Issue by sashakotov2** [griffithlab/pVACtools#79]
I run into the following issue
![image](https://user-images.githubusercontent.com/24713989/35968639-8c4b0f8e-0cd5-11e8-967d-e55b3ea19470.png)

Please, check line 417 in https://github.com/griffithlab/pVACtools/blob/master/lib/pipeline.py

and 369 line in https://github.com/griffithlab/pVAC-Seq/blob/master/pvacseq/lib/pipeline.py

I guess you need to change min() to max() how it was done in pVACseq pipeline.py

I tested it and it does work without errors

**Comment by susannasiebert** [comment]
Thank you for the bug report. I will fix this issue as soon as possible.

**Comment by susannasiebert** [comment]
This bug should be fixed in version 1.0.2. I'm closing this issue but feel free to reopen if you're still having problems.
