### ISSUE TITLE
Did you use the same reference build version for VEP that you used for creating the VCF?

### ISSUE THREAD

**Issue by asmlgkj** [griffithlab/pVACtools#790]
Thanks a lot for this great tool, it is the first time that I met this problem, it has been run for thousands of samples
* pvactools version: newest docker
* Python version: 3
* Operating System: centos

ERROR: There was a mismatch between the actual wildtype amino acid sequence (DVKPSNILLDERGQIKLCDFGISGRLVDSKAKTRSAGCAAYMAPERIDPPDPTKPDYDIRADVWSLGISLVELATGQFPYKNCKTDFE) and the expected amino acid sequence (DVKPSNILLDERGQIKLCDFGISGRLVDSKAKTRSAGCAAYMAVSGGPPAGEGVGAGRPAPALEIRLLLPPLQPERIDPPDPTKPDYD). Did you use the same reference build version for VEP that you used for creating the VCF?
OrderedDict([('chromosome_name', 'chr19'), ('start', '7975916'), ('stop', '7976179'), ('reference', 'GACGTCAAGCCCTCCAACATCCTGCTGGACGAGCGGGGCCAGATCAAGCTCTGCGACTTCGGCATCAGCGGCCGCCTGGTGGACTCCAAAGCCAAGACGCGGAGCGCCGGCTGTGCCGCCTACATGGCAGTGAGTGGGGGCCCCCCAGCGGGGGAGGGGGTGGGGGCTGGGAGGCCGGCCCCAGCCTTGGAGATACGTCTTCTCCTCCCCCCCCTGCAGCCCGAGCGCATTGACCCCCCAGACCCCACCAAGCCGGACTATGAC'), ('variant', 'CTGCAGGCTGAGGCAGGAGAATCACTTGAACCGGGCAGGTGG'), ('gene_name', 'MAP2K7'), ('transcript_name', 'NM_145185'), ('transcript_support_level', 'NA'), ('amino_acid_change', 'DVKPSNILLDERGQIKLCDFGISGRLVDSKAKTRSAGCAAYMAVSGGPPAGEGVGAGRPAPALEIRLLLPPLQPERIDPPDPTKPDYD/LQAEAGESLEPGRW'), ('codon_change', 'GACGTCAAGCCCTCCAACATCCTGCTGGACGAGCGGGGCCAGATCAAGCTCTGCGACTTCGGCATCAGCGGCCGCCTGGTGGACTCCAAAGCCAAGACGCGGAGCGCCGGCTGTGCCGCCTACATGGCAGTGAGTGGGGGCCCCCCAGCGGGGGAGGGGGTGGGGGCTGGGAGGCCGGCCCCAGCCTTGGAGATACGTCTTCTCCTCCCCCCCCTGCAGCCCGAGCGCATTGACCCCCCAGACCCCACCAAGCCGGACTATGAC/CTGCAGGCTGAGGCAGGAGAATCACTTGAACCGGGCAGGTGG'), ('ensembl_gene_id', '5609'), ('hgvsc', 'NM_145185:c.727_900delinsCTGCAGGCTGAGGCAGGAGAATCACTTGAACCGGGCAGGTGG'), ('hgvsp', 'NP_660186:p.Asp243_Asp300delinsLeuGlnAlaGluAlaGlyGluSerLeuGluProGlyArgTrp'), ('wildtype_amino_acid_sequence', 'MAASSLEQKLSRLEAKLKQENREARRRIDLNLDISPQRPRPTLQLPLANDGGSRSPSSESSPQHPTPPARPRHMLGLPSTLFTPRSMESIEIDQKLQEIMKQTGYLTIGGQRYQAEINDLENLGEMGSGTCGQVWKMRFRKTGHVIAVKQMRRSGNKEENKRILMDLDVVLKSHDCPYIVQCFGTFITNTDVFIAMELMGTCAEKLKKRMQGPIPERILGKMTVAIVKALYYLKEKHGVIHRDVKPSNILLDERGQIKLCDFGISGRLVDSKAKTRSAGCAAYMAPERIDPPDPTKPDYDIRADVWSLGISLVELATGQFPYKNCKTDFEVLTKVLQEEPPLLPGHMGFSGDFQSFVKDCLTKDHRKRPKYNKLLEHSFIKRYETLEVDVASWFKDVMAKTESPRTSGVLSQPHLPFFR'), ('frameshift_amino_acid_sequence', ''), ('fusion_amino_acid_sequence', ''), ('variant_type', 'inframe_del'), ('protein_position', '243-300'), ('transcript_expression', 'NA'), ('gene_expression', 'NA'), ('normal_depth', 'NA'), ('normal_vaf', 'NA'), ('tdna_depth', '148'), ('tdna_vaf', '0.0405'), ('trna_depth', 'NA'), ('trna_vaf', 'NA'), ('index', '2235.MAP2K7.NM_145185.inframe_del.243-300DVKPSNILLDERGQIKLCDFGISGRLVDSKAKTRSAGCAAYMAVSGGPPAGEGVGAGRPAPALEIRLLLPPLQPERIDPPDPTKPDYD/LQAEAGESLEPGRW'), ('protein_length_change', '')])

![image](https://user-images.githubusercontent.com/50854682/161463629-dec3f7a9-a26e-4b31-9293-039da087e118.png)

**Comment by asmlgkj** [comment]
thanks a lot ,how can I get rid of this petide even if it was not the same reference

**Comment by asmlgkj** [comment]
@susannasiebert  thanks a lot, sorry for the late thanks

**Comment by susannasiebert** [comment]
Hi @ZJURenyi,
I'm sorry you're running into these issues. I'm not entirely sure if your error has anything to do with your data being RNAseq data. I don't think it does. We haven't been able to fully understand why VEP is behaving this way. We only know that it has something to do with there being a mismatch between the reference nucleotide(s) for the affected variant and the transcript nucleotides at the affected position for whatever version of the transcript VEP is using for annotation. I think this boils down to mismatches existing between the reference genome fasta and whatever transcript cache VEP is using. That being said, pVACseq wasn't really designed to be run on a RNAseq VCF but it seems to work for you (aside from these minor errors). That's a bit outside of my area of expertise so maybe @chrisamiller or @malachig can advise if there are any caveats to be aware of.

In regards to the VAtools error, can you please make a bug report at https://github.com/griffithlab/VAtools so I can investigate further?

**Comment by susannasiebert** [comment]
@ZJURenyi one thing to be aware of when running pVACseq with a RNAseq VCF is that any data written by the variant caller in the AD/DP/AF fields will be interpreted by pVACseq as DNA coverage/VAF. The filter cutoffs are controlled by the `--tdna-cov`, `--tdna-vaf`, `--normal-cov`, and `--normal-vaf` parameters and might need adjusting to better work for RNAseq data.

**Comment by ZJURenyi** [comment]
> Hi @ZJURenyi, I'm sorry you're running into these issues. I'm not entirely sure if your error has anything to do with your data being RNAseq data. I don't think it does. We haven't been able to fully understand why VEP is behaving this way. We only know that it has something to do with there being a mismatch between the reference nucleotide(s) for the affected variant and the transcript nucleotides at the affected position for whatever version of the transcript VEP is using for annotation. I think this boils down to mismatches existing between the reference genome fasta and whatever transcript cache VEP is using. That being said, pVACseq wasn't really designed to be run on a RNAseq VCF but it seems to work for you (aside from these minor errors). That's a bit outside of my area of expertise so maybe @chrisamiller or @malachig can advise if there are any caveats to be aware of.
> 
> In regards to the VAtools error, can you please make a bug report at https://github.com/griffithlab/VAtools so I can investigate further?

Thank you Suhanna for the prompt response and the kind suggestion below. I will make the report tomorrow.
