### ISSUE TITLE
Does running the coverage annotation pipeline override information already present?

### ISSUE THREAD

**Issue by shadihames** [griffithlab/pVACtools#795]
I have VCF files for samples which have been created by merging VCFs from 3 different callers. One of those callers didn't output anything in the AD and AP format fields whereas the other 2 did. I have initially added coverage info from RNA but I'm hesitant to do the same for tumour and normal DNA because I'm not sure if information already present will be replaced with info from the coverage pipeline. Do you know if this is the case?

After running pVACseq I can see that the majority of filtered epitopes are from that caller. Eg. for one sample 7/8 epitopes were called from that tool. Would you suggest running the coverage pipeline you documented regardless of whether it replaces info from the other mutation callers?

Thanks!

**Comment by susannasiebert** [comment]
We generally recommend running the coverage pipeline for all variants, even the ones from callers that provide their own coverage information. This ensures that you will have coverage data for all variants and that the coverage information was calculated in a standardized way across all variants. The vcf-readcount-annotator will overwrite existing coverage data.

**Comment by shadihames** [comment]
Thanks so much for the quick advice. Standardising the coverage information makes a lot of sense, I'll go with that.
