### ISSUE TITLE
.all_epitopes.tsv result out, but process does not end for many hours

### ISSUE THREAD

**Issue by asmlgkj** [griffithlab/pVACtools#798]
* pvactools version:docker
* Python version:3.7
* Operating System:centos

**Describe the bug**
the file *.all_epitopes.tsv result out in a early time, but process does not end for many hours, and the final result *.filtered.tsv does not come out

thanks a lot for your help

**Comment by asmlgkj** [comment]
sorry for the late reply, I think it was because of too many variants, there was 20,000 variants

**Comment by susannasiebert** [comment]
We determined that this issue was related to the filtering steps. We reworked our our I/O approach during filtering, which fixes this issue. Please try version 3.1.0 and see if that resolved this problem for you as well.
