### ISSUE TITLE
pip install pvactool=v3.0.0, can not find tensorflow version 2.2.2 

### ISSUE THREAD

**Issue by YuntaoTan** [griffithlab/pVACtools#814]
* pvactools version: v3.0.0 or v3.0.1
* Python version: 3.10.4
* Operating System:  Linux login.local 3.10.0-693.el7.x86_64 

**Describe the bug**
pip install pvactool=v3.0.0, can not find tensorflow version 2.2.2 

**To Reproduce**
pip install pvactool=v3.0.0

**Log Output**
![pvactools_error](https://user-images.githubusercontent.com/9817389/173266624-04f78968-bd26-439b-b274-a1b18bfbdd26.png)

**Output File**

**Expected behavior**

will sucuss install pvactools v3.0.0

**Comment by toddajohnson** [comment]
I believe that certain pvactools prerequisite versions are only available for certain python versions.
I started trying to install pvactools with one of the more recent versions like python 3.8, but ended up setting up a condo environment with python 3.6.15 and everything installed fine (including tensorflow 2.2.2).

**Comment by susannasiebert** [comment]
You are correct. There is a chain of dependencies from MHCnuggets requiring tensorflow <=2.2 (it breaks on later versions). However, 2.2. isn't available on python 3.9 and above (@toddajohnson 3.8 should work according to our test env). We're currently waiting on MHCnuggets to release a new version that is compatible with later versions of tensorflow (see https://github.com/KarchinLab/mhcnuggets/issues/29). Once the new version is out, we can update our tensorflow dependency.

**Comment by susannasiebert** [comment]
This issue should be resolved with our brand new release, version 4.0.0
