### ISSUE TITLE
pVACfuse: -a sample_name option returns empty Sample Name column

### ISSUE THREAD

**Issue by toddajohnson** [griffithlab/pVACtools#817]
* pvactools version: 3.0.1
* Python version: 3.6.15
* Operating System: CentOS 7

**Describe the bug**
Using -a sample_name option with pVACfuse outputs .tsv files with "Sample Name" column that is empty.
pVACseq does not have that problem; "Sample Name" column was correctly filled with the tumor Sample Name.

I compared the pVACseq and pVACfuse run.py scripts, and pVACfuse uses pipeline = PvacbindPipeline(**run_arguments), while pVACseq uses pipeline = Pipeline(**class_i_arguments) to create the output files that are then combined into MHC I or II or then combined reports.

It looks to me like the Pipeline class in lib/pipeline.py includes commands to parse the additional_report_columns variable, but those do not appear to instantiated by the PvacbindPipeline class.  I will hazard a guess that the PostProcessor adds the empty Sample Name column when merging the intermediate tables from the pipeline step.

**To Reproduce**
`pvacseq run \
	${processed_vcf_file} \
	${tumor_sample_id} \
	${HLA_alleles} \
	${prediction_algorithms} \
	${output_dir} \
	--normal-sample-name ${normal_sample_id} \
	-p ${phased_vcf_file} \
	--iedb-install-directory $HOME/reference/immuno/IEDB/IEDB-3.1.2 \
	-e1 8,9,10,11 \
	-e2 12,13,14,15,16,17,18 \
	--net-chop-method cterm \
	-a sample_name \
	--maximum-transcript-support-level ${TSL_cutoff} \
	--tumor-purity ${tumor_purity} \
	-t ${threads}`

**Log Output**
The log output is >100k rows and has no information relevant to this problem

**Output File**
Chromosome      Start   Stop    Transcript      Gene Name       Variant Type    Mutation        HLA Allele      Sub-peptide Position    Epitope Seq     Median Score    Best Score      Best Score Method       Median Percentile       Best Percentile Best Percentile Method  MHCflurry Score MHCflurry Percentile    MHCnuggetsI Score       MHCnuggetsI Percentile  NetMHC Score    NetMHC Percentile       Sample Name     cterm_7mer_gravy_score  max_7mer_gravy_score    difficult_n_terminal_residue    c_terminal_cysteine     c_terminal_proline      cysteine_count  n_terminal_asparagine   asparagine_proline_bond_count   MHCnuggetsII Score      MHCnuggetsII Percentile NetMHCIIpan Score       NetMHCIIpan Percentile
9 / 19  16704753 / 18866044     16870843 / 18868230     ENST00000380672_ENST00000262803 BNC2_UPF1       inframe_fusion  1.BNC2_UPF1.ENST00000380672_ENST00000262803.inframe_fusion.110  HLA-A*24:02     1       LFRMSQQD        33247.586       5377.65 MHCnuggetsI     59.97   39.0    NetMHC  33247.585719973016      80.93987500000001       5377.65 NA      35404.51        39.0            -1.5857142857142859     -0.5428571428571429     False   False   False   0       False   0       NA      NA      NA      NA

**Expected behavior**
Sample Name column should contain a Sample Name.

**Comment by susannasiebert** [comment]
Thank you for this bug report. I made a pull request for a fix at #818. I plan on making a new release either later this week or next week.

**Comment by susannasiebert** [comment]
The new version 3.0.3 fixes this bug. Please let me know if you encounter any additional problems.
