### ISSUE TITLE
incorrect allele format for NetMHCIIpan

### ISSUE THREAD

**Issue by kylec** [griffithlab/pVACtools#82]
Although pvacseq accepts "DPA1*01:03-DPB1*05:01" as valid allele,  mhc_II_binding.py says it's invalid.

According to [NetMHCIIpan website](http://www.cbs.dtu.dk/services/NetMHCIIpan/alleles_name.list), the valid allele should either DPA1*01:03 or DPB1*05:01, there's no "-"
 ```
pvacseq run test.vcf test DPA1*01:03-DPB1*05:01 NetMHCIIpan test -e 9 --iedb-install-directory /rsrch2/ccp_rsch/kchang3/software/IEDB/
Executing MHC Class II predictions
Restart to be executed with a different pVACtools version:
Past version: 1.0.0
Current version: 1.0.1
Converting .vcf to TSV
TSV file already exists. Skipping.
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-15
Split TSV file for Entries 1-15 already exists. Skipping.
Completed
Generating Variant Peptide FASTA and Key Files
Split FASTA file for Entries 1-30 already exists. Skipping.
Completed
Processing entries for Allele DPA1*01:03-DPB1*05:01 - Entries 1-30
Running IEDB on Allele DPA1*01:03-DPB1*05:01 with Method NetMHCIIpan - Entries 1-30
Invalid allele name "DPA1*01:03-DPB1*05:01" for method "NetMHCIIpan" was found. To see all available alleles, please type command:
$ python mhc_II_binding.py allele
Traceback (most recent call last):
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/lib/python3.5/site-packages/tools/pvacseq/main.py", line 78, in main
    args[0].func.main(args[1])
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/lib/python3.5/site-packages/tools/pvacseq/run.py", line 148, in main
    pipeline.execute()
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/lib/python3.5/site-packages/lib/pipeline.py", line 340, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/lib/python3.5/site-packages/lib/pipeline.py", line 578, in call_iedb_and_parse_outputs
    '-e', self.iedb_executable,
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/lib/python3.5/site-packages/lib/call_iedb.py", line 56, in main
    response = run(prediction_class_object.iedb_executable_params(args), stdout=PIPE, check=True)
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python2.7', '/rsrch2/ccp_rsch/kchang3/software/IEDB/mhc_ii/mhc_II_binding.py', 'NetMHCIIpan', 'DPA1*01:03-DPB1*05:01', '/rsrch2/ccp_rsch/kchang3/lynch/rnaseq-hg19/pvacseq2/test/MHC_Class_II/tmp/test_31.fa.split_1-30']' returned non-zero exit status 1
```

More interestingly, if you run "python2.7 mhc_II_binding.py allele" to check for valid iedb alleles, you'll see that comblib, comblib etc uses "/" between alleles instead of "-" , e.g. HLA-DPA1*02:01/DPB1*01:01

**Comment by susannasiebert** [comment]
It looks like IEDB changed the allele format for class II predictions. We will need to update those on our side but I'm a bit weary of breaking compatibility with older IEDB versions. This will require some more thought.

**Comment by kylec** [comment]
I'm using IEDB_MHC_II-2.17.3.tar.gz listed in the tutorial. I'll try some older versions.

**Comment by kylec** [comment]
I got it to run after using older version but encounter a None-type error. I wonder if it has to do with my peptide length. Is there any suggested length for class II prediction?

```
pvacseq run EBL26-EBL27.vep.vcf EBL26 DQA1*01:03-DQB1*04:02,DRB1*08:01,DRB1*13:01 NetMHCIIpan EBL26-result -e 8,9,10,11 --iedb-install-directory ~/software/IEDB/

Running IEDB on Allele DQA1*01:03-DQB1*04:02 with Method NetMHCIIpan - Entries 1-200
Traceback (most recent call last):
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/lib/python3.5/site-packages/tools/pvacseq/main.py", line 78, i
n main
    args[0].func.main(args[1])
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/lib/python3.5/site-packages/tools/pvacseq/run.py", line 148, i
n main
    pipeline.execute()
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/lib/python3.5/site-packages/lib/pipeline.py", line 340, in exe
cute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/lib/python3.5/site-packages/lib/pipeline.py", line 578, in cal
l_iedb_and_parse_outputs
    '-e', self.iedb_executable,
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/lib/python3.5/site-packages/lib/call_iedb.py", line 86, in mai
n
    tmp_output_filehandle.write(response_text)
TypeError: a bytes-like object is required, not 'NoneType'
```

**Comment by susannasiebert** [comment]
Class II doesn't use the epitope length parameter. It's 15 by default.

I vaguely seem to recall this issue where IEDB simply doesn't return anything for some class II inputs. I wasn't able to figure out in which situation this would happen exactly or whether this was a bug with IEDB. One of the tmp files created by pVACseq is a fasta which you can use to run IEDB standalone and double check the outputs. This would also allow you to run different IEDB version and see if a newer IEDB version would give an output. pVACseq should handle this situation more gracefully so I will work on that.

A hacky workaround would be to try and manually update the IEDB allele files that are used for pVACseq in your installation until the bugfix in #84 is put live. On your system this file should be located at `/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/lib/python3.5//tools/pvacseq/iedb_alleles/class_ii/NetMHCIIpan.tsv`. Simply replace the `-` with `/` for combinatorial alleles.

**Comment by susannasiebert** [comment]
@kylec would it be possible for you to share the fasta file that gets created by pVACseq and is resulting in this error?

**Comment by kylec** [comment]
@susannasiebert
Here is the fasta file. I'm going to try your workaround as well. Thank you!
[EBL26_31.fa.split_1-200.zip](https://github.com/griffithlab/pVACtools/files/1720707/EBL26_31.fa.split_1-200.zip)

**Comment by susannasiebert** [comment]
Thank you.

I forgot to mention that if you try the workaround, you will also need to make a small change in your IEDB install. In `mhc_ii/ mhc_II_binding.py` line 205 you will need to replace `form_alleles.replace("HLA-", "").replace("/","-")` with `form_alleles.replace("HLA-", "")` otherwise this line of code would replace the `/` with `-` again.

**Comment by kylec** [comment]
I just realize the problem with having / in between the two alleles will cause a problem when trying to write file "EBL13.NetMHCIIpan.DQA1*01:01/DQB1*03:01.tsv_1-200.tmp" because it will be interpreted as a directory. 

So i replace "-" with "/" `mhc_ii/ mhc_II_binding.py` with `form_alleles = form_alleles.replace("HLA-", "").replace("-","/")`

What's weird is if i run pvacseq interactively, it's fine. 
```
Processing entries for Allele DQA1*05:01-DQB1*03:01 - Entries 1-200
Running IEDB on Allele DQA1*05:01-DQB1*03:01 with Method NetMHCIIpan - Entries 1-200
Completed
```
but when i submit pvacseq run command to the LSF cluster
Processing entries for Allele DQA1*05:01-DQB1*03:01 - Entries 1-200
Running IEDB on Allele DQA1*05:01-DQB1*03:01 with Method NetMHCIIpan - Entries 1-200
Traceback (most recent call last):
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/lib/python3.5/site-packages/tools/pvacseq/main.py", line 78, i
n main
    args[0].func.main(args[1])
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/lib/python3.5/site-packages/tools/pvacseq/run.py", line 148, i
n main
    pipeline.execute()
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/lib/python3.5/site-packages/lib/pipeline.py", line 340, in exe
cute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/lib/python3.5/site-packages/lib/pipeline.py", line 578, in cal
l_iedb_and_parse_outputs
    '-e', self.iedb_executable,
  File "/rsrch2/ccp_rsch/kchang3/.conda/envs/pvactools/lib/python3.5/site-packages/lib/call_iedb.py", line 86, in mai
n
    tmp_output_filehandle.write(response_text)
TypeError: a bytes-like object is required, not 'NoneType'

**Comment by susannasiebert** [comment]
Regarding the `/` vs `-` I will make a change to submit the `/` version to IEDB but keep on accepting the `-`  in the pVACseq command.

Regarding the NoneType error, I will do more digging into this.

**Comment by susannasiebert** [comment]
I just noticed that the error you are seeing is actually from a print statement that you added. The variable you are printing is misspelled. It needs to be `response_text` not `response_test`.

**Comment by kylec** [comment]
I found out why I get `TypeError: a bytes-like object is required, not 'NoneType'` error. This error doesn't happen when I run it interactively after fixing the "/" vs "-" issue.  It happens when it's submitted as a job to LSF cluster.

In `mhc_ii/mhc_II_binding.py` (version 2.17.3), there is the following if-else condition, when run during interactive mode (run your code in interactive queue), the stdin/out are terminals.  However, when it's submitted to a queue via LSF), jobs are run in background, so it can’t use default stdin/out, which cause mhc_II_binding.py to exit prematurely in the if loop and thus pvacseq didn't get any output (NoneType). I comment out `exit(0)` and add `infile = sys.argv[3]` and it solves the problem.

```
# /IEDB/mhc_ii/mhc_II_binding.py
# If there's input ready, do something, else do something
    # else. Note timeout is zero so select won't block at all.
    if sys.stdin in select.select([sys.stdin], [], [], 0)[0]:
        infile = sys.stdin.readline().strip()
        if infile:
            pass
        else: # an empty line means stdin has been closed 
            #exit(0) # when it’s submitted as a job, it exists here
            infile = sys.argv[3]
    else:
        if len(sys.argv) > 3: # when it’s run interactively, it looks for sys.argv
            infile = sys.argv[3]

```

**Comment by susannasiebert** [comment]
That's great news. You might want to consider submitting a ticket with IEDB so that they can make this change in their release.

**Comment by susannasiebert** [comment]
The allele bug should be fixed in version 1.0.2. I'm closing this issue but feel free to reopen if you're still having problems with it.

**Comment by connorjliu** [comment]
I'm encountering a very similar issue here. When running the following command:

`pvacseq run GBM27snvs_edit.vep.vcf GBM27_classII_snvs  DPA1*01:03-DPB1*02:01 NetMHCIIpan NNalign SMMalign /classII_snvs/ --iedb-install-directory /gscmnt/gc2502/griffithlab/yafeng/ -i cov_exp.yaml`

I get the following:

`Traceback (most recent call last):
  File "/gscuser/coliu/miniconda2/envs/pvactools/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/tools/pvacseq/main.py", line 78, in main
    args[0].func.main(args[1])
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/tools/pvacseq/run.py", line 152, in main
    pipeline.execute()
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/lib/pipeline.py", line 340, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/lib/pipeline.py", line 578, in call_iedb_and_parse_outputs
    '-e', self.iedb_executable,
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/lib/call_iedb.py", line 56, in main
    response = run(prediction_class_object.iedb_executable_params(args), stdout=PIPE, check=True)
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python2.7', '/gscmnt/gc2502/griffithlab/yafeng/mhc_ii/mhc_II_binding.py', 'NetMHCIIpan', 'DPA1*01:03/DPB1*02:01', '/gscmnt/gc2547/griffithlab/cliu/pvacseq/GBM27/classII_snvs/MHC_Class_II/tmp/GBM27_classII_snvs_31.fa.split_1-200']' returned non-zero exit status 1`


`pvacseq run /gscmnt/gc2547/griffithlab/cliu/pvacseq/GBM27/GBM27snvs_edit.vep.vcf GBM27_classII_snvs  DPA1*01:03-DPB1*02:01,DPA1*01:03-DPB1*04:01,DQA1*01:02-DQB1*03:02,DQA1*01:02-DQB1*06:02,DQA1*03:01-DQB1*03:02,DQA1*03:01-DQB1*06:02,DRB1*04:04,DRB1*15:01,DRB4*01:03,DRB5*01:01 NetMHCIIpan NNalign SMMalign /gscmnt/gc2547/griffithlab/cliu/pvacseq/GBM27/classII_snvs/ --iedb-install-directory /gscmnt/gc2502/griffithlab/yafeng/ -i /gscmnt/gc2547/griffithlab/cliu/pvacseq/GBM27/cov_exp.yaml -m lowest --normal-cov 5 --normal-vaf 100 --tdna-cov 5 --tdna-vaf 10 --trna-cov 10 --trna-vaf 10
No MHC class I prediction algorithms chosen. Skipping MHC class I predictions.
Executing MHC Class II predictions
Converting .vcf to TSV
TSV file already exists. Skipping.
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-100
Split TSV file for Entries 1-100 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 101-200
...
Split FASTA file for Entries 295001-295060 already exists. Skipping.
Completed
Processing entries for Allele DPA1*01:03-DPB1*02:01 - Entries 1-200
IEDB file for Allele DPA1*01:03-DPB1*02:01 with Method NNalign (Entries 1-200) already exists. Skipping.
Running IEDB on Allele DPA1*01:03-DPB1*02:01 with Method NetMHCIIpan - Entries 1-200
No prediction method NetMHCIIpan available for DPA1*01:03-DPB1*02:01. To see all available methods, please type command:
$ python mhc_II_binding.py allele

Traceback (most recent call last):
  File "/gscuser/coliu/miniconda2/envs/pvactools/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/tools/pvacseq/main.py", line 78, in main
    args[0].func.main(args[1])
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/tools/pvacseq/run.py", line 152, in main
    pipeline.execute()
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/lib/pipeline.py", line 340, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/lib/pipeline.py", line 578, in call_iedb_and_parse_outputs
    '-e', self.iedb_executable,
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/lib/call_iedb.py", line 56, in main
    response = run(prediction_class_object.iedb_executable_params(args), stdout=PIPE, check=True)
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['python2.7', '/gscmnt/gc2502/griffithlab/yafeng/mhc_ii/mhc_II_binding.py', 'NetMHCIIpan', 'DPA1*01:03/DPB1*02:01', '/gscmnt/gc2547/griffithlab/cliu/pvacseq/GBM27/classII_snvs/MHC_Class_II/tmp/GBM27_classII_snvs_31.fa.split_1-200']' returned non-zero exit status 1`

**Comment by connorjliu** [comment]
I'm encountering a very similar issue here. When running the following command:

`pvacseq run /gscmnt/gc2547/griffithlab/cliu/pvacseq/GBM27/GBM27snvs_edit.vep.vcf GBM27_classII_snvs  DPA1*01:03-DPB1*02:01,DPA1*01:03-DPB1*04:01,DQA1*01:02-DQB1*03:02,DQA1*01:02-DQB1*06:02,DQA1*03:01-DQB1*03:02,DQA1*03:01-DQB1*06:02,DRB1*04:04,DRB1*15:01,DRB4*01:03,DRB5*01:01 NetMHCIIpan NNalign SMMalign /gscmnt/gc2547/griffithlab/cliu/pvacseq/GBM27/classII_snvs/ --iedb-install-directory /gscmnt/gc2502/griffithlab/yafeng/ -i /gscmnt/gc2547/griffithlab/cliu/pvacseq/GBM27/cov_exp.yaml -m lowest --normal-cov 5 --normal-vaf 100 --tdna-cov 5 --tdna-vaf 10 --trna-cov 10 --trna-vaf 10
No MHC class I prediction algorithms chosen. Skipping MHC class I predictions.
Executing MHC Class II predictions
Converting .vcf to TSV
TSV file already exists. Skipping.
Splitting TSV into smaller chunks
Splitting TSV into smaller chunks - Entries 1-100
Split TSV file for Entries 1-100 already exists. Skipping.
Splitting TSV into smaller chunks - Entries 101-200
...
Split FASTA file for Entries 295001-295060 already exists. Skipping.
Completed
Processing entries for Allele DPA1*01:03-DPB1*02:01 - Entries 1-200
IEDB file for Allele DPA1*01:03-DPB1*02:01 with Method NNalign (Entries 1-200) already exists. Skipping.
Running IEDB on Allele DPA1*01:03-DPB1*02:01 with Method NetMHCIIpan - Entries 1-200
No prediction method NetMHCIIpan available for DPA1*01:03-DPB1*02:01. To see all available methods, please type command:
$ python mhc_II_binding.py allele`

**Comment by connorjliu** [comment]
I'm encountering a very similar issue here. When running the following command:

`pvacseq run GBM27snvs_edit.vep.vcf GBM27_classII_snvs DPA1*01:03-DPB1*02:01 NetMHCIIpan NNalign SMMalign /classII_snvs/ --iedb-install-directory /gscmnt/gc2502/griffithlab/yafeng/ -i cov_exp.yaml`

I get the following:

Split FASTA file for Entries 295001-295060 already exists. Skipping.
Completed
Processing entries for Allele DPA1*01:03-DPB1*02:01 - Entries 1-200
IEDB file for Allele DPA1*01:03-DPB1*02:01 with Method NNalign (Entries 1-200) already exists. Skipping.
Running IEDB on Allele DPA1*01:03-DPB1*02:01 with Method NetMHCIIpan - Entries 1-200
No prediction method NetMHCIIpan available for DPA1*01:03-DPB1*02:01. To see all available methods, please type command:
$ python mhc_II_binding.py allele

Traceback (most recent call last):
  File "/gscuser/coliu/miniconda2/envs/pvactools/bin/pvacseq", line 11, in <module>
    sys.exit(main())
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/tools/pvacseq/main.py", line 78, in main
    args[0].func.main(args[1])
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/tools/pvacseq/run.py", line 152, in main
    pipeline.execute()
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/lib/pipeline.py", line 340, in execute
    split_parsed_output_files = self.call_iedb_and_parse_outputs(chunks)
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/lib/pipeline.py", line 578, in call_iedb_and_parse_outputs
    '-e', self.iedb_executable,
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/site-packages/lib/call_iedb.py", line 56, in main
    response = run(prediction_class_object.iedb_executable_params(args), stdout=PIPE, check=True)
  File "/gscuser/coliu/miniconda2/envs/pvactools/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
**subprocess.CalledProcessError: Command '['python2.7', '/gscmnt/gc2502/griffithlab/yafeng/mhc_ii/mhc_II_binding.py', 'NetMHCIIpan', 'DPA1*01:03/DPB1*02:01', '/gscmnt/gc2547/griffithlab/cliu/pvacseq/GBM27/classII_snvs/MHC_Class_II/tmp/GBM27_classII_snvs_31.fa.split_1-200']' returned non-zero exit status 1**


I've tried the workarounds mentioned above but have not had any success.

**Comment by susannasiebert** [comment]
What version of the IEDB software do you have installed?

**Comment by susannasiebert** [comment]
And what version of pVACtools are you using?

**Comment by connorjliu** [comment]
Ah looks like I was using yfeng's older version of IEDB 2.15. Just updated mine to the latest version and it seems to be working! Easy fix, thank you!
