### ISSUE TITLE
Pre-filtering VCF file for high confidence mutations

### ISSUE THREAD

**Issue by shadihames** [griffithlab/pVACtools#836]
Is it recommended to filter the VCF file before running pVACseq? For example, one of the filters we use if we're looking for high-confidence mutations would be to use something like the CADD score. Is it recommended to input high-confidence VCFs into pVACseq, or just a VEP-annotated VCF that has been filtered by some quality metrics?

Apologies if this has been documented, I wasn't able to find anything specific. 

Thanks!

**Comment by chrisamiller** [comment]
Using the CADD score wouldn't necessarily be a good idea, as you don't much care about the impact/deleteriousness of an allele.  Typically you need to know is whether it creates a novel protein sequence.  That said, filtering a VCF in standard ways such that only high-confidence variants are passed through is a good idea. There's no sense in spending time having pvacseq make predictions for garbage calls. 

Hope that's helpful.

**Comment by shadihames** [comment]
Thanks for the super quick response!

Are there any particular filters you recommend using or is it just a matter of removing variants that won't be used anyway so that the pVACseq runtime is reduced?

**Comment by chrisamiller** [comment]
pvacseq will already remove non-coding variants (and I believe there's a filter that restricts to just PASS variants as well).  If you do something like just naively run Mutect with default parameters on a tumor/normal pair, though, you'll end up with many low-quality, low VAF variants that you might not really care about. The nuances of somatic variant calling are a little outside the bounds of pvactools support, but you can take a look at our WDL pipeline for taking raw sequence all the way though pvactools here: https://github.com/griffithlab/analysis-wdls/blob/main/definitions/immuno.wdl

**Comment by susannasiebert** [comment]
>  I believe there's a filter that restricts to just PASS variants as well

The `---pass-only` flag in pVACseq would achieve this.

**Comment by shadihames** [comment]
Brill, thanks both. I'll have a look through your pipeline.
