### ISSUE TITLE
Additional features for pVACview

### ISSUE THREAD

**Issue by huimingx** [griffithlab/pVACtools#841]
1. Separate section in Advanced option box that showcases the input variables/cutoffs specified by user
2. Create entries in metrics file to account for allele-specific binding threshold. This includes both the exact cutoff as well as list of intervals for coloring cutoff for applicable columns. 
3. Take into account clonal/subclonal cutoffs (now parametrized as well)
4. Tiering algorithm in pVACview helper function needs to be updated to match that of pVACseq. Transcript support level is now a new addition to tiering.
5. Change wording in tooltip for the binding descriptions to match new parametrized input (Best vs Median binding affinity)

**Comment by susannasiebert** [comment]
Some of the work to enable this has already been pushed to origin/pvacview. Additional work neededTo enable this we need to add to the metric file:

- A new top-level entry `binding_cutoffs` that contains a hash of HLA allele -> binding affinity cutoff entries for all HLA alleles used in the report. 
  - When the `--allele-specific-binding-threshold` option is set, the binding affinity cutoff will be allele-specific (using the `PredictionClass.cutoff_for_allele(<allele>)` method to retrieve this value for each HLA allele).
  - The value of the `binding_threshold` input will be used as a fallback for HLA alleles without a specific binding threshold.
  - If the `--allele-specific-binding-threshold` option is not set, use the value from the `binding_threshold` input. We still want to write this top-level entry for ease of processing, even though all the binding affinity cutoff values will be identical
  - These values should already be available in `self.binding_thresholds` so this should be as easy as adding another entry to https://github.com/griffithlab/pVACtools/blob/pvacview/pvactools/lib/aggregate_all_epitopes.py#L194
- A new top level entry `binding_affinity_colors` that contains a hash of HLA allele -> list of binding affinity value steps that are used to bin the binding affinity values into sequential categories of "goodness" for heatmap coloring. There should be a hash entry for each HLA allele used in the report
  - There should be 10 binding affinity cutoff values for each HLA allele. These should be at 10%, 20%, 40%, 60%, 80%, 100%, 120%, 140%, 160%, 180%, and 200% of the binding cutoff values calculated above.
