### ISSUE TITLE
ImportError when I use pvacseq

### ISSUE THREAD

**Issue by ysbioinfo** [griffithlab/pVACtools#842]
* pvactools version: 2.0.1
* Python version: 3.9.13
* Operating System: CentOS

**Describe the bug**
ImportError when I try to use pvacseq

**To Reproduce**
What is the pVACtools command you ran? Please also attach any input files that can be used to reproduce this problem.
pvacseq -h

**Log Output**
```
Traceback (most recent call last):
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/bin/pvacseq", line 5, in <module>
    from tools.pvacseq.main import main
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/lib/python3.9/site-packages/tools/pvacseq/__init__.py", line 15, in <module>
    from . import *
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/lib/python3.9/site-packages/tools/pvacseq/run.py", line 5, in <module>
    from lib.pipeline import *
  File "/mnt/efs/NGS/yangshi/software/anaconda3/envs/pvactools/lib/python3.9/site-packages/lib/pipeline.py", line 9, in <module>
    from .. import lib
ImportError: attempted relative import beyond top-level package
```

**Output File**
No

**Expected behavior**
Print the help information on screen

**Comment by ysbioinfo** [comment]
BTW,
I installed python using conda and then installed pvactools using pip.
When I type pvactools -h, there is no error. But when I type pvacseq, an error occurred.

Thanks
Yang

**Comment by susannasiebert** [comment]
Hi @ysbioinfo ,

thanks for your interest in pVACtools. I'm sorry you're running into errors using our tool. I haven't come across this error before so I will need to see if I can reproduce it locally. You might want to try an installation under python 3.8. I know that some users had problems with python 3.9, albeit different ones. If that doesn't work, I recommend switching to our docker images until I can debug this issue further. Unfortunately, I will be leaving on vacation tomorrow so it will be a few weeks before I can investigate.

Best,
Susanna

**Comment by ysbioinfo** [comment]
HI Susanna,
Thanks for your suggestion! It's so sad that we are not allowed to use docker on the computing cluster. I'll have a try with python3.8, and if it does not work, I'll provide more information of my environment to help you solve it. Have a good vacation!

Best
Yang

**Comment by ysbioinfo** [comment]
Hi Susanna,
So sorry that I forget updating the result. Python 3.8 perfectly solved my problem. Thanks again!

Yang
