### ISSUE TITLE
Keep getting error: "ERROR: VCF file contains more than one sample" even after specifying sample_name

### ISSUE THREAD

**Issue by seetarajpara** [griffithlab/pVACtools#843]
* pvactools version: 2.0.1
* Python version: 3.7
* Operating System: Linux (SLURM)

**Describe the bug**
I have the error as described in the subject line even after specifying the tumor ID for sample_name

**To Reproduce**
```
pvacseq run \
/scratch1/rajpara/TEST2_PVACSEQ/HR9_HC_All.vep.vcf \
KOVAUSCJC_0009_01_OVATUMTD_R00001S8A1M0001P0000_T1_ASXE6S_A00009 \
HLA-A*02:01,HLA-B*35:01,DRB1*11:01 \
NNalign \
--iedb-install-directory /home1/rajpara \
-k \
/scratch1/rajpara/TEST2_PVACSEQ/
```
**Log Output**
```
Executing MHC Class II predictions
Converting VCF to TSV
ERROR: VCF file contains more than one sample
```

Please let me know if I'm missing something in my code. I think once this is resolved, the tool should work fine since it did work before on a VCF I used with just germline variants (not a multi-sample VCF before). Thanks!

**Comment by susannasiebert** [comment]
Could you please double check that you don’t also have the pvacseq package installed? If you do, please uninstall it and try again. You might also need to reinstall pvactools to make sure the right files are used.

**Comment by susannasiebert** [comment]
Hi @seetarajpara,
Since there has been no further action on this ticket, I assume that the issue was indeed related to having the older pvacseq package installed alongside the pvactools package. I will resolve this issue but please do reopen it if you're still having problems.
