### ISSUE TITLE
Exclude epitopes with problematic amino acids

### ISSUE THREAD

**Issue by susannasiebert** [griffithlab/pVACtools#850]
This would implement a new step to remove epitopes in the all_epitopes file that contain a problematic amino acid. Problematic amino acids would be provided via a new input (name TBD).

@m-two @gschang Should we allow any amino acid to be excluded here or is there at least a short list of amino acids that are usually known to be problematic?

**Comment by gschang** [comment]
As Mike commented, Cysteine residue causes failure in peptide synthesis for Gillanders' peptide-vaccine clinical trials.

We're open for discussion. In my opinion, a new option for any customized list of amino acids would be recommended because this list would be specific to each vendor for peptide vaccine design as Mike mentioned. We can make a new column to indicate the presence of such exclusion amino acids (and their position as well?) in the final output, rather than hard filtering-out of those epitopes.

**Comment by susannasiebert** [comment]
I like the idea of not hard-filtering the all_epitopes file. What do you think of adding a filter step downstream to remove such epitopes from the filtered tsv and also exclude them from the aggregate report/pVACview.

**Comment by chrisamiller** [comment]
I agree with the idea of a parameter to exclude certain amino-acids. `--amino-acids-to-exclude CRG`

**Comment by m-two** [comment]
For the JLF project and Gillanders projects moving forward they want to filter all epitopes with Cysteine residues in the peptide sequence.

**Comment by gschang** [comment]
Mike provided useful information on this issue. I copied Mike's comments below from another channel.

--- (source: Mike) ---
Publication:

(1) Factors affecting the physical stability (aggregation) of peptide therapeutics
> https://royalsocietypublishing.org/doi/10.1098/rsfs.2017.0030

(2) Peptide Stability and Degradation
> https://biopeptek.com/peptide-resources/peptide-handling/peptide-stability-and-degradation/

```
Peptide Stability and Potential Degradation Pathways
1. Hydrolysis
> Peptides containing Asp (D)
> Sequence contains Asp-Pro (D-P)
> Similarly, if Asp-Gly (D-G) is present in the sequence
> Sequences containing Ser (S)

2. Deamidation sequences containing:
> Asn-Gly (N-G)
> Gln-Gly (Q-G)
> Asp-Gly (D-G)

3. Oxidation
> The Cys (C) and Met (M)

4. Diketopiperazine and pyroglutamic acid formation
> Gly (G) is in the third position from the N-terminus
> Pro (P) or Gly (G) is in position 1 or 2
```

**Comment by m-two** [comment]
I did a quick lit search.  There are specific positions in the peptide sequences and specific pairs that are more prone to degradation.  The input should probably allow for users to define two attributes "residue position + aa seq".  The position could be "+" (from right/ N-terminus) or "-" (from left /C-terminus).  If the position is undefined then all positions would be considered for filtering.
