### ISSUE TITLE
Error in running pVACvector with a pVACseq output TSV

### ISSUE THREAD

**Issue by QianhuiXu** [griffithlab/pVACtools#867]
* pvactools version: 3.1.0
* Python version:3.6
* Operating System:Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-125-generic x86_64)
* Environment: # packages in environment at /home/shpc_1006/anaconda3/envs/pvactool:

 Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
_openmp_mutex             4.5                       2_gnu    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
absl-py                   1.3.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
astropy                   4.1                      pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
biopython                 1.76                     pypi_0    pypi
bleach                    1.5.0                    pypi_0    pypi
ca-certificates           2022.9.24            ha878542_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
cached-property           1.5.2                    pypi_0    pypi
cachetools                4.2.4                    pypi_0    pypi
certifi                   2022.9.24                pypi_0    pypi
charset-normalizer        2.0.12                   pypi_0    pypi
click                     8.0.4                    pypi_0    pypi
clickclick                20.10.2                  pypi_0    pypi
connexion                 1.4.2                    pypi_0    pypi
datacache                 1.1.5                    pypi_0    pypi
dataclasses               0.8                      pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
flask                     2.0.3                    pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gast                      0.3.3                    pypi_0    pypi
google-auth               1.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.48.2                   pypi_0    pypi
gtfparse                  1.2.1                    pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
html5lib                  0.9999999                pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        4.8.3                    pypi_0    pypi
importlib-resources       5.4.0                    pypi_0    pypi
inflection                0.5.1                    pypi_0    pypi
isovar                    1.1.1                    pypi_0    pypi
itsdangerous              2.0.1                    pypi_0    pypi
jinja2                    3.0.3                    pypi_0    pypi
joblib                    1.1.1                    pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
keras                     2.4.3                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
ld_impl_linux-64          2.39                 hc81fddc_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libffi                    3.4.2                h7f98852_5    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libgcc-ng                 12.2.0              h65d4601_19    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libgomp                   12.2.0              h65d4601_19    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libnsl                    2.0.0                h7f98852_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libsqlite                 3.39.4               h753d276_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
libzlib                   1.2.13               h166bdaf_4    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
markdown                  3.3.7                    pypi_0    pypi
markupsafe                2.0.1                    pypi_0    pypi
memoized-property         1.0.3                    pypi_0    pypi
mhcflurry                 2.0.1                    pypi_0    pypi
mhcgnomes                 1.8.4                    pypi_0    pypi
mhcnames                  0.4.8                    pypi_0    pypi
mhcnuggets                2.3.3                    pypi_0    pypi
mhctools                  1.8.1                    pypi_0    pypi
mock                      4.0.3                    pypi_0    pypi
ncurses                   6.3                  h27087fc_1    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
networkx                  2.5.1                    pypi_0    pypi
np-utils                  0.6.0                    pypi_0    pypi
numpy                     1.18.5                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
openssl                   1.1.1s               h166bdaf_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
pandas                    1.1.5                    pypi_0    pypi
pdfkit                    1.0.0                    pypi_0    pypi
pillow                    8.4.0                    pypi_0    pypi
pip                       21.2.4             pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
progressbar33             2.4                      pypi_0    pypi
protobuf                  3.19.4                   pypi_0    pypi
psutil                    5.9.3                    pypi_0    pypi
pvactools                 3.1.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pyensembl                 2.1.0                    pypi_0    pypi
pymp-pypi                 0.5.0                    pypi_0    pypi
pypandoc                  1.10                     pypi_0    pypi
pyrsistent                0.18.0                   pypi_0    pypi
pysam                     0.20.0                   pypi_0    pypi
python                    3.6.15          hb7a2778_0_cpython    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.6                     2_cp36m    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
pytz                      2022.6                   pypi_0    pypi
pyvcf                     0.6.8                    pypi_0    pypi
pyyaml                    5.4                      pypi_0    pypi
readline                  8.1.2                h0f457ee_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
requests                  2.27.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
roman                     3.3                      pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
sercol                    0.1.4                    pypi_0    pypi
serializable              0.2.1                    pypi_0    pypi
setuptools                49.6.0           py36h5fab9bb_3    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
shellinford               0.4.1                    pypi_0    pypi
simanneal                 0.5.0                    pypi_0    pypi
simplejson                3.17.6                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.39.4               h4ff8645_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
swagger-spec-validator    3.0.0                    pypi_0    pypi
tensorboard               2.2.2                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.2.2                    pypi_0    pypi
tensorflow-estimator      2.2.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
testfixtures              7.0.2                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tinytimer                 0.0.0                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
tqdm                      4.64.1                   pypi_0    pypi
typechecks                0.1.0                    pypi_0    pypi
typing-extensions         4.1.1                    pypi_0    pypi
urllib3                   1.26.12                  pypi_0    pypi
varcode                   1.0.3                    pypi_0    pypi
vaxrank                   1.4.0                    pypi_0    pypi
vcfpy                     0.13.4                   pypi_0    pypi
werkzeug                  2.0.3                    pypi_0    pypi
wget                      3.2                      pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
wrapt                     1.14.1                   pypi_0    pypi
xlrd                      2.0.1                    pypi_0    pypi
xlsxwriter                3.0.3                    pypi_0    pypi
xvfbwrapper               0.2.9                    pypi_0    pypi
xz                        5.2.6                h166bdaf_0    https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge
zipp                      3.6.0                    pypi_0    pypi

**Describe the bug**
Error in running pVACvector with a pVACseq output TSV.

**To Reproduce**
(pvactool) shpc_100668@shpc52:~$ pvacvector run \
> /home/shpc_1006/pvactool/pvacvector_example_data/input.tsv \
> Test \
> HLA-A*02:01,HLA-B*35:01,DRB1*11:01 \
> MHCflurry MHCnuggetsI MHCnuggetsII NNalign NetMHC PickPocket SMM SMMPMBEC SMMalign \
> /home/shpc_1006/pvactool/pvacvectortest/ \
> -e1 8,9,10 \
> -e2 15 \
> -v /home/shpc_1006/pvactool/pvacvector_example_data/vepout.vcf

**Log Output**
```
/home/shpc_1006/anaconda3/envs/pvactool/lib/python3.6/site-packages/vcfpy/header.py:415: FieldInfoNotFound: FORMAT DP2 not found using String/'.' instead
  FieldInfoNotFound,
/home/shpc_1006/anaconda3/envs/pvactool/lib/python3.6/site-packages/vcfpy/header.py:415: FieldInfoNotFound: FORMAT TAR not found using String/'.' instead
  FieldInfoNotFound,
/home/shpc_1006/anaconda3/envs/pvactool/lib/python3.6/site-packages/vcfpy/header.py:415: FieldInfoNotFound: FORMAT TIR not found using String/'.' instead
  FieldInfoNotFound,
/home/shpc_1006/anaconda3/envs/pvactool/lib/python3.6/site-packages/vcfpy/header.py:415: FieldInfoNotFound: FORMAT TOR not found using String/'.' instead
  FieldInfoNotFound,
/home/shpc_1006/anaconda3/envs/pvactool/lib/python3.6/site-packages/vcfpy/header.py:415: FieldInfoNotFound: FORMAT DP50 not found using String/'.' instead
  FieldInfoNotFound,
/home/shpc_1006/anaconda3/envs/pvactool/lib/python3.6/site-packages/vcfpy/header.py:415: FieldInfoNotFound: FORMAT FDP50 not found using String/'.' instead
  FieldInfoNotFound,
/home/shpc_1006/anaconda3/envs/pvactool/lib/python3.6/site-packages/vcfpy/header.py:415: FieldInfoNotFound: FORMAT SUBDP50 not found using String/'.' instead
  FieldInfoNotFound,
Traceback (most recent call last):
  File "/home/shpc_1006/anaconda3/envs/pvactool/bin/pvacvector", line 8, in <module>
    sys.exit(main())
  File "/home/shpc_1006/anaconda3/envs/pvactool/lib/python3.6/site-packages/pvactools/tools/pvacvector/main.py", line 50, in main
    args[0].func.main(args[1])
  File "/home/shpc_1006/anaconda3/envs/pvactool/lib/python3.6/site-packages/pvactools/tools/pvacvector/run.py", line 455, in main
    generator.execute()
  File "/home/shpc_1006/anaconda3/envs/pvactool/lib/python3.6/site-packages/pvactools/lib/pvacvector_input_fasta_generator.py", line 88, in execute
    transcripts_dict = self.parse_original_vcf()
  File "/home/shpc_1006/anaconda3/envs/pvactool/lib/python3.6/site-packages/pvactools/lib/pvacvector_input_fasta_generator.py", line 45, in parse_original_vcf
    VcfConverter(**{'input_file': self.input_vcf, 'output_file': tsv_file.name, 'sample_name': self.sample_name}).execute()
  File "/home/shpc_1006/anaconda3/envs/pvactool/lib/python3.6/site-packages/pvactools/lib/input_file_converter.py", line 301, in execute
    if genotype.gt_bases and alt not in genotype.gt_bases:
  File "/home/shpc_1006/anaconda3/envs/pvactool/lib/python3.6/site-packages/vcfpy/record.py", line 283, in gt_bases
    result.append(self.site.ALT[a - 1].value)
IndexError: list index out of range
```

**Output File**
None

**Expected behavior**
I have used VEP to annotate input.vcf from example data.

I'm really at a loss as to how to proceed, and any guidance would be much appreciated!
Thank you for your kind help!

**Comment by susannasiebert** [comment]
Hi @QianhuiXu,
I see that you closed this issue. May I ask what the source of this error was and how you resolved it? This will help future users who might encounter the same error.
Thanks,
Susanna

**Comment by QianhuiXu** [comment]
Thank you for your reply!
I used the Test.filtered.tsv(output of pvacseq_example_data) as the input.tsv then this issue was resolved.
