### ISSUE TITLE
Not sure if running correctly? TSV Empty or No Matches Found

### ISSUE THREAD

**Issue by nicoleversetwo** [griffithlab/pVACtools#886]
* pvactools version: 3.1.0
* Python version: 3.7..12
* Operating System: MAC OS / Docker

**Describe the bug**
I currently have pvactools installed on my local machine, and I have also set up the desktop version of docker to use the pvacseq:latest-slim version. I've looked through other issues / documentation and from the website it seems that if I'm lacking missense, frameshift, or infram indels I won't get results. I've gone through the recommended file preparation (outside of the phasing step, which I may choose to do later on). I can confirm I have these in my vcf, as the VEP output (attached) shows presence of these. I'm not sure if the file is still formatted incorrectly? Or if I've chosen incorrect alleles? Unfortunately my compressed VCF is still 54MB so I can't attach it but I have attached the VEP output summary. If there is a different pace I can share the input VCF, I am happy to do so.

**To Reproduce**
On MAC OS:
pvacseq run 48986-5113.vep.tx.vcf TUMOR HLA-A02:01,HLA-B35:01,DRB1*11:01 MHCflurry MHCnuggetsI MHCnuggetsII NNalign NetMHC PickPocket SMM SMMPMBEC SMMalign /Users/yeagern/pvacseq_output -e1 8,9,10 -e2 15 --iedb-install-directory /Users/yeagern

On Docker:
pvacseq run pvacseq_example_data/48986-5113.vep.tx.vcf TUMOR HLA-A*02:01,HLA-B*35:01,DRB1*11:01 MHCflurry MHCnuggetsI MHCnuggetsII NNalign NetMHC PickPocket SMM SMMPMBEC SMMalign /pvacseq_output_data -e1 8,9,10 -e2 15 --iedb-install-directory /opt/iedb

**Log Output**
On MacOS:
zsh: no matches found: HLA-A*02:01,HLA-B*35:01,DRB1*11:01

On Docker:
Executing MHC Class I predictions
Converting .vcf to TSV
Completed
Converting VCF to TSV
Completed
Generating Variant Peptide FASTA and Key File
Completed
Parsing the Variant Peptide FASTA and Key File
Completed
Calculating Manufacturability Metrics
Completed
The TSV file is empty. Please check that the input VCF contains missense, inframe indel, or frameshift mutations.
Executing MHC Class II predictions
Converting .vcf to TSV
Completed
Converting VCF to TSV
Completed
[VEP summary.pdf](https://github.com/griffithlab/pVACtools/files/10281734/VEP.summary.pdf)

Generating Variant Peptide FASTA and Key File
Completed
Parsing the Variant Peptide FASTA and Key File
Completed
Calculating Manufacturability Metrics
Completed
The TSV file is empty. Please check that the input VCF contains missense, inframe indel, or frameshift mutations.
Creating combined reports
File /pvacseq_output_data/MHC_Class_I/TUMOR.all_epitopes.tsv doesn't exist. Aborting.

**Output File**
If your bug is related to the contents of an output file, please paste the output file here.

**Expected behavior**
I was hoping after successfully running the test data through the pipeline in both my local and docker system, I'd be able to process one of our project files.

**Comment by susannasiebert** [comment]
That's certainly unexpected. Could you email us your VCF to help@pvactools.org for further debugging?

**Comment by nicoleversetwo** [comment]
Thank you! Sending on now.

**Comment by susannasiebert** [comment]
I'm able to confirm the same issue you are seeing. It looks like all of the genotypes for these variants in the tumor samples are 0/0 (homozygous reference) which means the variants were not called in the tumor. So then there is nothing for pVACseq to process as there are no tumor variants. I think this might point to some problem upstream in your pipeline as I would expect in a somatic pipeline all of the variants to be called in the tumor and then only some or none would be called in the normal. Or is the NORMAL and TUMOR sample simply mislabeled in your VCF?

**Comment by susannasiebert** [comment]
Side note, I also see that a lot of your variants have a FILTER applied so you might want to consider running pvacseq with the `--pass-only` flag set.

**Comment by nicoleversetwo** [comment]
Hi there!

Thanks for the quick response. The input file I used for the VEP annotation
was actually an output file from Mutect2. We have used other callers
(strelka, SomaticSniper, Varscan) and have consensus files of all of these.
Should I have used the raw VCF files from our samples? The NORMAL in the
file I shared is from our Germline sequencing, and TUMOR from the tumor, I
just confirmed with the other bioinformatician in our group that produced
these files.

I had actually tried the pass-only flag but got the same result!

Thanks,

Nicole

**Comment by nicoleversetwo** [comment]
I'm starting to think that the issue is with the heavy filtering done on our VCFs after they have been run through various callers. I just processed our raw VCF in the same manner and it is currently running in the docker instance, yay!!! I appreciate your very quick and thorough responses! Thank you again for being so helpful. I'll close this out as it looks like we're all set now!
