### ISSUE TITLE
some samples failed bacause of not permission to access /tools_api/mhci/ & unfinished output_parser.py

### ISSUE THREAD

**Issue by vickysyy** [griffithlab/pVACtools#892]
Particular errors occurred with some samples during the process.

![image](https://user-images.githubusercontent.com/106020517/210190165-12f2f4df-6feb-4025-9229-dd5dfd47b3cc.png)
![image](https://user-images.githubusercontent.com/106020517/210190173-76b7b020-a63f-4579-8465-b840e46c96d6.png)

**Comment by susannasiebert** [comment]
I'm sorry you're running into errors running pVACtools. The first error indicates that your IP address was blacklisted by the IEDB API for executing too many requests in quick succession (e.g. when running many samples in parallel). In that scenario we recommend switching to the standalone IEDB tools by either installing them locally or using our `latest` or `latest-slim` docker containers.

The second error occurs when restarting a run where a request to IEDB failed. Removing the existing output directory and starting from scratch should resolve this problem.

**Comment by susannasiebert** [comment]
I'm closing this as resolved but feel free to reopen if you're still running into problems.
