### ISSUE TITLE
Suggestion: add necessity of --normal-sample-name with multi-sample VCF to usage guide

### ISSUE THREAD

**Issue by bozbezbozzel** [griffithlab/pVACtools#893]
`pvacseq` couldn't make a tsv of my annotated Mutect2 output without both the sample name (of the tumor) and the name of the normal sample with the option `--normal-sample-name`. 

Mutect2 output has 2 extra columns in the `#CHROM` header for both normal and tumor, and they both have `GT` info, so I figured that what went wrong is that `pvacseq` tried to use the genotype info of the normal sample since that comes before the tumor. Now everything is running as normal!

**Comment by susannasiebert** [comment]
It shouldn't be necessary to specify the normal sample in a multi-sample VCF. For multi-sample VCFs pVACseq will use the sample with `sample_name` from the command line parameters to pick the matching sample based on the sample names in the `CHROM` header line after the `FORMAT` column. If that is not working right, then that's a bug. What error where you getting?

**Comment by bozbezbozzel** [comment]
Hi Susanna, I haven't had the time to look into this again but I will try to do so next week and give you an answer.

**Comment by susannasiebert** [comment]
I'm closing this issue assuming that it was a simple misunderstanding but do reopen it if you're still running into problems.
