### ISSUE TITLE
To use phased.vcf as input of pVACseq run

### ISSUE THREAD

**Issue by yzhan360** [griffithlab/pVACtools#896]
Hi, I have successfully implemented pVACseq workflow for our project. Thanks for your work!
I just realized one problem. I used phased VCF file with annotation and coverage data as the input of pVACseq run, leaving PHASED_PROXIMAL_VARIANTS_VCF as default (None). 
Can I used the phased VCF instead of unphased VCF as input? If so, do I need to set the PHASED_PROXIMAL_VARIANTS_VCF as phased VCF again?
Thanks!

**Comment by susannasiebert** [comment]
Did you use our [recommended steps](https://pvactools.readthedocs.io/en/latest/pvacseq/input_file_prep/proximal_vcf.html) for creating the phased VCF? If so, I would not recommend using that VCF as your main input VCF as it will contain germline mutations, which shouldn't be included as vaccine candidates. The somatic tumor VCF is one of the inputs to creating the phased VCF and is what you should use as your main input VCF.

**Comment by yzhan360** [comment]
Thanks Susanna! Yes I used the recommended steps for phased VCF, which contains germline mutations. I didn't find such information from your document. I'll use somatic tumor VCF as input of pvacseq run. Thanks again.

**Comment by susannasiebert** [comment]
I apologize for not replying to this issue sooner but I updated our documentation (the "bgzip and index the pVACseq main input VCF" section [here](https://pvactools.readthedocs.io/en/latest/pvacseq/input_file_prep/proximal_vcf.html#bgzip-and-index-the-pvacseq-main-input-vcf) to clarify that the main input VCF to pVACseq should be your somatic VCF. I'm resolving this issue but please reopen it if you have any additional questions.
