### ISSUE TITLE
failed to use pvacseq run  wtih nohup!

### ISSUE THREAD

**Issue by xmy1990** [griffithlab/pVACtools#897]
Thanks for your great work!
I have ran pvacseq run successfully in command line on linux, 
but when I try to use pvacseq run  wtih nohup &, it failed, the errors are below:

Traceback (most recent call last):
File "xxx/predict_binding.py", line 520, in <module>
Prediction().main()
File "xxx/predict_binding.py", line 498, in main
stdin = sys.stdin.readline().strip()
OSError: [Errno 9] Bad file descriptor

pvacseq run  can not run with nohup?

Thanks for your great work!

**Comment by susannasiebert** [comment]
@xmy1990 I'm sorry you were experiencing problems with using pVACtools with nohup. I see that you have resolved this issue. Did you find out what the problem was? It would be great if we could document that here for other users that might run into the same error.

**Comment by xmy1990** [comment]
Thanks @susannasiebert
I have ran pvacseq run successfully with nohup like this,

nohup sh pvacseq run xxxxx > outfile.txt < /dev/null &
