### ISSUE TITLE
Reading a fasta file generated from fast files obtained from extracting SRA files

### ISSUE THREAD

**Issue by maheshworpaudel5001** [griffithlab/pVACtools#900]
Hello there,
I have been trying to understand a fasta file I have generated from a fast file that I obtained from an SRA accession. When I generated fasta files from fastq files, I got two files in the file format name "SRRXXXXXX_1.fasta" and "SRRXXXXXX_2.fasta".

I checked the description of the SRAs in the dbGAP website and it says these files correspond to a WXS of normal DNA of a patient. Each of these files have millions of sequences but each of length 151. A sequence looks like following:

>SRRXXXXXXXX.1264 1264 length=151
TGGTGGTGGGGGCGGTGGGGGTGGTGTTAGTACCCCATCTTGTAGGTCTGAAACACAAAGTGTGGGGTGTCTAGGGAAGAAGGTGTGTGACCAGGGAGGTCCCCGGCCCAGCTCCCATCCCAGAACCCAGCTCACCTACCTTGAGAGGCTC

My questions:
1. What are the _1.fasta and _2.fasta files?
2. How do I know a particular sequence chromosome number?
3. Since, these are DNA sequences, my guess was that _1.fasta and _2.fasta give sequences for 22 pairs of chromosomes leaving out the chromosome X or Y. But the total number of sequences are not divisible by 22. So, I do not understand, what the total number of sequences meant?
4. In the example sequence I provided, could you help me understand different parts in it? 

Thanks a lot.

**Comment by susannasiebert** [comment]
Hi @maheshworpaudel5001, it seems like your question isn't really related to pVACtools. I would recommend contacting dbGAP or the team that uploaded these reads to the SRA for further clarification.
