### ISSUE TITLE
Mutation position column sometimes are empty

### ISSUE THREAD

**Issue by boyangzhao** [griffithlab/pVACtools#902]
* pvactools version: 3.0.0
* Python version: 3.8
* Operating System: linux

I finding that in some pvacseq outputs, that the Mutation Position column is left as empty. I saw there were some earlier mentioning of the position columns (e.g. #701 but doesn't seen to be addressing this).

One example, is 

`15,85533931,85533931,C,CT,ENST00000560302.5,1.0,ENSG00000170776,FS,L/LX,177,AKAP13,ENST00000560302.5:c.538dup,ENSP00000453634.1:p.Ter180LeufsTer35,HLA-A*11:01,8,10,,FLMGLLFY,,...`

where you see the peptide length and sub-peptide mutation are defined, but the mutation position is not. In some outputs, there are several thousands of these. Is this expected behavior?

**Comment by susannasiebert** [comment]
This doesn't look like expected behavior to me. Is this the raw output (i.e. not being read in by another program like Excel)? Is this in the filtered file or the all_epitopes file? The Mutation position should either be a positive integer if the mutation starts in the epitope or 0 if the mutation started before the epitope (e.g. for epitopes in the tail of a frameshift).

**Comment by boyangzhao** [comment]
It is the raw output, in the all_epitopes file. There is also `Mutation` field that are sometimes empty as well (perhaps unrelated, but maybe here it is expected).

**Comment by susannasiebert** [comment]
Would you be able to share your output all_epitopes file with us as well as your input VCF and the exact pVACtools command you ran? I would like to investigate this further.

**Comment by boyangzhao** [comment]
I've sent you a working vcf file with the command.

**Comment by susannasiebert** [comment]
I received your email with the data. It looks like all of these cases are frameshifts where the WT Epitope Seq is NA and the Mutation Position is NA. I have to make an correction to my previous statement, that this particular case is expected in cases where the MT Epitope Seq is in the tail of the frameshift and has no or little overlap with the WT transcript. However, I'm unable to reproduce a case where these columns from your original output line are empty. Did you use some sort of parser that interpreted NAs as empty columns?

**Comment by boyangzhao** [comment]
Ah yes, the earlier output line was the output from a follow-on parser, that converted the NA to empty (in csv format). And the Mutation column was our own parser's issue (it misinterpreted N/A mutation as nan). Ok then that makes sense and I consider this is not an issue anymore. Thank you!

**Comment by susannasiebert** [comment]
Awesome. I'll resolve this issue but feel free to reopen if you have any additional questions related to this issue.

**Comment by bioxu** [comment]
> I received your email with the data. It looks like all of these cases are frameshifts where the WT Epitope Seq is NA and the Mutation Position is NA. I have to make an correction to my previous statement, that this particular case is expected in cases where the MT Epitope Seq is in the tail of the frameshift and has no or little overlap with the WT transcript. However, I'm unable to reproduce a case where these columns from your original output line are empty. Did you use some sort of parser that interpreted NAs as empty columns?


Hi, I want to know why frameshifts' WT Epitope Seq would be NA?

**Comment by susannasiebert** [comment]
We only associate a WT Epitope with a MT epitope if at least half of their amino acids overlap consecutively. Otherwise we set it to NA and treat it as a novel peptide. The comparison to the MT epitope is not meaningful when there is little to no overlap to the MT epitope.
