### ISSUE TITLE
Anyelse Filtering Commands ?

### ISSUE THREAD

**Issue by xmy1990** [griffithlab/pVACtools#903]
Thanks for your great work!
I have set the Filtering Commands:

-b 500
-m median
--normal-cov 5
--normal-vaf 0.03
--tdna-cov 10
--tdna-vaf 0.05

but, the below result was in  .all_epitopes.tsv 
chrX    151869811       151869812       G       A       ENST00000329342.5       NA      ENSG00000197172 missense        E/K     168 MAGEA6   ENST00000329342.5:c.502G>A      ENSP00000329199.5:p.Glu168Lys   HLA-B*15:01     11      9       3       LMKVDPIGHVY     LMEVDPIGHVY  MHCnuggetsI     9.8     62.68   6.396   MHCflurry       0.224   0.885   113     0.806   NA      NA      113     0.01    NA  NA       98.263  1306.519        13.296  0.54    3.8     311.7182848590268       68.64670329492941       0.8852499999999996      0.22462.68   9.8     NA      NA      2301.32 127.88  3.8     0.54    4062.6458292605503      1422.3578464915408      5.9     1.3     NA  NA       NA      NA      NA      NA      NA      NA      236.MAGEA6.ENST00000329342.5.missense.168E/K    -0.18571428571428572    0.7714285714285715   False   False   False   0       False   0

its  Best MT Score  and Median MT Score are all <500nM,
its Tumor DNA Depth >10 and Tumor DNA VAF >0.05,
its Normal Depth >5 and Normal VAF <0.03
as follow:
Gene Name       HLA Allele      MT Epitope Seq  WT Epitope Seq  Best MT Score   Tumor DNA Depth Tumor DNA VAF   Normal Depth    Normal VAF   Median MT Score
MAGEA6  HLA-B*15:01     LMKVDPIGHVY     LMEVDPIGHVY     9.8     113     0.806   113     0.01    98.263

not in the .filtered.tsv, I do not know why

the all log/inputs.yml was :
additional_report_columns: null
allele_specific_binding_thresholds: false
alleles:
HLA-A*01:01
HLA-A*30:02
HLA-B*15:01
HLA-B*18:01
HLA-C*03:03
HLA-C*05:01
binding_threshold: 500
blastp_db: refseq_select_prot
blastp_path: ncbi-blast-2.13.0+/bin/blastp
downstream_sequence_length: 1000
epitope_lengths:
8
9
10
11
exclude_NAs: false
expn_val: 1.0
fasta_size: 200
iedb_executable: mhc_i/src/predict_binding.py
iedb_retries: 5
input_file: 8_TN_vep.vcf
input_file_type: vcf
keep_tmp_files: false
maximum_transcript_support_level: 1
minimum_fold_change: 0.0
n_threads: 2
net_chop_method: null
net_chop_threshold: 0.5
netmhc_stab: false
normal_cov: 5
normal_sample_name: n-test
normal_vaf: 0.03
output_dir: MHC_Class_I
pass_only: true
percentile_threshold: null
phased_proximal_variants_vcf: null
prediction_algorithms:
MHCflurry
MHCnuggetsI
NetMHC
PickPocket
SMM
SMMPMBEC
proximal_variants_file: null
pvactools_version: 3.1.1
run_reference_proteome_similarity: false
sample_name: test
species: human
tdna_cov: 10
tdna_vaf: 0.05
tmp_dir: MHC_Class_I/tmp
top_score_metric: median
trna_cov: 10
trna_vaf: 0.25
tumor_purity: null

Is there anyother Filtering Commands  that I had missed?
Thanks for your great work!

**Comment by susannasiebert** [comment]
This epitope is likely being filtered out by the top score filter because there is an even better candidate available for this particular variant. Please see [our documentation](https://pvactools.readthedocs.io/en/latest/pvacseq/output_files.html#filters-applied-to-the-filtered-tsv-file) for more information on the filtering steps.

**Comment by xmy1990** [comment]
Thank you so much for your kind help!

**Comment by xmy1990** [comment]
Thanks for your great work!

I haver another question!
From .all_epitopes.tsv to .filtered.tsv, pvacseq just kept only one epitope for each variant (Chromosome - Start - Stop - Reference - Variant), some meaningful epitopes may be filtered.
Is there any option I can set to keep more epitopes for a variant, not just the only top one?
Thanks again!

**Comment by xmy1990** [comment]
Thanks a lot!
I am sorry for another question about the --percentile-threshold setting, 
--percentile-threshold PERCENTILE_THRESHOLD
                        Report only epitopes where the mutant allele has a
                        percentile rank below this value. (default: None)

how to set the cutoff of the --percentile-threshold ?
how the Percentile of each candidate epitope was calculated？ 
the small the better (eg, Best MT Percentile)?

Thanks！

**Comment by susannasiebert** [comment]
The percentile metrics are provided directly by the prediction algorithms you chose to run and reflect where the candidate epitope ranks compared to the binding affinity of other epitopes to the same HLA allele in the algorithm's training data set. The lower the better. The threshold will either be applied to the Median MT Percentile column or the Best MT Percentile, depending on the --top-score-metric chosen. The default is median.

**Comment by susannasiebert** [comment]
I'm closing this issue as resolved but do feel free to reopen it if you have any additional questions.
