### ISSUE TITLE
Comparison with previous command breaks parallel multi-sample processing  

### ISSUE THREAD

**Issue by danilotat** [griffithlab/pVACtools#907]
* pvactools version: 3.1.1
* Python version: Python 3.7.12
* Operating System: 

**Describe the bug**

In a common scenario, I've got multiple samples against which I want to run pvactools. Given an HPC cluster, fairly common in a bioinformatic research group, to speed up the processing I'd process each sample simultaneously using a job array. In this case, **the working directory** **will be the same**, but each job contains inputs (vcf, HLA genotypes) and will produce the respective outputs. In order to ensure reproducibility, pvacseq keeps comparing a submitted command against a next one and, as you could imagine, in this scenario, only the first batch would be processed, and the other submissions are aborted.

 

**To Reproduce**

```bash
#!/bin/bash
#SBATCH --job-name=pvacseq
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --time=4:00:00
#SBATCH --array=0-50
#SBATCH --mem-per-cpu=8GB
VCF_files=(/input_dir/*mismatch*.vcf.gz)
ALLELES_files=(/input_dir/*allele_input_pvacseq.csv)
VCF_file=$(basename ${VCF_files[$SLURM_ARRAY_TASK_ID]})
HLA_file=$(basename ${ALLELES_files[$SLURM_ARRAY_TASK_ID]})
pat_name=$(echo $VCF_file | cut -d'_' -f1,2,3)
HLA_genotype=$(cat ${ALLELES_files[$SLURM_ARRAY_TASK_ID]})
DEST_PATH="/peptides"
softwares="MHCflurry MHCnuggetsI NNalign NetMHC NetMHCpan PickPocket SMM SMMPMBEC SMMalign"

pvacseq run $VCF_file $pat_name $HLA_genotype $softwares $DEST_PATH -e1 8,9,10,11
```

**Log Output**

Follows a quick example on the error message.
```
Executing MHC Class I predictions
Restart inputs are different from past inputs:
Past input: input_file - /input_dir/19_PRE_ref_transcript_mismatch_reporter.vcf.gz
Current input: input_file - /input_dir/12_PRE_ref_transcript_mismatch_reporter.vcf.gz
Aborting
```

**Expected behavior**

Only the first VCF, so the first file of the input array, is processed: all the other files wouldn't because the working directory remains the same, and pvacseq prevents concurrent processing of multiple samples. Is this somehow bypassable?
I'd suggest to use a different strategy for temporary files generation (maybe named using sample name in a user specified PATH?) and/or to make the integrity check optional for end users. In my case, I need to switch from a fast solution (70 concurrent jobs, ~1h) to a for loop (single job, long queue, ~24-30h).

**Comment by susannasiebert** [comment]
Hi @danilotat,

The behavior you're describing is intentional. The chosen output directory is supposed to be patient-specific. I recommend updating your script to include the `pat_name` in your `DEST_PATH` and running a `mkdir` command before running pVACseq.

**Comment by danilotat** [comment]
Hi @susannasiebert , thanks for the prompt response. Passing a patient-specific folder works (still doesn't work because of too many concurrent request to the IEDB api.. surely not your fault), apart from producing a nested tree of subdirectories, that could be a bit annoying with many samples. Are you planning to provide a less stringent folder setup? Maybe by not creating a standard subdirectory (always named the same) and by automatically create a temp directory in respect to the user `patient_name` parameter? In that case, would you accept pull requests?
