### ISSUE TITLE
TSVfile is empty

### ISSUE THREAD

**Issue by dhy2002** [griffithlab/pVACtools#909]
* pvactools version:3.1.1
* Python version:3.7.15
* Operating System:linux64

After I run pvacseq, it seems that the tsv is empty. And I checked the vcf file. But there do exist annotations like"frameshifht mutations". Besides the GT information doesn't seem to be missing #502 . 

My vep command is:
`./vep --input_file ../A3_MLK_T1.PASS.anno.vcf --output_file ../A3_MLK_T1.PASS.VEP.vcf--format vcf --vcf --symbol --terms SO --tsl --cache --cache_version 105 --dir ./ensembl-vep-release-109 --fasta ./ensembl-vep-release-109/Homo_sapiens.GRCh37.dna.primary_assembly.fa.gz  --offline --hgvs --force_overwrite --plugin Frameshift --plugin Wildtype --dir_plugins ./
`

My pvacseq run command is:
`pvacseq run ./A3_MLK_T1.PASS.VEP.vcf A3 HLA-A*02:01,HLA-B*15:01,HLA-B*54:01,HLA-C*01:02,HLA-C*03:03 {MHCflurry,MHCnuggetsI,MHCnuggetsII,NNalign,NetMHC,PickPocket,SMM,SMMPMBEC,SMMalign} ./test1 --iedb-install-directory ./ --pass-only`

While the output shows that 
**Executing MHC Class I predictions
Converting .vcf to TSV
TSV file already exists. Skipping.
Converting VCF to TSV
Completed
Generating Variant Peptide FASTA and Key File
Completed
Parsing the Variant Peptide FASTA and Key File
Completed
Calculating Manufacturability Metrics
Completed
The TSV file is empty. Please check that the input VCF contains missense, inframe indel, or frameshift mutations.**

The top 200 lines of input vcf is attached here. 
[test.zip](https://github.com/griffithlab/pVACtools/files/10876856/test.zip)

And the output files are like this:

[MHC_Class_I.zip](https://github.com/griffithlab/pVACtools/files/10876854/MHC_Class_I.zip)

**Comment by susannasiebert** [comment]
It looks like you are running pVACseq with the `A3` sample. That sample is uncalled (GT field is `.`) on every line. Did you mean to use the `A3_MLK_T1` sample?

**Comment by susannasiebert** [comment]
Closing this issue since there hasn't been any further activity. Please do reopen if you're still running into problems.
