### ISSUE TITLE
GATK4 does not support CombineVariants and Readbackphasing to create phased VCF of proximal variants.

### ISSUE THREAD

**Issue by PierreLaplante** [griffithlab/pVACtools#987]
Hello,

As you may know GATK4 does not support the tools necessary for the creation of phased VCF of proximal variants CombineVariants and Readbackphasing.

So, should I use a legacy version of GATK? (if yes, which one?)
Or if I can use GATK4, which tools should I replace Readbackphasing with ? As I understood, in this case, MergeVCFs can replace CombineVariants, but Haplotypecaller does not work the same way as Readbackphasing. 

Thank you for your help and have a good day.

**Comment by susannasiebert** [comment]
Unfortunately, we haven't been able to find any alternative tools to Readbackphasing so we rely on legacy GATK for this particular step. In our pipelines we use GATK 3.6.0 for this purpose. I will update our documentation to mention this.

**Comment by PierreLaplante** [comment]
Ok, thank you for the info!
